// apps/dev-rxdb-vue/src/pages/TodoPage.vue
<script lang="ts" setup>
import { EntityStaticType, reorderTargetForMove, type HistoryItem, type UUID } from '@aiao/rxdb';
import { Task } from '@aiao/rxdb-test/entities';
import { injectRxDB, useFindAll } from '@aiao/rxdb-vue';
import { FixedRowDrag, type FixedRowDragState, type FixedRowDrop } from '@aiao/utils';
import { useVirtualizer } from '@tanstack/vue-virtual';
import { ArrowDown, ArrowUp, GripVertical, History, Pen, Plus, Redo2, Undo2, X } from '@lucide/vue';
import { Subscription } from 'rxjs';
import { computed, nextTick, onMounted, onUnmounted, ref, type ComponentPublicInstance } from 'vue';
import HistorySidebar from '../app/components/HistorySidebar.vue';
import { pairVirtualRows } from '../app/utils/virtual-rows';

const ITEM_SIZE = 48;

const rxdb = injectRxDB()!;
const mainContainerRef = ref<HTMLDivElement | null>(null);
const fullHeaderRef = ref<HTMLDivElement | null>(null);
const todoListRef = ref<HTMLDivElement | null>(null);
const editInputRefs = new Map<string, HTMLInputElement>();

const inputValue = ref('');
const currentTab = ref<'all' | 'active' | 'completed'>('all');
const completedSort = ref<'asc' | 'desc'>('asc');
const editingTodoIds = ref<Set<string>>(new Set());
const editValues = ref<Map<string, string>>(new Map());
const showHistory = ref(true);
const showStickyHeader = ref(false);
const addingCount = ref<number | null>(null);
// 拖拽中的起点与落点；null 表示没在拖
const drag = ref<FixedRowDragState | null>(null);
// 一次重排正在落库；期间不允许开始新的拖拽
const reorderPending = ref(false);
// 最近一次重排失败的原因；下一次重排开始时清掉
const reorderError = ref<string | null>(null);

// History - 手动订阅 Observable
const history = rxdb.versionManager.history(Task);
const undoCount = ref(0);
const redoCount = ref(0);
const histories = ref<HistoryItem[]>([]);

let subscriptions: Subscription[] = [];

// 查询条件
const todoQueryOptions = computed<EntityStaticType<typeof Task, 'findAllOptions'>>(() => {
  const options: EntityStaticType<typeof Task, 'findAllOptions'> = {
    where: {
      combinator: 'and',
      rules: []
    },
    orderBy: [
      {
        field: 'completed',
        sort: completedSort.value
      },
      // 组内手动顺序；id 只在 sortOrder 相同时定序，保证结果稳定
      {
        field: 'sortOrder',
        sort: 'asc'
      },
      {
        field: 'id',
        sort: 'asc'
      }
    ]
  };

  if (currentTab.value === 'active') {
    options.where.rules.push({
      field: 'completed',
      operator: '=',
      value: false
    });
  } else if (currentTab.value === 'completed') {
    options.where.rules.push({
      field: 'completed',
      operator: '=',
      value: true
    });
  }

  return options;
});

const todoResource = useFindAll(Task, todoQueryOptions);
const todos = computed(() => todoResource.value ?? []);

// 虚拟滚动
const rowVirtualizerOptions = computed(() => ({
  count: todos.value.length,
  getScrollElement: () => mainContainerRef.value,
  estimateSize: () => ITEM_SIZE,
  overscan: 10
}));

const virtualizer = useVirtualizer(rowVirtualizerOptions);
const virtualRows = computed(() => pairVirtualRows(todos.value, virtualizer.value.getVirtualItems()));

// 计算派生状态
const activeTodoCount = computed(() => todos.value.filter(todo => !todo.completed).length);
const completedTodos = computed(() => todos.value.filter(todo => todo.completed));
const isAllCompleted = computed(() => todos.value.length > 0 && todos.value.every(todo => todo.completed));
const disabledToggleAllBtn = computed(() => todos.value.length === 0);
const disabledClearCompletedBtn = computed(() => completedTodos.value.length === 0);
// 「全部」页混着两个分组且受排序方向影响，不提供手柄；加载中或待决重排时下标可能过期
const canDrag = computed(
  () => currentTab.value !== 'all' && !todoResource.isLoading && !reorderPending.value && todos.value.length >= 2
);

const requiredElement = (element: HTMLElement | null, name: string): HTMLElement => {
  if (!element) throw new Error(`拖拽需要的元素 ${name} 尚未渲染`);
  return element;
};

// 把被拖行放到落点：对着起拖时的 id 序列换算成邻居目标后交给 Repository.reorder()；换算失败也显示在页面上
const dropTodo = async ({ id, ids, fromIndex, toIndex }: FixedRowDrop<UUID>) => {
  reorderPending.value = true;
  reorderError.value = null;
  try {
    const target = reorderTargetForMove(ids, fromIndex, toIndex);
    if (target) await rxdb.entityManager.getRepository(Task).reorder(id, target);
  } catch (error) {
    reorderError.value = error instanceof Error ? error.message : String(error);
  } finally {
    reorderPending.value = false;
  }
};

// 会话绑定起拖时的 id 序列，列表在拖拽中变了（活查询插入 / 删除、切 tab）就取消
const rowDrag = new FixedRowDrag<UUID>({
  rowHeight: ITEM_SIZE,
  scrollElement: () => requiredElement(mainContainerRef.value, 'todo-page'),
  listElement: () => requiredElement(todoListRef.value, 'todo-list'),
  ids: () => todos.value.map(todo => todo.id),
  onChange: state => (drag.value = state),
  onDrop: drop => void dropTodo(drop)
});

const startDrag = (event: PointerEvent, index: number) => {
  if (!canDrag.value) return;
  rowDrag.start(event, index);
};

// 落点指示：上移画在目标行上沿，下移画在下沿，与 reorderTargetForMove 的插入位置一致
const dropShadow = (index: number): string | undefined => {
  const state = drag.value;
  if (!state || state.overIndex !== index || state.overIndex === state.fromIndex) return undefined;
  return `inset 0 ${state.overIndex < state.fromIndex ? 2 : -2}px 0 var(--color-primary)`;
};

// Sticky header 检测
const checkVisibility = () => {
  const mainElement = mainContainerRef.value;
  const headerElement = fullHeaderRef.value;

  if (!mainElement || !headerElement) return;

  const scrollTop = mainElement.scrollTop;
  const headerOffsetTop = headerElement.offsetTop;
  const headerHeight = headerElement.offsetHeight;
  const shouldShow = scrollTop > headerOffsetTop + headerHeight;
  showStickyHeader.value = shouldShow;
};

onMounted(() => {
  subscriptions = [
    history.undoCount$.subscribe(value => (undoCount.value = value)),
    history.redoCount$.subscribe(value => (redoCount.value = value)),
    history.histories$.subscribe(value => (histories.value = value))
  ];

  const mainElement = mainContainerRef.value;
  if (mainElement) {
    mainElement.addEventListener('scroll', checkVisibility);
    checkVisibility();
  }
});

onUnmounted(() => {
  subscriptions.forEach(sub => sub.unsubscribe());
  rowDrag.dispose();

  const mainElement = mainContainerRef.value;
  if (mainElement) {
    mainElement.removeEventListener('scroll', checkVisibility);
  }
});

const addTodo = async (event?: Event) => {
  event?.preventDefault();
  const value = inputValue.value.trim();
  if (!value) return;

  const todo = new Task({ title: value });
  await todo.save();
  inputValue.value = '';
};

const toggleTodoCompletion = async (event: Event, todo: Task) => {
  const isEditing = editingTodoIds.value.has(todo.id);
  if (isEditing) return;

  event.preventDefault();
  const target = event.target as HTMLInputElement;
  todo.completed = target.checked;
  await todo.save();
};

const startEditing = (event: Event, todo: Task) => {
  event.preventDefault();
  event.stopPropagation();
  editingTodoIds.value = new Set(editingTodoIds.value).add(todo.id);
  editValues.value = new Map(editValues.value).set(todo.id, todo.title);

  nextTick(() => {
    const input = editInputRefs.get(todo.id);
    input?.focus();
    input?.select();
  });
};

const saveTodo = async (event: Event, input: HTMLInputElement, todo: Task) => {
  event.preventDefault();
  event.stopPropagation();

  if (!editingTodoIds.value.has(todo.id)) return;

  const editValue = editValues.value.get(todo.id);
  if (editValue !== undefined) {
    todo.title = editValue;
  }

  const newSet = new Set(editingTodoIds.value);
  newSet.delete(todo.id);
  editingTodoIds.value = newSet;

  const newMap = new Map(editValues.value);
  newMap.delete(todo.id);
  editValues.value = newMap;

  await todo.save();
  input.blur();
};

const cancelEditing = (todo: Task) => {
  if (!editingTodoIds.value.has(todo.id)) return;

  const newSet = new Set(editingTodoIds.value);
  newSet.delete(todo.id);
  editingTodoIds.value = newSet;

  const newMap = new Map(editValues.value);
  newMap.delete(todo.id);
  editValues.value = newMap;
};

const removeTodo = async (event: Event, todo: Task) => {
  event.preventDefault();
  event.stopPropagation();
  await todo.remove();
};

const toggleAllTodos = async () => {
  const newCompletedState = !isAllCompleted.value;
  const todosToUpdate = todos.value.filter(d => d.completed === isAllCompleted.value);

  todosToUpdate.forEach(todo => {
    todo.completed = newCompletedState;
  });

  await rxdb.entityManager.saveMany(todosToUpdate);
};
const clearCompleted = async () => {
  await rxdb.entityManager.removeMany(completedTodos.value);
};

const toggleCompletedSort = () => {
  completedSort.value = completedSort.value === 'asc' ? 'desc' : 'asc';
};

const toggleHistory = () => {
  showHistory.value = !showHistory.value;
};

const stickyTabClick = (tab: 'all' | 'active' | 'completed') => {
  const element = mainContainerRef.value;
  if (!element) return;

  let scrollTimeout: number;
  const onScrollEnd = () => {
    clearTimeout(scrollTimeout);
    scrollTimeout = window.setTimeout(() => {
      currentTab.value = tab;
      element.removeEventListener('scroll', onScrollEnd);
    }, 50);
  };

  element.addEventListener('scroll', onScrollEnd);
  element.scrollTo({ top: 0, behavior: 'smooth' });

  setTimeout(() => {
    element.removeEventListener('scroll', onScrollEnd);
    clearTimeout(scrollTimeout);
  }, 5000);
};

const addManyTodo = async (total: number) => {
  addingCount.value = total;
  const newTodos: Task[] = [];
  for (let i = 0; i < total; i++) {
    const todo = new Task();
    todo.title = `test-${i}`;
    newTodos.push(todo);
  }
  await rxdb.entityManager.saveMany(newTodos);
  addingCount.value = null;
};

const undo = () => {
  void history.undo();
};

const redo = () => {
  void history.redo();
};

const setEditInputRef = (id: string, el: Element | ComponentPublicInstance | null) => {
  if (el instanceof HTMLInputElement) editInputRefs.set(id, el);
};
</script>

<template>
  <div class="flex h-full">
    <!-- History Sidebar -->
    <HistorySidebar
      :histories="histories"
      :scope-type="history.type"
      :show="showHistory"
      @close="toggleHistory"
      border-side="left"
    />

    <main
      class="h-full min-w-0 flex-1 overflow-auto"
      data-testid="todo-page"
      ref="mainContainerRef"
    >
      <!-- Sticky Header (简化版) -->
      <div
        class="border-base-300 bg-base-100 sticky top-0 z-10 border-b px-4 py-2 shadow-sm"
        v-if="showStickyHeader"
      >
        <div class="mx-auto flex max-w-4xl items-center justify-between">
          <div class="flex items-center gap-3">
            <h2 class="text-lg font-semibold">Todos</h2>
            <div class="badge badge-primary badge-sm">{{ activeTodoCount }} 待办</div>
          </div>
          <div
            class="tabs tabs-boxed tabs-xs"
            role="tablist"
          >
            <button
              :class="['tab', { 'tab-active': currentTab === 'all' }]"
              @click="stickyTabClick('all')"
              type="button"
            >
              全部
            </button>
            <button
              :class="['tab', { 'tab-active': currentTab === 'active' }]"
              @click="stickyTabClick('active')"
              type="button"
            >
              进行中
            </button>
            <button
              :class="['tab', { 'tab-active': currentTab === 'completed' }]"
              @click="stickyTabClick('completed')"
              type="button"
            >
              已完成
            </button>
          </div>
        </div>
      </div>

      <!-- Full Header -->
      <div
        class="border-base-300 flex-none border-b p-4"
        ref="fullHeaderRef"
      >
        <div class="mx-auto flex max-w-4xl flex-col gap-3">
          <!-- Title Bar -->
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-3">
              <h1 class="text-2xl font-bold">Todos</h1>
              <div
                class="badge badge-primary"
                data-testid="todo-count"
                >{{ activeTodoCount }} 待办</div
              >

              <!-- Batch Add Dropdown -->
              <div class="dropdown dropdown-end">
                <button
                  class="btn btn-circle btn-sm"
                  aria-label="批量添加"
                  data-testid="todo-batch-add"
                  tabindex="0"
                >
                  <Plus :size="16" />
                </button>
                <ul class="menu dropdown-content rounded-box bg-base-200 z-[1] w-40 p-2 shadow">
                  <li>
                    <button
                      :disabled="addingCount === 1"
                      @click="addManyTodo(1)"
                      data-testid="todo-batch-option-1"
                    >
                      <span
                        class="loading loading-spinner loading-xs"
                        v-if="addingCount === 1"
                      />
                      添加 1 条
                    </button>
                  </li>
                  <li>
                    <button
                      :disabled="addingCount === 10"
                      @click="addManyTodo(10)"
                      data-testid="todo-batch-option-10"
                    >
                      <span
                        class="loading loading-spinner loading-xs"
                        v-if="addingCount === 10"
                      />
                      添加 10 条
                    </button>
                  </li>
                  <li>
                    <button
                      :disabled="addingCount === 100"
                      @click="addManyTodo(100)"
                      data-testid="todo-batch-option-100"
                    >
                      <span
                        class="loading loading-spinner loading-xs"
                        v-if="addingCount === 100"
                      />
                      添加 100 条
                    </button>
                  </li>
                  <li>
                    <button
                      :disabled="addingCount === 1000"
                      @click="addManyTodo(1000)"
                      data-testid="todo-batch-option-1000"
                    >
                      <span
                        class="loading loading-spinner loading-xs"
                        v-if="addingCount === 1000"
                      />
                      添加 1000 条
                    </button>
                  </li>
                  <li>
                    <button
                      :disabled="addingCount === 10000"
                      @click="addManyTodo(10000)"
                      data-testid="todo-batch-option-10000"
                    >
                      <span
                        class="loading loading-spinner loading-xs"
                        v-if="addingCount === 10000"
                      />
                      添加 10000 条
                    </button>
                  </li>
                </ul>
              </div>
            </div>

            <div class="flex items-center gap-2">
              <!-- Undo/Redo -->
              <div class="join">
                <button
                  class="btn btn-sm join-item"
                  :disabled="undoCount === 0"
                  @click="undo"
                  aria-label="Undo"
                  data-testid="todo-undo"
                >
                  <Undo2 :size="16" />
                  <span
                    class="badge badge-xs"
                    v-if="undoCount > 0"
                  >
                    {{ undoCount }}
                  </span>
                </button>
                <button
                  class="btn btn-sm join-item"
                  :disabled="redoCount === 0"
                  @click="redo"
                  aria-label="Redo"
                  data-testid="todo-redo"
                >
                  <Redo2 :size="16" />
                  <span
                    class="badge badge-xs"
                    v-if="redoCount > 0"
                  >
                    {{ redoCount }}
                  </span>
                </button>
              </div>

              <!-- History Toggle -->
              <button
                :class="['btn btn-sm', { 'btn-primary': showHistory }]"
                @click="toggleHistory"
                aria-label="历史记录"
                data-testid="todo-history"
              >
                <History :size="16" />
              </button>
            </div>
          </div>

          <!-- Tabs and Action Buttons -->
          <div class="flex flex-wrap items-center justify-between gap-2">
            <div
              class="tabs tabs-boxed tabs-sm"
              role="tablist"
            >
              <button
                :class="['tab', { 'tab-active': currentTab === 'all' }]"
                @click="currentTab = 'all'"
                data-testid="todo-tab-all"
                role="tab"
              >
                全部
              </button>
              <button
                :class="['tab', { 'tab-active': currentTab === 'active' }]"
                @click="currentTab = 'active'"
                data-testid="todo-tab-active"
                role="tab"
              >
                进行中
              </button>
              <button
                :class="['tab', { 'tab-active': currentTab === 'completed' }]"
                @click="currentTab = 'completed'"
                data-testid="todo-tab-completed"
                role="tab"
              >
                已完成
              </button>
            </div>

            <div class="flex flex-wrap items-center gap-2">
              <button
                class="btn btn-sm"
                :disabled="disabledToggleAllBtn"
                @click="toggleAllTodos"
                aria-label="全选/取消全选"
                data-testid="todo-toggle-all"
              >
                全选
              </button>
              <button
                class="btn btn-sm"
                :disabled="disabledClearCompletedBtn"
                @click="clearCompleted"
                aria-label="清除已完成"
                data-testid="todo-clear-completed"
              >
                清除已完成
              </button>
              <button
                class="btn btn-sm"
                @click="toggleCompletedSort"
                aria-label="排序"
                data-testid="todo-sort"
              >
                <ArrowUp
                  v-if="completedSort === 'asc'"
                  :size="16"
                />
                <ArrowDown
                  v-else
                  :size="16"
                />
                排序
              </button>
            </div>
          </div>

          <!-- Add Todo Input -->
          <div class="flex w-full gap-2">
            <input
              class="input input-bordered input-sm flex-1"
              v-model="inputValue"
              @keyup.enter="addTodo"
              aria-label="添加新任务"
              data-testid="todo-title-input"
              placeholder="添加新任务..."
              type="text"
            />
            <button
              class="btn btn-primary btn-sm"
              :disabled="!inputValue"
              @click="addTodo"
              aria-label="添加"
              data-testid="todo-add"
            >
              <Plus :size="16" />
              添加
            </button>
          </div>
        </div>
      </div>

      <div
        class="alert alert-error mx-auto my-2 max-w-4xl"
        v-if="reorderError"
        data-testid="todo-reorder-error"
        role="alert"
      >
        <span>排序保存失败：{{ reorderError }}</span>
      </div>

      <!-- Todo List -->
      <div class="mx-auto min-h-60 max-w-4xl">
        <div
          class="hero min-h-60"
          v-if="todoResource.isLoading"
        >
          <div class="hero-content text-center">
            <span class="loading loading-spinner loading-md" />
          </div>
        </div>
        <div
          class="hero min-h-60"
          v-else-if="todoResource.isEmpty"
        >
          <div class="hero-content text-center">
            <div>
              <p class="text-base-content/60">暂无任务</p>
              <p class="text-base-content/40 text-sm">添加一个新任务开始吧</p>
            </div>
          </div>
        </div>
        <div
          v-else
          :class="{ 'cursor-progress': reorderPending }"
          :style="{ height: `${virtualizer.getTotalSize()}px`, position: 'relative' }"
          ref="todoListRef"
        >
          <ul class="divide-base-200 divide-y">
            <!-- P1-1（React 同源缺陷的 Vue 端）：key 必须是**身份**。
                 原先是 `getEntityStatus(todo).fingerprint`（= `id@updatedAt`），
                 每次写入都换 key，Vue 会销毁重建整行，行内编辑的 input 连焦点一起没。
                 同一应用的 TodoCursorPage 用的就是 `.id`。 -->
            <li
              class="group border-base-200 hover:bg-base-200/50 flex items-center border-b px-4 py-2 transition-colors"
              v-for="{ item: todo, virtualItem } in virtualRows"
              :class="{ 'opacity-50': drag?.fromIndex === virtualItem.index }"
              :data-drop-target="drag?.overIndex === virtualItem.index ? '' : undefined"
              :key="todo.id"
              :style="{
                boxShadow: dropShadow(virtualItem.index),
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: `${ITEM_SIZE}px`,
                transform: `translateY(${virtualItem.start}px)`
              }"
              data-testid="todo-row"
            >
              <div class="flex w-full flex-1 items-center gap-3">
                <template v-if="editingTodoIds.has(todo.id)">
                  <input
                    class="todo-input input input-bordered input-sm flex-1"
                    :ref="el => setEditInputRef(todo.id, el)"
                    :value="editValues.get(todo.id) ?? todo.title"
                    @blur="cancelEditing(todo)"
                    @input="e => editValues.set(todo.id, (e.target as HTMLInputElement).value)"
                    @keyup.enter="
                      e => {
                        const input = editInputRefs.get(todo.id);
                        if (input) saveTodo(e, input, todo);
                      }
                    "
                    @keyup.escape="cancelEditing(todo)"
                    data-testid="todo-edit-input"
                    placeholder="任务名称..."
                    type="text"
                  />
                  <button
                    class="btn btn-sm"
                    @click="
                      e => {
                        const input = editInputRefs.get(todo.id);
                        if (input) saveTodo(e, input, todo);
                      }
                    "
                    @mousedown.prevent
                    aria-label="保存"
                    data-testid="todo-save"
                  >
                    保存
                  </button>
                </template>
                <template v-else>
                  <button
                    class="btn btn-ghost btn-xs cursor-grab touch-none"
                    v-if="currentTab !== 'all'"
                    :disabled="!canDrag"
                    @pointerdown="e => startDrag(e, virtualItem.index)"
                    aria-label="拖动排序"
                    data-testid="todo-drag-handle"
                    type="button"
                  >
                    <GripVertical :size="14" />
                  </button>
                  <input
                    class="checkbox"
                    :checked="todo.completed"
                    @change="e => toggleTodoCompletion(e, todo)"
                    data-testid="todo-completed"
                    type="checkbox"
                  />
                  <div
                    :class="[
                      'flex-1 cursor-pointer truncate select-none',
                      {
                        'line-through': todo.completed,
                        'opacity-50': todo.completed
                      }
                    ]"
                    @dblclick="e => startEditing(e, todo)"
                    data-testid="todo-title"
                  >
                    {{ todo.title }}
                  </div>
                  <div class="flex gap-1 opacity-0 transition-opacity group-hover:opacity-100">
                    <button
                      class="btn btn-ghost btn-xs"
                      @click="e => startEditing(e, todo)"
                      aria-label="编辑"
                      data-testid="todo-edit"
                    >
                      <Pen :size="14" />
                    </button>
                    <button
                      class="btn btn-ghost btn-xs text-error"
                      @click="e => removeTodo(e, todo)"
                      aria-label="删除"
                      data-testid="todo-delete"
                    >
                      <X :size="14" />
                    </button>
                  </div>
                </template>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </main>
  </div>
</template>

// modules/angular-todo/todo-page/todo.page.ts
import { getEntityStatus, reorderTargetForMove, RxDB, type UUID } from '@aiao/rxdb';
// 本页的撤销/重做读 `rxdb.versionManager`，而历史子系统自 US-025 阶段 C 起住在这个插件里。
// 本模块**不**装插件 —— 它拿的是宿主注入的 `RxDB`，装插件是宿主 `setup_rxdb_*.ts` 的活；
// 这里只借 `declare module '@aiao/rxdb'` 的类型声明，`import type` 在 emit 时整句擦除。
import { useAction, useFindAll } from '@aiao/rxdb-angular';
import type {} from '@aiao/rxdb-plugin-history';
import { Task, TaskStaticTypes } from '@aiao/rxdb-test/entities';
import { FixedRowDrag, type FixedRowDragState, type FixedRowDrop, nextMacroTask } from '@aiao/utils';
import { ScrollDispatcher, ScrollingModule } from '@angular/cdk/scrolling';
import { AsyncPipe, isPlatformBrowser } from '@angular/common';
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  computed,
  DestroyRef,
  ElementRef,
  inject,
  OnInit,
  PLATFORM_ID,
  signal,
  viewChild,
  WritableSignal
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import {
  LucideArrowDown as ArrowDown,
  LucideArrowUp as ArrowUp,
  LucideGripVertical as GripVertical,
  LucideHistory as History,
  LucideDynamicIcon,
  LucidePen as Pen,
  LucidePlus as Plus,
  LucideRedo2 as Redo2,
  LucideUndo2 as Undo2,
  LucideX as X
} from '@lucide/angular';
import { HistorySidebarComponent } from '@modules/angular';

/** 行高（px）：虚拟滚动的 itemSize 与拖拽落点换算共用 */
const ITEM_SIZE = 48;

@Component({
  selector: 'ao-todo-page',
  imports: [AsyncPipe, FormsModule, LucideDynamicIcon, ScrollingModule, HistorySidebarComponent],
  standalone: true,
  templateUrl: './todo.page.html',
  styleUrls: ['./todo.page.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TodoPage implements OnInit, AfterViewInit {
  #todo_state_map = new Map<Task, WritableSignal<{ isEditing: boolean }>>();
  #destroyRef = inject(DestroyRef);
  #rxdb = inject(RxDB);
  #scrollDispatcher = inject(ScrollDispatcher);
  #loading = false;
  #hasMore = true;
  // 会话绑定起拖时的 id 序列：活查询插入 / 删除、切 tab、重排让列表变了就取消，不把旧下标套到新列表上
  readonly #drag = new FixedRowDrag<UUID>({
    rowHeight: ITEM_SIZE,
    scrollElement: () => this.#required(this.mainContainerRef(), 'mainContainer'),
    listElement: () => this.#required(this.todoListRef(), 'todoList'),
    ids: () => this.todo_resource.value().map(todo => todo.id),
    onChange: state => this.$drag.set(state),
    onDrop: drop => void this.drop_todo(drop)
  });

  readonly itemSize = ITEM_SIZE;
  readonly history = this.#rxdb.versionManager.history(Task);

  // 图标
  readonly Undo2 = Undo2;
  readonly Redo2 = Redo2;
  readonly Pen = Pen;
  readonly X = X;
  readonly Plus = Plus;
  readonly ArrowUp = ArrowUp;
  readonly ArrowDown = ArrowDown;
  readonly History = History;
  readonly GripVertical = GripVertical;

  readonly title = signal<string>('');
  readonly $current_tab = signal<string>('all');
  readonly $completed_sort = signal<'asc' | 'desc'>('asc');
  readonly $init_date = signal(new Date()).asReadonly();
  readonly $next_new_data = signal(new Date());
  readonly $show_history = signal(true);
  readonly $show_sticky_header = signal(false);
  /** 拖拽中的起点与落点；`null` 表示没在拖 */
  readonly $drag = signal<FixedRowDragState | null>(null);
  /** 一次重排正在落库；期间不允许开始新的拖拽 */
  readonly $reorder_pending = signal(false);
  /** 最近一次重排失败的原因；下一次重排开始时清掉 */
  readonly $reorder_error = signal<string | null>(null);

  // 查询条件
  readonly $todo_query_options = computed<TaskStaticTypes['findAllOptions']>(() => {
    const current_tab = this.$current_tab();
    const options: TaskStaticTypes['findAllOptions'] = {
      where: {
        combinator: 'and',
        rules: []
      },
      orderBy: [
        {
          field: 'completed',
          sort: this.$completed_sort()
        },
        // 组内手动顺序；id 只在 sortOrder 相同时定序，保证结果稳定
        {
          field: 'sortOrder',
          sort: 'asc'
        },
        {
          field: 'id',
          sort: 'asc'
        }
      ]
    };
    if (current_tab === 'active') {
      options.where.rules.push({
        field: 'completed',
        operator: '=',
        value: false
      });
    } else if (current_tab === 'completed') {
      options.where.rules.push({
        field: 'completed',
        operator: '=',
        value: true
      });
    }
    return options;
  });

  // Resource
  readonly todo_resource = useFindAll(Task, this.$todo_query_options);

  readonly $todo_count_left = computed(() => this.todo_resource.value().filter(d => d.completed === false).length);
  readonly $completed_todos = computed(() => this.todo_resource.value().filter(d => d.completed));
  readonly $is_all_completed = computed(() => this.todo_resource.value().every(d => d.completed));
  readonly $disabled_clear_completed_btn = computed(() => !this.$completed_todos().length);
  readonly $disabled_toggle_all_btn = computed(() => this.todo_resource.value().length === 0);
  /**
   * 是否允许拖拽排序。「全部」页混着两个分组且受排序方向影响，拖动语义不清，不提供手柄；
   * 加载中的列表下标与库里顺序可能对不上，待决重排期间再拖会基于过期邻居计算目标。
   */
  readonly $can_drag = computed(
    () =>
      this.$current_tab() !== 'all' &&
      !this.todo_resource.isLoading() &&
      !this.$reorder_pending() &&
      this.todo_resource.value().length >= 2
  );

  readonly isBrowser = isPlatformBrowser(inject(PLATFORM_ID));
  readonly add_1 = useAction<number>(options => this.add_many_todo(options));
  readonly add_2 = useAction<number>(options => this.add_many_todo(options));
  readonly add_3 = useAction<number>(options => this.add_many_todo(options));
  readonly add_4 = useAction<number>(options => this.add_many_todo(options));
  readonly add_5 = useAction<number>(options => this.add_many_todo(options));

  fullHeaderRef = viewChild<ElementRef<HTMLElement>>('fullHeader');
  mainContainerRef = viewChild<ElementRef<HTMLElement>>('mainContainer');
  todoListRef = viewChild('todoList', { read: ElementRef<HTMLElement> });

  constructor() {
    this.#destroyRef.onDestroy(() => this.#drag.dispose());
  }

  trackByFn = (index: number, todo: Task) => getEntityStatus(todo).fingerprint;

  ngOnInit() {
    if (!this.isBrowser) return;
  }

  ngAfterViewInit() {
    const fullHeader = this.fullHeaderRef();
    const mainContainer = this.mainContainerRef();

    if (!this.isBrowser || !fullHeader || !mainContainer) return;

    const checkVisibility = () => {
      const headerElement = fullHeader.nativeElement;
      const mainElement = mainContainer.nativeElement;

      const scrollTop = mainElement.scrollTop;
      const headerOffsetTop = headerElement.offsetTop;
      const headerHeight = headerElement.offsetHeight;

      const shouldShow = scrollTop > headerOffsetTop + headerHeight;
      this.$show_sticky_header.set(shouldShow);
    };

    this.#scrollDispatcher
      .scrolled()
      .pipe(takeUntilDestroyed(this.#destroyRef))
      .subscribe(() => checkVisibility());

    checkVisibility();
  }

  /** 按下拖拽手柄：从第 `index` 行开始拖 */
  start_drag(event: PointerEvent, index: number) {
    if (!this.$can_drag()) return;
    this.#drag.start(event, index);
  }

  /**
   * 把被拖行放到落点：对着起拖时的 id 序列换算成邻居目标后交给 `Repository.reorder()`
   *
   * 换算也在错误处理之内：失败显示在页面上，返回的 Promise 不拒绝。
   */
  async drop_todo({ id, ids, fromIndex, toIndex }: FixedRowDrop<UUID>) {
    this.$reorder_pending.set(true);
    this.$reorder_error.set(null);
    try {
      const target = reorderTargetForMove(ids, fromIndex, toIndex);
      if (target) await this.#rxdb.entityManager.getRepository(Task).reorder(id, target);
    } catch (error) {
      this.$reorder_error.set(error instanceof Error ? error.message : String(error));
    } finally {
      this.$reorder_pending.set(false);
    }
  }

  load_more() {
    if (this.#loading || !this.#hasMore) return;
    this.#loading = true;
  }

  todo_edit(event: Event, liEle: HTMLDivElement, todo: Task) {
    event.preventDefault();
    event.stopImmediatePropagation();
    this.get_todo_state_signal(todo).update(state => ({ ...state, isEditing: true }));
    nextMacroTask(() => {
      const input = liEle.querySelector<HTMLInputElement>('input.todo-input');
      input?.focus();
    });
  }

  async todo_save(event: Event, input: HTMLInputElement, todo: Task) {
    event.preventDefault();
    event.stopImmediatePropagation();
    const stateSignal = this.get_todo_state_signal(todo);
    if (stateSignal().isEditing === false) return;
    await todo.save();
    stateSignal.update(state => ({ ...state, isEditing: false }));
    input.blur();
  }

  todo_cancel_edit(todo: Task) {
    const state = this.get_todo_state_signal(todo);
    if (state().isEditing === false) return;
    state.update(state => ({ ...state, isEditing: false }));
    todo.reset();
  }

  get_todo_state_signal(todo: Task) {
    if (this.#todo_state_map.has(todo) === false) this.#todo_state_map.set(todo, signal({ isEditing: false }));
    return this.#todo_state_map.get(todo)!;
  }

  async todo_remove(event: Event, todo: Task) {
    event.preventDefault();
    event.stopImmediatePropagation();
    await todo.remove();
  }

  async clear_completed() {
    console.time('removeMany');
    const completed_todos = this.$completed_todos();
    await this.#rxdb.entityManager.removeMany(completed_todos);
    console.timeEnd('removeMany');
  }

  async toggle_all() {
    const all_completed = this.$is_all_completed();
    const toggle = !all_completed;
    const todos = this.todo_resource.value().filter(d => d.completed === all_completed);
    for (const todo of todos) {
      todo.completed = toggle;
    }
    console.time('saveMany');
    await this.#rxdb.entityManager.saveMany(todos);
    console.timeEnd('saveMany');
  }

  toggle_complete_sort() {
    this.$completed_sort.update(sort => (sort === 'asc' ? 'desc' : 'asc'));
  }

  toggle_history() {
    this.$show_history.update(show => !show);
  }

  set_current_tab(tab: string) {
    this.$current_tab.set(tab);
  }

  sticky_tab_click(tab: string) {
    const mainContainer = this.mainContainerRef();
    if (!mainContainer) return;

    const element = mainContainer.nativeElement;

    // 监听滚动结束
    let scrollTimeout: number;
    const onScrollEnd = () => {
      clearTimeout(scrollTimeout);
      scrollTimeout = window.setTimeout(() => {
        // 滚动结束后切换 tab
        this.set_current_tab(tab);
        element.removeEventListener('scroll', onScrollEnd);
      }, 50);
    };

    element.addEventListener('scroll', onScrollEnd);
    element.scrollTo({ top: 0, behavior: 'smooth' });

    // 防止监听器泄漏：5秒后强制清理
    setTimeout(() => {
      element.removeEventListener('scroll', onScrollEnd);
      clearTimeout(scrollTimeout);
    }, 5000);
  }

  async add_todo(event: Event) {
    event.preventDefault();
    const titleValue = this.title();
    if (titleValue) {
      const todo = new Task({
        title: titleValue
      });
      await todo.save();
      this.title.set('');
    }
  }

  async toggle_todo_completed(event: Event, todo: Task) {
    const state = this.get_todo_state_signal(todo)();
    if (state.isEditing) return;
    event.preventDefault();
    todo.completed = (event.target as HTMLInputElement).checked;
    await todo.save();
  }

  async add_many_todo(total: number) {
    const todos: Task[] = [];
    for (let i = 0; i < total; i++) {
      const todo = new Task();
      todo.title = 'test' + '-' + i;
      todos.push(todo);
    }
    console.time('saveMany');
    await this.#rxdb.entityManager.saveMany(todos);
    console.timeEnd('saveMany');
  }

  undo() {
    void this.#rxdb.versionManager.history().undo();
  }

  redo() {
    void this.#rxdb.versionManager.history().redo();
  }

  #required(ref: ElementRef<HTMLElement> | undefined, name: string): HTMLElement {
    if (!ref) throw new Error(`拖拽需要的元素 #${name} 尚未渲染`);
    return ref.nativeElement;
  }
}
