// packages/rxdb-model-react/src/query-builder/popover-select/popover-select.tsx
/**
 * @fileoverview 基于 Popover API 的下拉选择组件（Angular `PopoverSelectComponent` 的 React 移植）。
 *
 * 语义与 Angular 侧一致：使用浏览器原生 Popover API 渲染选项列表（top layer 渲染，
 * 不受 `overflow` 容器裁剪），支持关键字过滤、键盘导航（↑↓ 移动、Enter 选中、
 * Escape 关闭并聚焦触发按钮、Tab 关闭）。打开弹框自动高亮第一项，搜索后也自动高亮第一条结果。
 *
 * @module query-builder/popover-select
 */
import { applyPopoverPosition, cn, findOptionLabel } from '@aiao/rxdb-model';
import { useMemo, useRef, useState, type JSX } from 'react';

let uidCounter = 0;

/** {@link PopoverSelect} 的选项。 */
export interface PopoverSelectOption {
  /** 选项值。 */
  value: string;
  /** 显示文本。 */
  label: string;
}

/** {@link PopoverSelect} 的 props。 */
export interface PopoverSelectProps {
  /** 可选项列表。 */
  options: ReadonlyArray<PopoverSelectOption>;
  /** 当前选中值。 */
  selected?: string;
  /** 占位文案（未选中或选中值不在选项中时显示），缺省 `'请选择'`。 */
  placeholder?: string;
  /** 触发器与弹层最小宽度，缺省 `'8rem'`。 */
  minWidth?: string;
  /** 选中回调。 */
  onSelectChange?: (value: string) => void;
}

/**
 * 基于 Popover API 的下拉选择组件。
 */
export function PopoverSelect({
  options,
  selected = '',
  placeholder = '请选择',
  minWidth = '8rem',
  onSelectChange
}: PopoverSelectProps): JSX.Element {
  const [uid] = useState(() => `rxdb-ps-${++uidCounter}`);
  const listId = `${uid}-list`;

  const triggerRef = useRef<HTMLButtonElement>(null);
  const popoverRef = useRef<HTMLDivElement>(null);
  const filterInputRef = useRef<HTMLInputElement>(null);

  const [filterText, setFilterText] = useState('');
  const [activeIndex, setActiveIndex] = useState(0);

  const currentLabel = findOptionLabel(options, selected, placeholder);

  const filteredOptions = useMemo(() => {
    const filter = filterText.toLowerCase().trim();
    if (!filter) return options;
    return options.filter(option => option.label.toLowerCase().includes(filter));
  }, [options, filterText]);

  // 过滤词变化后高亮自动回到第一项（Angular 侧 effect 同语义；渲染期调整状态）
  const [prevFiltered, setPrevFiltered] = useState(filteredOptions);
  if (prevFiltered !== filteredOptions) {
    setPrevFiltered(filteredOptions);
    setActiveIndex(0);
  }

  const activeItemId =
    activeIndex >= 0 && activeIndex < filteredOptions.length ?
      `${uid}-opt-${filteredOptions[activeIndex].value}`
    : null;

  /** beforetoggle open：清空过滤词并应用弹层定位（Angular 侧同语义）。 */
  const onBeforeToggle = (event: React.ToggleEvent<HTMLDivElement>): void => {
    if (event.nativeEvent.newState === 'open') {
      applyPopoverPosition(popoverRef.current as HTMLDivElement, triggerRef.current!.getBoundingClientRect());
      setFilterText('');
    }
  };

  /** toggle open：聚焦搜索框并重置高亮索引。 */
  const onToggle = (event: React.ToggleEvent<HTMLDivElement>): void => {
    if (event.nativeEvent.newState === 'open') {
      filterInputRef.current?.focus();
      setActiveIndex(0);
    }
  };

  /** 选中：回调 + 关闭弹层 + 聚焦触发按钮。 */
  const onSelect = (value: string): void => {
    onSelectChange?.(value);
    popoverRef.current?.hidePopover();
    triggerRef.current?.focus();
  };

  const scrollActiveIntoView = (index: number): void => {
    const option = filteredOptions[index];
    if (!option) return;
    document.getElementById(`${uid}-opt-${option.value}`)?.scrollIntoView({ block: 'nearest' });
  };

  /** 键盘导航（↑↓ 循环移动、Enter 选中、Escape 关闭并聚焦触发按钮、Tab 关闭）。 */
  const onKeydown = (event: React.KeyboardEvent): void => {
    const len = filteredOptions.length;
    switch (event.key) {
      case 'ArrowDown': {
        event.preventDefault();
        if (len > 0) {
          const next = (activeIndex + 1) % len;
          setActiveIndex(next);
          scrollActiveIntoView(next);
        }
        break;
      }
      case 'ArrowUp': {
        event.preventDefault();
        if (len > 0) {
          const next = (activeIndex - 1 + len) % len;
          setActiveIndex(next);
          scrollActiveIntoView(next);
        }
        break;
      }
      case 'Enter': {
        event.preventDefault();
        const option = filteredOptions[activeIndex];
        if (option) onSelect(option.value);
        break;
      }
      case 'Escape': {
        event.preventDefault();
        popoverRef.current?.hidePopover();
        triggerRef.current?.focus();
        break;
      }
      case 'Tab': {
        popoverRef.current?.hidePopover();
        break;
      }
    }
  };

  return (
    <>
      <button
        ref={triggerRef}
        className='select select-sm text-left'
        popoverTarget={uid}
        style={{ minWidth }}
        type='button'
      >
        {currentLabel}
      </button>
      <div
        ref={popoverRef}
        id={uid}
        className='bg-base-100 rounded-box border-base-300 border shadow-xl'
        style={{ minWidth }}
        onBeforeToggle={onBeforeToggle}
        onToggle={onToggle}
        onKeyDown={onKeydown}
        popover=''
        tabIndex={-1}
      >
        <div className='mb-1 p-2'>
          <input
            ref={filterInputRef}
            className='input input-sm w-full'
            aria-activedescendant={activeItemId ?? undefined}
            aria-controls={listId}
            aria-expanded='true'
            aria-autocomplete='list'
            placeholder='搜索...'
            role='combobox'
            type='text'
            value={filterText}
            onChange={event => setFilterText(event.target.value)}
          />
        </div>
        <ul className='menu menu-sm max-h-60 w-full flex-nowrap overflow-y-auto px-2' id={listId} role='listbox'>
          {filteredOptions.map((option, index) => (
            <li role='none' key={option.value}>
              <button
                className={cn(
                  'flex w-full items-center text-left text-sm',
                  option.value === selected && 'bg-primary/15 font-semibold',
                  index === activeIndex && 'menu-focus'
                )}
                aria-selected={option.value === selected}
                id={`${uid}-opt-${option.value}`}
                role='option'
                type='button'
                onClick={() => onSelect(option.value)}
              >
                <span className='grow'>{option.label}</span>
                {option.value === selected && (
                  <svg
                    className='text-primary h-3 w-3 shrink-0'
                    fill='none'
                    stroke='currentColor'
                    strokeLinecap='round'
                    strokeLinejoin='round'
                    strokeWidth='2.5'
                    viewBox='0 0 24 24'
                  >
                    <polyline points='20 6 9 17 4 12' />
                  </svg>
                )}
              </button>
            </li>
          ))}
          {filteredOptions.length === 0 && <li className='px-3 py-1.5 text-sm opacity-50'>无匹配项</li>}
        </ul>
      </div>
    </>
  );
}

// packages/rxdb-model-vue/src/query-builder/popover-select/PopoverSelect.vue
<script lang="ts" setup>
/**
 * 基于 Popover API 的下拉选择组件（对齐 Angular 侧 `PopoverSelectComponent`）。
 *
 * 使用浏览器原生 Popover API 渲染选项列表（top layer，`overflow` 容器内不被裁剪）；
 * 支持关键字过滤、键盘导航（↑↓ 循环移动、Enter 选中、Escape 关闭）、
 * 打开自动高亮第一项，搜索后也自动高亮第一条结果。
 */
import { applyPopoverPosition, findOptionLabel } from '@aiao/rxdb-model';
import { computed, ref, watch } from 'vue';

let moduleUid = 0;

const props = withDefaults(
  defineProps<{
    /** 选项列表 */
    options: ReadonlyArray<{ value: string; label: string }>;
    /** 当前选中值 */
    selected?: string;
    /** 未选中时的占位文案 */
    placeholder?: string;
    /** 最小宽度 */
    minWidth?: string;
  }>(),
  { selected: '', placeholder: '请选择', minWidth: '8rem' }
);

const emit = defineEmits<{
  /** 选中某个选项 */
  selectChange: [value: string];
}>();

const uid = `rxdb-ps-${++moduleUid}`;
const listId = `${uid}-list`;
const filterText = ref('');
const activeIndex = ref(0);

const trigger = ref<HTMLButtonElement | null>(null);
const popoverEl = ref<HTMLElement | null>(null);
const filterInput = ref<HTMLInputElement | null>(null);

const currentLabel = computed(() => findOptionLabel(props.options, props.selected, props.placeholder));

const filteredOptions = computed(() => {
  const filter = filterText.value.toLowerCase().trim();
  if (!filter) return props.options;
  return props.options.filter(opt => opt.label.toLowerCase().includes(filter));
});

const activeItemId = computed(() => {
  const idx = activeIndex.value;
  const opts = filteredOptions.value;
  return idx >= 0 && idx < opts.length ? `${uid}-opt-${opts[idx].value}` : null;
});

// 过滤结果变化时高亮自动回到第一项
watch(filteredOptions, () => {
  activeIndex.value = 0;
});

const onBeforeToggle = (event: Event): void => {
  const te = event as ToggleEvent;
  if (te.newState === 'open') {
    if (popoverEl.value && trigger.value) {
      applyPopoverPosition(popoverEl.value, trigger.value.getBoundingClientRect());
    }
    filterText.value = '';
  }
};

const onToggle = (event: Event): void => {
  if ((event as ToggleEvent).newState === 'open') {
    filterInput.value?.focus();
    activeIndex.value = 0;
  }
};

const onKeydown = (event: KeyboardEvent): void => {
  const opts = filteredOptions.value;
  const len = opts.length;

  switch (event.key) {
    case 'ArrowDown': {
      event.preventDefault();
      if (len > 0) {
        activeIndex.value = (activeIndex.value + 1) % len;
        scrollActiveIntoView();
      }
      break;
    }
    case 'ArrowUp': {
      event.preventDefault();
      if (len > 0) {
        activeIndex.value = (activeIndex.value - 1 + len) % len;
        scrollActiveIntoView();
      }
      break;
    }
    case 'Enter': {
      event.preventDefault();
      const opt = opts[activeIndex.value];
      if (opt) onSelect(opt.value);
      break;
    }
    case 'Escape': {
      event.preventDefault();
      popoverEl.value?.hidePopover();
      trigger.value?.focus();
      break;
    }
    case 'Tab': {
      popoverEl.value?.hidePopover();
      break;
    }
  }
};

const onSelect = (value: string): void => {
  emit('selectChange', value);
  popoverEl.value?.hidePopover();
  trigger.value?.focus();
};

const scrollActiveIntoView = (): void => {
  const opts = filteredOptions.value;
  const opt = opts[activeIndex.value];
  if (!opt) return;
  document.getElementById(`${uid}-opt-${opt.value}`)?.scrollIntoView({ block: 'nearest' });
};

defineExpose({
  uid,
  listId,
  currentLabel,
  filteredOptions,
  activeItemId,
  filterText,
  activeIndex,
  onBeforeToggle,
  onToggle,
  onKeydown,
  onSelect
});
</script>

<template>
  <button
    ref="trigger"
    class="select select-sm text-left"
    :popovertarget="uid"
    :style="{ 'min-width': minWidth }"
    type="button"
  >
    {{ currentLabel }}
  </button>
  <div
    :id="uid"
    ref="popoverEl"
    class="bg-base-100 rounded-box border-base-300 border shadow-xl"
    :style="{ 'min-width': minWidth }"
    popover
    tabindex="-1"
    @beforetoggle="onBeforeToggle"
    @keydown="onKeydown"
    @toggle="onToggle"
  >
    <div class="mb-1 p-2">
      <input
        ref="filterInput"
        v-model="filterText"
        class="input input-sm w-full"
        :aria-activedescendant="activeItemId ?? undefined"
        :aria-controls="listId"
        aria-autocomplete="list"
        aria-expanded="true"
        placeholder="搜索..."
        role="combobox"
        type="text"
      />
    </div>
    <ul
      :id="listId"
      class="menu menu-sm max-h-60 w-full flex-nowrap overflow-y-auto px-2"
      role="listbox"
    >
      <li
        v-for="(option, i) in filteredOptions"
        :key="option.value"
        role="none"
      >
        <button
          :id="`${uid}-opt-${option.value}`"
          class="flex w-full items-center text-left text-sm"
          :aria-selected="option.value === selected"
          :class="{
            'bg-primary/15': option.value === selected,
            'font-semibold': option.value === selected,
            'menu-focus': activeIndex === i
          }"
          role="option"
          type="button"
          @click="onSelect(option.value)"
        >
          <span class="grow">{{ option.label }}</span>
          <svg
            v-if="option.value === selected"
            class="text-primary h-3 w-3 shrink-0"
            fill="none"
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2.5"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <polyline points="20 6 9 17 4 12" />
          </svg>
        </button>
      </li>
      <li
        v-if="filteredOptions.length === 0"
        class="px-3 py-1.5 text-sm opacity-50"
      >
        无匹配项
      </li>
    </ul>
  </div>
</template>
