// apps/dev-rxdb-angular/src/app/pages/storage/storage.page.ts
import { RxDB } from '@aiao/rxdb';
import { normalizeDirectoryPath } from '@aiao/rxdb-plugin-storage';
import { checkOPFSAvailable, formatFileSize, STORAGE_LABELS, STORAGE_TESTID } from '@aiao/utils';
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  OnDestroy,
  OnInit,
  signal,
  untracked,
  viewChild
} from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { ActivatedRoute, Router } from '@angular/router';
import {
  LucideAlertTriangle as AlertTriangle,
  LucideChevronRight as ChevronRight,
  LucideDatabase as Database,
  LucideDownload as Download,
  LucideEdit3 as Edit3,
  LucideEye as Eye,
  LucideFolder as Folder,
  LucideFolderOpen as FolderOpen,
  LucideFolderPlus as FolderPlus,
  LucideGrid3x3 as Grid3x3,
  LucideHome as Home,
  LucideList as List,
  LucideDynamicIcon,
  LucideRefreshCw as RefreshCw,
  LucideTrash2 as Trash2,
  LucideUpload as Upload,
  LucideX as X
} from '@lucide/angular';
import { map } from 'rxjs';
import { traverseFileTree } from '../../shared/traverse-file-tree';
import { StorageFileGridComponent } from './components/storage-file-grid.component';
import { StorageFileListComponent } from './components/storage-file-list.component';
import { StorageFilePreviewComponent } from './components/storage-file-preview.component';
import { StoragePageBrowser } from './storage-page.browser';
import {
  buildUrlFromPath,
  getBatchArchiveName,
  getStoredViewMode,
  normalizeRoutePath,
  pathSegmentsFrom,
  VIEW_MODE_STORAGE_KEY,
  type ViewMode
} from './storage-page.helpers';
import { nextSelectedPaths } from './storage-page.selection';
import { StoragePageTransfer } from './storage-page.transfer';
import { StorageBrowserItem } from './utils/storage-utils';

interface ConfirmDialog {
  show: boolean;
  message: string;
  resolve?: (value: boolean) => void;
}

interface DeleteConfirm {
  show: boolean;
  target: DeleteTarget | null;
  resolve?: (value: boolean) => void;
}

type DeleteTarget = { type: 'single'; entry: StorageBrowserItem } | { type: 'batch'; count: number };

interface RenameDialog {
  show: boolean;
  entry: StorageBrowserItem | null;
  newName: string;
}

interface OverwriteConfirm {
  show: boolean;
  file: File | null;
  existingEntry: StorageBrowserItem | null;
  resolve?: (value: boolean) => void;
}

interface ContextMenu {
  show: boolean;
  x: number;
  y: number;
  entry: StorageBrowserItem | null;
}

interface Toast {
  show: boolean;
  message: string;
  type: 'error' | 'success' | 'info';
}

interface SelectionBox {
  active: boolean;
  startX: number;
  startY: number;
  currentX: number;
  currentY: number;
}

@Component({
  selector: 'app-storage-page',
  imports: [
    CommonModule,
    LucideDynamicIcon,
    StorageFileListComponent,
    StorageFileGridComponent,
    StorageFilePreviewComponent
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './storage.page.html'
})
export default class StoragePage implements OnInit, OnDestroy {
  private initialized = false;
  private clickAbortController?: AbortController;
  private mouseMoveListener?: (event: MouseEvent) => void;
  private mouseUpListener?: () => void;
  private toastTimer?: ReturnType<typeof setTimeout>;
  private readonly destroyRef = inject(DestroyRef);
  private readonly browser: StoragePageBrowser;
  private readonly transfer: StoragePageTransfer;

  readonly rxdb = inject(RxDB);
  readonly router = inject(Router);
  readonly route = inject(ActivatedRoute);

  readonly currentPath = signal('/');
  readonly selectedPaths = signal<Set<string>>(new Set());
  readonly lastSelectedPath = signal<string | null>(null);
  readonly allFiles: StoragePageBrowser['allFiles'];
  readonly entries: StoragePageBrowser['entries'];
  readonly loading: StoragePageBrowser['loading'];
  readonly error: StoragePageBrowser['error'];
  readonly viewMode = signal<ViewMode>(getStoredViewMode());
  readonly previewEntry = signal<StorageBrowserItem | null>(null);
  readonly newFolderName = signal('');
  readonly showNewFolder = signal(false);
  readonly isDragging = signal(false);
  readonly overwriteConfirm = signal<OverwriteConfirm>({ show: false, file: null, existingEntry: null });
  readonly contextMenu = signal<ContextMenu>({ show: false, x: 0, y: 0, entry: null });
  readonly renameDialog = signal<RenameDialog>({ show: false, entry: null, newName: '' });
  readonly deleteConfirm = signal<DeleteConfirm>({ show: false, target: null });
  readonly confirmDialog = signal<ConfirmDialog>({ show: false, message: '' });
  readonly toast = signal<Toast>({ show: false, message: '', type: 'info' });
  readonly opfsAvailable = signal(false);
  readonly selectionBox = signal<SelectionBox | null>(null);

  readonly routePath = toSignal(
    this.route.paramMap.pipe(map(params => normalizeRoutePath(params.get('storagePath')))),
    { initialValue: '/' }
  );

  readonly gridContainerRef = viewChild<ElementRef<HTMLDivElement>>('gridContainer');
  readonly Math = Math;

  readonly TESTID = STORAGE_TESTID;
  readonly LABELS = STORAGE_LABELS;
  readonly formatFileSize = formatFileSize;

  readonly Database = Database;
  readonly RefreshCw = RefreshCw;
  readonly List = List;
  readonly Grid3x3 = Grid3x3;
  readonly Upload = Upload;
  readonly FolderPlus = FolderPlus;
  readonly Download = Download;
  readonly Trash2 = Trash2;
  readonly ChevronRight = ChevronRight;
  readonly AlertTriangle = AlertTriangle;
  readonly Edit3 = Edit3;
  readonly Eye = Eye;
  readonly X = X;
  readonly Folder = Folder;
  readonly FolderOpen = FolderOpen;
  readonly Home = Home;

  fileInputRef?: HTMLInputElement;
  folderInputRef?: HTMLInputElement;

  get dirCount(): number {
    return this.entries().filter(entry => entry.kind === 'directory').length;
  }

  get fileCount(): number {
    return this.entries().filter(entry => entry.kind === 'file').length;
  }

  get pathSegments() {
    return pathSegmentsFrom(this.currentPath());
  }

  constructor() {
    this.browser = new StoragePageBrowser(this.rxdb.storage, {
      currentPath: this.currentPath,
      lastSelectedPath: this.lastSelectedPath,
      selectedPaths: this.selectedPaths,
      showToast: (message, type) => this.showToast(message, type)
    });
    this.allFiles = this.browser.allFiles;
    this.entries = this.browser.entries;
    this.loading = this.browser.loading;
    this.error = this.browser.error;
    this.transfer = new StoragePageTransfer(this.rxdb.storage, {
      currentPath: () => this.currentPath(),
      fileInputFiles: () => this.fileInputRef?.files,
      findExistingFileEntry: (fileName, directoryPath) => this.browser.findExistingFileEntry(fileName, directoryPath),
      refresh: () => this.browser.refreshCurrentDirectory(),
      resolveOverwrite: (file, existing) =>
        new Promise(resolve => {
          this.overwriteConfirm.set({ show: true, file, existingEntry: existing, resolve });
        }),
      showToast: (message, type) => this.showToast(message, type)
    });

    void checkOPFSAvailable().then(available => {
      if (!this.destroyRef.destroyed) this.opfsAvailable.set(available);
    });

    effect(() => {
      if (!this.opfsAvailable() || this.initialized) return;

      this.currentPath.set(this.routePath());
      this.initialized = true;
      void this.browser.refreshCurrentDirectory();
    });

    effect(() => {
      const routePath = this.routePath();
      if (!this.initialized || routePath === untracked(() => this.currentPath())) {
        return;
      }

      this.currentPath.set(routePath);
      this.clearSelection();
      this.closeContextMenu();
      this.previewEntry.set(null);
      void this.browser.refreshCurrentDirectory();
    });

    effect(() => {
      localStorage.setItem(VIEW_MODE_STORAGE_KEY, this.viewMode());
    });
  }

  ngOnInit(): void {
    this.clickAbortController = new AbortController();
    window.addEventListener('click', () => this.closeContextMenu(), { signal: this.clickAbortController.signal });

    this.fileInputRef = document.createElement('input');
    this.fileInputRef.type = 'file';
    this.fileInputRef.multiple = true;
    this.fileInputRef.style.display = 'none';
    this.fileInputRef.dataset['testid'] = this.TESTID.FILE_INPUT;
    document.body.appendChild(this.fileInputRef);
    this.fileInputRef.addEventListener('change', () => {
      if (this.fileInputRef?.files) {
        void this.handleUpload(Array.from(this.fileInputRef.files));
        this.fileInputRef.value = '';
      }
    });

    this.folderInputRef = document.createElement('input');
    this.folderInputRef.type = 'file';
    this.folderInputRef.setAttribute('webkitdirectory', '');
    this.folderInputRef.setAttribute('directory', '');
    this.folderInputRef.style.display = 'none';
    this.folderInputRef.dataset['testid'] = this.TESTID.FOLDER_INPUT;
    document.body.appendChild(this.folderInputRef);
    this.folderInputRef.addEventListener('change', () => {
      if (this.folderInputRef?.files) {
        void this.handleUploadFolder(Array.from(this.folderInputRef.files));
        this.folderInputRef.value = '';
      }
    });
  }

  ngOnDestroy(): void {
    this.clickAbortController?.abort();

    if (this.mouseMoveListener) {
      window.removeEventListener('mousemove', this.mouseMoveListener);
    }

    if (this.mouseUpListener) {
      window.removeEventListener('mouseup', this.mouseUpListener);
    }

    this.fileInputRef?.remove();
    this.folderInputRef?.remove();

    if (this.toastTimer) {
      clearTimeout(this.toastTimer);
    }
  }

  onNewFolderNameInput(event: Event): void {
    this.newFolderName.set((event.target as HTMLInputElement).value);
  }

  onRenameInput(event: Event): void {
    this.renameDialog.set({
      show: this.renameDialog().show,
      entry: this.renameDialog().entry,
      newName: (event.target as HTMLInputElement).value
    });
  }

  handleMouseDown(event: MouseEvent): void {
    if (this.viewMode() !== 'grid' || event.button !== 0 || event.ctrlKey || event.metaKey || event.shiftKey) {
      return;
    }

    const target = event.target as HTMLElement;
    if (target.closest('button') || target.closest('a') || target.closest('[role="button"]')) {
      return;
    }

    const container = this.gridContainerRef()?.nativeElement;
    if (!container) return;

    const rect = container.getBoundingClientRect();
    const startX = event.clientX - rect.left;
    const startY = event.clientY - rect.top;

    this.selectionBox.set({
      active: true,
      startX,
      startY,
      currentX: startX,
      currentY: startY
    });

    this.mouseMoveListener = currentEvent => this.handleMouseMove(currentEvent);
    this.mouseUpListener = () => this.handleMouseUp();
    window.addEventListener('mousemove', this.mouseMoveListener);
    window.addEventListener('mouseup', this.mouseUpListener);
  }

  async navigateTo(path: string): Promise<void> {
    await this.router.navigateByUrl(buildUrlFromPath(normalizeDirectoryPath(path)));
  }

  handleNavigate(entry: StorageBrowserItem): void {
    if (entry.kind === 'directory') {
      void this.navigateTo(entry.path);
    }
  }

  async handleDownload(entry: StorageBrowserItem): Promise<void> {
    await this.transfer.handleDownload(entry);
  }

  async handleDelete(entry: StorageBrowserItem): Promise<void> {
    const shouldDelete = await new Promise<boolean>(resolve => {
      this.deleteConfirm.set({ show: true, target: { type: 'single', entry }, resolve });
    });

    if (!shouldDelete) {
      return;
    }

    const result = await this.deleteEntry(entry);
    if (!result) {
      this.showToast(`Delete failed: ${entry.name}`, 'error');
    }
  }

  handleDeleteResponse(confirm: boolean): void {
    const current = this.deleteConfirm();
    current.resolve?.(confirm);
    this.deleteConfirm.set({ show: false, target: null });
  }

  async handleUpload(files?: File[]): Promise<void> {
    await this.transfer.handleUpload(files);
  }

  async handleUploadFolder(files: File[]): Promise<void> {
    await this.transfer.handleUploadFolder(files);
  }

  handleOverwriteResponse(confirm: boolean): void {
    const current = this.overwriteConfirm();
    current.resolve?.(confirm);
    this.overwriteConfirm.set({ show: false, file: null, existingEntry: null });
  }

  async handleCreateFolder(): Promise<void> {
    const name = this.newFolderName().trim();
    if (!name) return;

    try {
      await this.rxdb.storage.createDirectory(name, { path: this.currentPath() });
      this.showNewFolder.set(false);
      this.newFolderName.set('');
      this.showToast('Folder created successfully', 'success');
      await this.browser.refreshCurrentDirectory();
    } catch (err) {
      this.showToast(err instanceof Error ? err.message : String(err), 'error');
    }
  }

  async handleRename(): Promise<void> {
    const dialog = this.renameDialog();
    if (!dialog.entry || !dialog.newName.trim()) return;

    try {
      if (dialog.entry.kind === 'file' && dialog.entry.meta) {
        await this.rxdb.storage.rename(dialog.entry.meta.id, dialog.newName.trim());
      } else {
        await this.rxdb.storage.renameDirectory(dialog.entry.path, dialog.newName.trim());
      }

      this.renameDialog.set({ show: false, entry: null, newName: '' });
      this.showToast('Rename successful', 'success');
      await this.browser.refreshCurrentDirectory();
    } catch (err) {
      this.showToast(err instanceof Error ? err.message : String(err), 'error');
    }
  }

  async handleBatchDelete(): Promise<void> {
    const selected = this.selectedPaths();
    if (selected.size === 0) return;

    const entries = this.entries().filter(entry => selected.has(entry.path));
    const shouldDelete = await new Promise<boolean>(resolve => {
      this.deleteConfirm.set({
        show: true,
        target: { type: 'batch', count: selected.size },
        resolve
      });
    });

    if (!shouldDelete) {
      return;
    }

    let failedCount = 0;
    for (const entry of entries) {
      const result = await this.deleteEntry(entry);
      if (!result) {
        failedCount++;
      }
    }

    if (failedCount > 0) {
      this.showToast(`${failedCount} items failed to delete`, 'error');
    } else {
      this.showToast(`Deleted ${entries.length} items`, 'success');
    }

    this.clearSelection();
  }

  async handleBatchDownload(): Promise<void> {
    const selectedEntries = this.entries().filter(entry => this.selectedPaths().has(entry.path));
    await this.transfer.handleBatchDownload(selectedEntries, getBatchArchiveName(this.currentPath()));
  }

  handleEntryClick(entry: StorageBrowserItem, event: MouseEvent): void {
    const next = nextSelectedPaths(entry, {
      entries: this.entries(),
      lastSelectedPath: this.lastSelectedPath(),
      metaKey: event.ctrlKey || event.metaKey,
      selectedPaths: this.selectedPaths(),
      shiftKey: event.shiftKey
    });
    this.selectedPaths.set(next.selectedPaths);
    this.lastSelectedPath.set(next.lastSelectedPath);
  }

  handleContextMenu(event: MouseEvent, entry: StorageBrowserItem): void {
    event.preventDefault();
    this.contextMenu.set({
      show: true,
      x: event.clientX,
      y: event.clientY,
      entry
    });
  }

  closeContextMenu(): void {
    this.contextMenu.set({ show: false, x: 0, y: 0, entry: null });
  }

  async handleContextMenuAction(action: 'view' | 'download' | 'rename' | 'delete'): Promise<void> {
    const menu = this.contextMenu();
    this.closeContextMenu();

    if (!menu.entry) {
      return;
    }

    switch (action) {
      case 'view':
        if (menu.entry.kind === 'file') {
          this.previewEntry.set(menu.entry);
        } else {
          await this.navigateTo(menu.entry.path);
        }
        break;
      case 'download':
        await this.handleDownload(menu.entry);
        break;
      case 'rename':
        this.renameDialog.set({ show: true, entry: menu.entry, newName: menu.entry.name });
        break;
      case 'delete':
        await this.handleDelete(menu.entry);
        break;
    }
  }

  clearSelection(): void {
    this.selectedPaths.set(new Set());
    this.lastSelectedPath.set(null);
  }

  showToast(message: string, type: 'error' | 'success' | 'info' = 'info'): void {
    if (this.toastTimer) {
      clearTimeout(this.toastTimer);
    }

    this.toast.set({ show: true, message, type });
    this.toastTimer = setTimeout(() => {
      this.toast.set({ show: false, message: '', type: 'info' });
    }, 3000);
  }

  closeToast(): void {
    if (this.toastTimer) {
      clearTimeout(this.toastTimer);
      this.toastTimer = undefined;
    }

    this.toast.set({ show: false, message: '', type: 'info' });
  }

  async refresh(): Promise<void> {
    await this.browser.refreshCurrentDirectory();
  }

  async handleDrop(event: DragEvent): Promise<void> {
    if (!event.dataTransfer) return;

    const items = event.dataTransfer.items;
    if (items) {
      const files: File[] = [];
      const promises: Promise<void>[] = [];

      for (let index = 0; index < items.length; index++) {
        const item = items[index];
        if (item.kind === 'file') {
          const entry = item.webkitGetAsEntry?.();
          if (entry) {
            promises.push(traverseFileTree(entry, '', files));
          }
        }
      }

      await Promise.all(promises);

      if (files.length > 0) {
        const hasFolder = files.some(file => !!file.webkitRelativePath && file.webkitRelativePath.includes('/'));
        if (hasFolder) {
          await this.handleUploadFolder(files);
        } else {
          await this.handleUpload(files);
        }
      }

      return;
    }

    if (event.dataTransfer.files) {
      await this.handleUpload(Array.from(event.dataTransfer.files));
    }
  }

  async onClearAll(): Promise<void> {
    const confirmed = await this.confirm(STORAGE_LABELS.CONFIRM_CLEAR);
    if (!confirmed) {
      return;
    }

    try {
      await this.rxdb.storage.clear('/');
      this.clearSelection();
      this.previewEntry.set(null);
      this.showToast(STORAGE_LABELS.CLEAR_SUCCESS, 'success');
      await this.browser.refreshCurrentDirectory();
    } catch (err) {
      this.showToast(err instanceof Error ? err.message : String(err), 'error');
    }
  }

  resolveConfirm(value: boolean): void {
    const dialog = this.confirmDialog();
    dialog.resolve?.(value);
    this.confirmDialog.set({ show: false, message: '' });
  }

  private confirm(message: string): Promise<boolean> {
    return new Promise(resolve => {
      this.confirmDialog.set({ show: true, message, resolve });
    });
  }

  private async deleteEntry(entry: StorageBrowserItem): Promise<boolean> {
    return this.browser.deleteEntry(entry);
  }

  private handleMouseMove(event: MouseEvent): void {
    const box = this.selectionBox();
    if (!box?.active) {
      return;
    }

    const container = this.gridContainerRef()?.nativeElement;
    if (!container) {
      return;
    }

    const rect = container.getBoundingClientRect();
    const currentX = event.clientX - rect.left;
    const currentY = event.clientY - rect.top;

    this.selectionBox.set({
      ...box,
      currentX,
      currentY
    });

    const boxLeft = Math.min(box.startX, currentX) + rect.left;
    const boxTop = Math.min(box.startY, currentY) + rect.top;
    const boxRight = Math.max(box.startX, currentX) + rect.left;
    const boxBottom = Math.max(box.startY, currentY) + rect.top;

    const selected = new Set<string>();
    const items = container.querySelectorAll('[data-entry-path]');

    items.forEach(item => {
      const itemRect = item.getBoundingClientRect();
      const intersects = !(
        itemRect.right < boxLeft ||
        itemRect.left > boxRight ||
        itemRect.bottom < boxTop ||
        itemRect.top > boxBottom
      );
      if (intersects) {
        const path = item.getAttribute('data-entry-path');
        if (path) {
          selected.add(path);
        }
      }
    });

    this.selectedPaths.set(selected);
  }

  private handleMouseUp(): void {
    this.selectionBox.set(null);

    if (this.mouseMoveListener) {
      window.removeEventListener('mousemove', this.mouseMoveListener);
      this.mouseMoveListener = undefined;
    }

    if (this.mouseUpListener) {
      window.removeEventListener('mouseup', this.mouseUpListener);
      this.mouseUpListener = undefined;
    }
  }
}

// apps/dev-rxdb-vue/src/pages/StoragePage.vue
<script lang="ts" setup>
import { normalizeDirectoryPath } from '@aiao/rxdb-plugin-storage';
import { injectRxDB } from '@aiao/rxdb-vue';
import { checkOPFSAvailable, STORAGE_LABELS, STORAGE_TESTID } from '@aiao/utils';
import { Database, TriangleAlert, Upload } from '@lucide/vue';
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useStorageBrowser } from './storage/composables/useStorageBrowser';
import { useStorageInitialization } from './storage/composables/useStorageInitialization';
import { useStorageSelection } from './storage/composables/useStorageSelection';
import { traverseDataTransferTree, useStorageTransfer } from './storage/composables/useStorageTransfer';
import StorageConfirmDialog from './storage/components/StorageConfirmDialog.vue';
import StorageContextMenu from './storage/components/StorageContextMenu.vue';
import StorageDeleteDialog from './storage/components/StorageDeleteDialog.vue';
import StorageFileGrid from './storage/components/StorageFileGrid.vue';
import StorageFileList from './storage/components/StorageFileList.vue';
import StorageFilePreview from './storage/components/StorageFilePreview.vue';
import StorageNewFolderDialog from './storage/components/StorageNewFolderDialog.vue';
import StorageOverwriteDialog from './storage/components/StorageOverwriteDialog.vue';
import StorageRenameDialog from './storage/components/StorageRenameDialog.vue';
import StorageToolbar from './storage/components/StorageToolbar.vue';
import type { StorageBrowserItem } from './storage/utils/storage-utils';
import { formatErrorMessage, useToast } from '../app/composables/useToast';

type ViewMode = 'list' | 'grid';

const rxdb = injectRxDB()!;
const router = useRouter();
const route = useRoute();
const toast = useToast();
const T = STORAGE_TESTID;
const L = STORAGE_LABELS;

const viewMode = ref<ViewMode>(getStoredViewMode());
const previewEntry = ref<StorageBrowserItem | null>(null);
const isDragging = ref(false);
const fileInputRef = ref<HTMLInputElement | null>(null);
const folderInputRef = ref<HTMLInputElement | null>(null);
const gridContainerRef = ref<HTMLDivElement | null>(null);

const overwriteConfirm = ref<{
  show: boolean;
  file: File | null;
  existingEntry: StorageBrowserItem | null;
  resolve?: (value: boolean) => void;
}>({ show: false, file: null, existingEntry: null });
const contextMenu = ref<{ show: boolean; x: number; y: number; entry: StorageBrowserItem | null }>({
  show: false,
  x: 0,
  y: 0,
  entry: null
});
const renameDialog = ref<{ show: boolean; entry: StorageBrowserItem | null }>({ show: false, entry: null });
const deleteConfirm = ref<{
  show: boolean;
  entry: StorageBrowserItem | null;
  resolve?: (value: boolean) => void;
}>({ show: false, entry: null });
const confirmDialog = ref<{ show: boolean; message: string; resolve?: (value: boolean) => void }>({
  show: false,
  message: ''
});
const showNewFolder = ref(false);

const browser = useStorageBrowser(rxdb);
const initialization = useStorageInitialization({
  checkAvailability: checkOPFSAvailable,
  open: async path => {
    browser.currentPath.value = path;
    await browser.refresh(path);
  }
});
const selection = useStorageSelection(browser.entries);
const transfer = useStorageTransfer({
  rxdb,
  currentPath: () => browser.currentPath.value,
  findExistingFileEntry: browser.findExistingFileEntry,
  refresh: () => browser.refresh(browser.currentPath.value),
  uploadResolver: {
    resolve: (file, existingEntry) =>
      new Promise<boolean>(resolve => {
        overwriteConfirm.value = { show: true, file, existingEntry, resolve };
      })
  }
});

const routePath = computed(() => normalizeRoutePath(route.params.storagePath as string | string[] | undefined));
const dirCount = computed(() => browser.entries.value.filter(entry => entry.kind === 'directory').length);
const fileCount = computed(() => browser.entries.value.filter(entry => entry.kind === 'file').length);
const opfsAvailable = computed(() => initialization.isReady.value);
const storageLoading = computed(() => initialization.status.value === 'checking' || browser.loading.value);
const storageStatusMessage = computed(() => {
  if (initialization.status.value === 'unavailable') return 'OPFS is not available in this browser.';
  if (initialization.status.value === 'error') {
    return formatErrorMessage('Storage initialization failed', initialization.error.value);
  }
  return null;
});

onMounted(async () => {
  window.addEventListener('click', closeContextMenu);
  await initialization.start(routePath.value);
});

onUnmounted(() => {
  window.removeEventListener('click', closeContextMenu);
  selection.teardownDrag();
});

watch(routePath, async path => {
  if (!initialization.isReady.value || path === browser.currentPath.value) return;

  browser.currentPath.value = path;
  selection.clearSelection();
  closeContextMenu();
  previewEntry.value = null;
  await browser.refresh(path);
});

watch(
  () => browser.currentPath.value,
  path => {
    if (!initialization.isReady.value) return;
    const url = buildUrlFromPath(path);
    if (router.currentRoute.value.fullPath !== url) {
      void router.replace(url);
    }
  }
);

watch(viewMode, mode => {
  localStorage.setItem('storage-view-mode', mode);
});

function getStoredViewMode(): ViewMode {
  const stored = localStorage.getItem('storage-view-mode');
  return stored === 'grid' || stored === 'list' ? stored : 'list';
}

function normalizeRoutePath(path: string | string[] | undefined): string {
  const value = Array.isArray(path) ? path.join('/') : path;
  if (!value || value === '/') return '/';
  return normalizeDirectoryPath(value.startsWith('/') ? value : `/${value}`);
}

function buildUrlFromPath(path: string): string {
  const segments = path.split('/').filter(Boolean);
  if (segments.length === 0) return '/storage';
  return `/storage/${segments.map(segment => encodeURIComponent(segment)).join('/')}`;
}

function confirm(message: string): Promise<boolean> {
  return new Promise(resolve => {
    confirmDialog.value = { show: true, message, resolve };
  });
}

async function navigateTo(path: string): Promise<void> {
  selection.clearSelection();
  closeContextMenu();
  previewEntry.value = null;
  await browser.navigateTo(path);
}

async function handleDelete(entry: StorageBrowserItem): Promise<void> {
  const shouldDelete = await new Promise<boolean>(resolve => {
    deleteConfirm.value = { show: true, entry, resolve };
  });

  if (!shouldDelete) return;

  const result = await browser.deleteEntry(entry);
  if (!result) toast.error(`Delete failed: ${entry.name}`);
}

async function handleCreateFolder(name: string): Promise<void> {
  try {
    await rxdb.storage.createDirectory(name, { path: browser.currentPath.value });
    showNewFolder.value = false;
    toast.success('Folder created successfully');
    await browser.refresh(browser.currentPath.value);
  } catch (err) {
    toast.error(formatErrorMessage('创建文件夹失败', err));
  }
}

async function handleRename(newName: string): Promise<void> {
  const entry = renameDialog.value.entry;
  if (!entry) return;

  try {
    if (entry.kind === 'file' && entry.meta) {
      await rxdb.storage.rename(entry.meta.id, newName);
    } else {
      await rxdb.storage.renameDirectory(entry.path, newName);
    }
    renameDialog.value = { show: false, entry: null };
    toast.success('Rename successful');
    await browser.refresh(browser.currentPath.value);
  } catch (err) {
    toast.error(formatErrorMessage('重命名失败', err));
  }
}

async function handleBatchDelete(): Promise<void> {
  if (selection.selectedPaths.value.size === 0) return;

  const selectedEntries = browser.entries.value.filter(entry => selection.selectedPaths.value.has(entry.path));
  const shouldDelete = await new Promise<boolean>(resolve => {
    deleteConfirm.value = {
      show: true,
      entry: { name: `${selection.selectedPaths.value.size} items`, kind: 'file', path: '' },
      resolve
    };
  });

  if (!shouldDelete) return;

  let failedCount = 0;
  for (const entry of selectedEntries) {
    const ok = await browser.deleteEntry(entry);
    if (!ok) failedCount++;
  }

  if (failedCount > 0) toast.error(`${failedCount} items failed to delete`);
  else toast.success(`Deleted ${selectedEntries.length} items`);

  selection.clearSelection();
}

async function handleBatchDownload(): Promise<void> {
  const selectedEntries = browser.entries.value.filter(entry => selection.selectedPaths.value.has(entry.path));
  await transfer.downloadBatch(selectedEntries);
}

async function onClearAll(): Promise<void> {
  const confirmed = await confirm(L.CONFIRM_CLEAR);
  if (!confirmed) return;

  try {
    await rxdb.storage.clear('/');
    selection.clearSelection();
    previewEntry.value = null;
    toast.success(L.CLEAR_SUCCESS);
    browser.currentPath.value = '/';
    await browser.refresh('/');
  } catch (err) {
    toast.error(formatErrorMessage('清空失败', err));
  }
}

function handleContextMenu(payload: { event: MouseEvent; entry: StorageBrowserItem }): void {
  payload.event.preventDefault();
  contextMenu.value = { show: true, x: payload.event.clientX, y: payload.event.clientY, entry: payload.entry };
}

function closeContextMenu(): void {
  contextMenu.value = { show: false, x: 0, y: 0, entry: null };
}

async function handleContextMenuAction(action: 'view' | 'download' | 'rename' | 'delete'): Promise<void> {
  const entry = contextMenu.value.entry;
  closeContextMenu();
  if (!entry) return;

  if (action === 'view') {
    if (entry.kind === 'file') previewEntry.value = entry;
    else await navigateTo(entry.path);
    return;
  }
  if (action === 'download') {
    await transfer.downloadEntry(entry);
    return;
  }
  if (action === 'rename') {
    renameDialog.value = { show: true, entry };
    return;
  }
  if (action === 'delete') {
    await handleDelete(entry);
  }
}

async function handleDrop(event: DragEvent): Promise<void> {
  event.preventDefault();
  isDragging.value = false;
  if (!event.dataTransfer) return;

  if (event.dataTransfer.items) {
    const droppedFiles: File[] = [];
    const promises: Promise<void>[] = [];
    for (let index = 0; index < event.dataTransfer.items.length; index++) {
      const item = event.dataTransfer.items[index];
      if (item.kind === 'file') {
        const entry = item.webkitGetAsEntry?.();
        if (entry) promises.push(traverseDataTransferTree(entry, '', droppedFiles));
      }
    }

    await Promise.all(promises);

    if (droppedFiles.length > 0) {
      const hasFolder = droppedFiles.some(file =>
        (file as File & { webkitRelativePath?: string }).webkitRelativePath?.includes('/')
      );
      if (hasFolder) await transfer.uploadFolder(droppedFiles);
      else await transfer.upload(droppedFiles);
    }
    return;
  }

  if (event.dataTransfer.files) {
    await transfer.upload(Array.from(event.dataTransfer.files));
  }
}

function handleMouseDown(event: MouseEvent): void {
  if (viewMode.value !== 'grid' || event.button !== 0 || event.ctrlKey || event.metaKey || event.shiftKey) return;
  const container = gridContainerRef.value;
  if (!container) return;
  selection.startBoxSelection(event, container);
}

function handleFileInputUpload(): void {
  if (fileInputRef.value?.files) {
    transfer.upload(Array.from(fileInputRef.value.files));
    fileInputRef.value.value = '';
  }
}

function handleFolderInputUpload(): void {
  if (folderInputRef.value?.files) {
    transfer.uploadFolder(Array.from(folderInputRef.value.files));
    folderInputRef.value.value = '';
  }
}

function resolveDeleteConfirm(confirmed: boolean): void {
  deleteConfirm.value.resolve?.(confirmed);
  deleteConfirm.value = { show: false, entry: null };
}

function resolveOverwrite(confirmed: boolean): void {
  overwriteConfirm.value.resolve?.(confirmed);
  overwriteConfirm.value = { show: false, file: null, existingEntry: null };
}

function resolveConfirmDialog(confirmed: boolean): void {
  confirmDialog.value.resolve?.(confirmed);
  confirmDialog.value = { show: false, message: '' };
}
</script>

<template>
  <div
    class="flex h-full flex-col"
    :data-testid="T.PAGE"
  >
    <StorageToolbar
      :all-files-count="browser.allFiles.value.length"
      :current-path="browser.currentPath.value"
      :loading="storageLoading"
      :opfs-available="opfsAvailable"
      :selection-size="selection.selectedPaths.value.size"
      :view-mode="viewMode"
      @batch-delete="handleBatchDelete"
      @batch-download="handleBatchDownload"
      @clear-all="onClearAll"
      @clear-selection="selection.clearSelection()"
      @navigate="navigateTo"
      @new-folder="showNewFolder = true"
      @refresh="browser.refresh(browser.currentPath.value)"
      @update:view-mode="viewMode = $event"
      @upload="fileInputRef?.click()"
      @upload-folder="folderInputRef?.click()"
    />

    <div
      class="relative flex-1 overflow-auto"
      @dragenter.prevent="isDragging = true"
      @dragleave.prevent="isDragging = false"
      @dragover.prevent
      @drop="handleDrop"
      @mousedown="handleMouseDown"
      ref="gridContainerRef"
    >
      <div
        class="flex h-full items-center justify-center"
        v-if="initialization.status.value === 'checking'"
      >
        <span class="loading loading-spinner loading-md" />
      </div>
      <div
        class="flex h-full items-center justify-center"
        v-else-if="storageStatusMessage"
      >
        <div class="max-w-md px-6 text-center">
          <TriangleAlert
            class="text-error mx-auto mb-4"
            :size="48"
          />
          <p class="text-error text-sm">{{ storageStatusMessage }}</p>
        </div>
      </div>
      <div
        class="flex h-full items-center justify-center"
        v-else-if="browser.entries.value.length === 0"
        :data-testid="T.EMPTY_STATE"
      >
        <div class="text-center">
          <Database
            class="text-base-content/30 mx-auto mb-4"
            :size="48"
          />
          <p class="text-base-content/60 text-sm">
            {{ browser.currentPath.value === '/' ? L.NO_FILES : 'This folder is empty' }}
          </p>
        </div>
      </div>
      <StorageFileList
        v-else-if="viewMode === 'list'"
        :current-path="browser.currentPath.value"
        :entries="browser.entries.value"
        :selected-paths="selection.selectedPaths.value"
        @context-menu="handleContextMenu"
        @delete="handleDelete"
        @download="transfer.downloadEntry"
        @entry-click="payload => selection.handleEntryClick(payload.entry, payload.event)"
        @navigate="navigateTo($event.path)"
        @preview="previewEntry = $event"
      />
      <StorageFileGrid
        v-else
        :current-path="browser.currentPath.value"
        :entries="browser.entries.value"
        :selected-paths="selection.selectedPaths.value"
        @context-menu="handleContextMenu"
        @delete="handleDelete"
        @download="transfer.downloadEntry"
        @entry-click="payload => selection.handleEntryClick(payload.entry, payload.event)"
        @navigate="navigateTo($event.path)"
        @preview="previewEntry = $event"
      />

      <div
        class="border-primary bg-primary/10 pointer-events-none absolute border-2"
        v-if="selection.selectionBox.value?.active"
        :style="{
          left: Math.min(selection.selectionBox.value.startX, selection.selectionBox.value.currentX) + 'px',
          top: Math.min(selection.selectionBox.value.startY, selection.selectionBox.value.currentY) + 'px',
          width: Math.abs(selection.selectionBox.value.currentX - selection.selectionBox.value.startX) + 'px',
          height: Math.abs(selection.selectionBox.value.currentY - selection.selectionBox.value.startY) + 'px'
        }"
      />

      <div
        class="bg-primary/10 border-primary pointer-events-none absolute inset-0 z-50 flex items-center justify-center border-2 border-dashed"
        v-if="isDragging"
      >
        <div class="bg-base-100 rounded-lg p-8 shadow-lg">
          <Upload
            class="text-primary mx-auto mb-2"
            :size="48"
          />
          <p class="text-primary text-lg font-semibold">Drop files here to upload</p>
        </div>
      </div>
    </div>

    <div class="border-base-300 text-base-content/60 flex items-center gap-4 border-t px-3 py-1 text-xs">
      <span>{{ browser.entries.value.length }} items ({{ dirCount }} folders, {{ fileCount }} files)</span>
    </div>

    <StorageFilePreview
      :entry="previewEntry"
      @close="previewEntry = null"
    />

    <StorageNewFolderDialog
      :show="showNewFolder"
      @cancel="showNewFolder = false"
      @confirm="handleCreateFolder"
    />

    <StorageOverwriteDialog
      :existing-entry="overwriteConfirm.existingEntry"
      :file="overwriteConfirm.file"
      :show="overwriteConfirm.show"
      @respond="resolveOverwrite"
    />

    <StorageContextMenu
      :entry="contextMenu.entry"
      :show="contextMenu.show"
      :x="contextMenu.x"
      :y="contextMenu.y"
      @action="handleContextMenuAction"
    />

    <StorageDeleteDialog
      :entry="deleteConfirm.entry"
      :show="deleteConfirm.show"
      @respond="resolveDeleteConfirm"
    />

    <StorageRenameDialog
      :entry="renameDialog.entry"
      :show="renameDialog.show"
      @cancel="renameDialog = { show: false, entry: null }"
      @confirm="handleRename"
    />

    <StorageConfirmDialog
      :message="confirmDialog.message"
      :show="confirmDialog.show"
      @respond="resolveConfirmDialog"
    />

    <input
      class="hidden"
      :data-testid="T.FILE_INPUT"
      @change="handleFileInputUpload"
      multiple
      ref="fileInputRef"
      type="file"
    />
    <input
      class="hidden"
      :data-testid="T.FOLDER_INPUT"
      @change="handleFolderInputUpload"
      directory
      ref="folderInputRef"
      type="file"
      webkitdirectory
    />
  </div>
</template>
