// apps/dev-rxdb-angular/src/app/pages/entity/entity-detail.page.ts
import { RxDB } from '@aiao/rxdb';
import { EntityDetailComponent, EntityFormData } from '@aiao/rxdb-model-angular';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';

/**
 * rxdb-model 实体详情演示页：create 模式——组件内部生成内存草稿实体，
 * 校验通过保存时才落库（详情 Tab 结构含基础表单；Todo 无关系故只有表单 Tab）。
 */
@Component({
  selector: 'app-entity-detail-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [EntityDetailComponent],
  template: `<rxdb-entity-detail
    class="block h-full"
    (formCancelled)="onCancelled()"
    (formSubmitted)="onSaved($event)"
    name="Todo"
    namespace="public"
  />`,
  host: { class: 'page-host flex h-full flex-col bg-base-100' }
})
export default class EntityDetailPage {
  // 注入 RxDB 以初始化本地数据库
  rxdb = inject(RxDB);

  onSaved(data: EntityFormData): void {
    console.info('[entity-detail] saved', data);
  }

  onCancelled(): void {
    console.info('[entity-detail] cancelled');
  }
}

// apps/dev-rxdb-vue/src/pages/entities/EntityDetailPage.vue
<script lang="ts" setup>
import { injectRxDB } from '@aiao/rxdb-vue';
import { EntityDetail, type EntityFormData } from '@aiao/rxdb-model-vue';
import { computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';

// 注入 RxDB 以初始化本地数据库
injectRxDB();

/** 路由参数 :namespace / :name / :entityId */
const route = useRoute();
const router = useRouter();
const namespace = computed(() => String(route.params.namespace ?? ''));
const name = computed(() => String(route.params.name ?? ''));
const entityId = computed(() => String(route.params.entityId ?? ''));

function onSaved(data: EntityFormData): void {
  console.info('[entity-detail] saved', data);
  // URL 相对导航返回实体列表（Angular '..' 同款语义：扁平四段 URL 的上一段即列表页）
  void router.push('..');
}

function onCancelled(): void {
  console.info('[entity-detail] cancelled');
  void router.push('..');
}
</script>

<template>
  <div class="page-host bg-base-100 flex h-full flex-col">
    <EntityDetail
      class="block h-full"
      :entity-id="entityId"
      :name="name"
      :namespace="namespace"
      @form-cancelled="onCancelled"
      @form-submitted="onSaved"
    />
  </div>
</template>
