// packages/rxdb-model-react/src/query-builder/query-builder/query-builder.tsx
/**
 * @fileoverview Query Builder 主组件（Angular `QueryBuilderComponent` 的 React 移植）。
 *
 * 语义与 Angular 侧一致：提供可视化的查询条件构建界面（字段选择 / 操作符 / 值输入、
 * AND/OR 组合、拖拽重排、最大 5 层嵌套、实时验证），`fields` 优先于 `schema`，
 * `initialQuery` 仅在引用变化时加载（用户修改不覆盖），Escape 在有规则时清空。
 * 服务生命周期：挂载创建、卸载销毁（对应 Angular constructor + ngOnDestroy）。
 *
 * @module query-builder/query-builder
 */
import {
  createQueryBuilderService,
  type FieldMetadata,
  type QueryBuilderService,
  type RuleGroup,
  type SchemaInfo,
  type UIRule,
  type ValidationResult
} from '@aiao/rxdb-model';
import { useEffect, useMemo, useRef, useState, type JSX } from 'react';
import { QueryDragDropHandler, QueryGroup, type UIRuleGroup } from '../query-group/query-group';

/**
 * RxDB 查询输出格式。
 */
export interface RxDBQueryOutput<T> {
  combinator: 'and' | 'or';
  rules: Array<RxDBQueryOutput<T> | { field: keyof T & string; operator: string; value: unknown }>;
}

/** {@link QueryBuilder} 的 props。 */
export interface QueryBuilderProps<T extends object = Record<string, unknown>> {
  /** Schema 信息，包含字段定义。 */
  schema?: SchemaInfo;
  /** 字段列表（直接传入，优先于 schema）。 */
  fields?: FieldMetadata[];
  /** 初始查询条件（可选）。 */
  initialQuery?: RxDBQueryOutput<T>;
  /** 最大嵌套层级，缺省 `5`。 */
  maxDepth?: number;
  /** 内容区域最大高度（超出后滚动），支持任意 CSS 长度值，如 `'400px'`、`'50vh'`，缺省 `'80vh'`。 */
  height?: string;
  /** 是否开启拖拽排序功能，缺省 `true`。 */
  enableDrag?: boolean;
  /** 是否开启分组展开/收起功能，缺省 `true`。 */
  enableCollapse?: boolean;
  /** 查询条件变更事件。 */
  onQueryChange?: (query: RxDBQueryOutput<T>) => void;
  /** 验证状态变更事件。 */
  onValidationChange?: (result: ValidationResult) => void;
}

/**
 * Query Builder 主组件。
 */
export function QueryBuilder<T extends object = Record<string, unknown>>({
  schema,
  fields = [],
  initialQuery,
  maxDepth = 5,
  height = '80vh',
  enableDrag = true,
  enableCollapse = true,
  onQueryChange,
  onValidationChange
}: QueryBuilderProps<T>): JSX.Element {
  const serviceRef = useRef<QueryBuilderService<T> | null>(null);
  const lastAppliedInitialQueryRef = useRef<unknown>(undefined);
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const onQueryChangeRef = useRef(onQueryChange);
  const onValidationChangeRef = useRef(onValidationChange);
  const [rootGroup, setRootGroup] = useState<UIRuleGroup | undefined>(undefined);
  const [validation, setValidation] = useState<ValidationResult | undefined>(undefined);
  // 拖拽状态管理器：挂载期创建一次（moveItem 实现由服务就绪后的 effect 绑定）
  const [dragDropHandler] = useState(() => new QueryDragDropHandler());

  useEffect(() => {
    onQueryChangeRef.current = onQueryChange;
  }, [onQueryChange]);

  useEffect(() => {
    onValidationChangeRef.current = onValidationChange;
  }, [onValidationChange]);

  // 计算后的字段列表（fields 优先于 schema）
  const fieldsComputed = useMemo(() => (fields.length > 0 ? fields : (schema?.fields ?? [])), [fields, schema]);

  // 服务生命周期（挂载创建 / 卸载销毁，对应 Angular constructor + ngOnDestroy）
  useEffect(() => {
    const service = createQueryBuilderService<T>({ config: { maxNestingLevel: maxDepth } });
    serviceRef.current = service;

    // 拖拽 moveItem 实现绑定到服务（服务实例 effect 期才就绪）
    dragDropHandler.setMoveItemFn((itemId, targetGroupId, targetIndex) => {
      service.moveItem(itemId, targetGroupId, targetIndex);
    });

    const groupSubscription = service.rootGroup$.subscribe(group => {
      setRootGroup(group as unknown as UIRuleGroup);
      onQueryChangeRef.current?.(service.toRxDBQuery() as unknown as RxDBQueryOutput<T>);
    });
    const validationSubscription = service.validation$.subscribe(result => {
      setValidation(result);
      onValidationChangeRef.current?.(result);
    });

    return () => {
      groupSubscription.unsubscribe();
      validationSubscription.unsubscribe();
      service.destroy();
      serviceRef.current = null;
    };
    // 初始 maxDepth 只在服务创建时读取（Angular 侧 constructor 同语义）
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dragDropHandler]);

  // 字段变化同步到服务（Angular 侧 effect 同语义）
  useEffect(() => {
    const service = serviceRef.current;
    if (service && fieldsComputed.length > 0) {
      service.setFields(fieldsComputed);
    }
  }, [fieldsComputed]);

  // 初始查询加载（引用变化时重新加载；用户修改不改变 initialQuery 引用故不会覆盖）
  useEffect(() => {
    const service = serviceRef.current;
    if (!service) return;
    if (initialQuery !== undefined && initialQuery !== lastAppliedInitialQueryRef.current) {
      lastAppliedInitialQueryRef.current = initialQuery;
      service.fromRxDBQuery(initialQuery as unknown as RuleGroup<T>);
    }
  }, [initialQuery]);

  const hasRules = !!rootGroup && rootGroup.rules.length > 0;

  /** 添加第一个规则。 */
  const addFirstRule = (): void => {
    const firstField = fieldsComputed[0];
    if (firstField) {
      serviceRef.current?.addRule(undefined, {
        field: firstField.name,
        operator:
          firstField.isRelation ? 'exists'
          : firstField.type === 'keyValue' ? 'null'
          : '=',
        value: firstField.type === 'boolean' ? false : ''
      });
    }
  };

  /** 清空所有规则。 */
  const clearAll = (): void => {
    serviceRef.current?.clear();
  };

  const scrollToBottom = (): void => {
    setTimeout(() => {
      const el = scrollContainerRef.current;
      el?.scrollTo({ top: el.scrollHeight, behavior: 'smooth' });
    }, 0);
  };

  const onAddRule = (event: { parentId: string; rule: Omit<UIRule, 'id'> }): void => {
    serviceRef.current?.addRule(event.parentId, event.rule);
    scrollToBottom();
  };

  const onAddGroup = (parentId: string): void => {
    serviceRef.current?.addGroup(parentId);
    scrollToBottom();
  };

  const onRemoveItem = (id: string): void => {
    serviceRef.current?.remove(id);
  };

  const onUpdateRule = (event: { id: string; updates: Partial<UIRule> }): void => {
    serviceRef.current?.updateRule(event.id, event.updates);
  };

  const onUpdateCombinator = (event: { id: string; combinator: 'and' | 'or' }): void => {
    serviceRef.current?.updateGroupCombinator(event.id, event.combinator);
  };

  /** 键盘快捷键处理：Escape 在有规则时清空（Angular 侧同语义）。 */
  const onKeyDown = (event: React.KeyboardEvent): void => {
    if (event.key === 'Escape' && hasRules) {
      event.preventDefault();
      clearAll();
    }
  };

  return (
    <div
      className='rxdb-query-builder bg-base-100'
      onKeyDown={onKeyDown}
      aria-label='查询条件构建器'
      role='search'
      tabIndex={0}
    >
      <div className='overflow-y-auto' ref={scrollContainerRef} style={{ maxHeight: height }}>
        <div className='mb-4 flex items-center justify-between'>
          <h3 className='text-base' id='query-builder-title'>
            查询条件
          </h3>
          <div className='flex gap-2' aria-label='查询操作' role='toolbar'>
            {hasRules && (
              <button
                className='btn btn-ghost btn-sm'
                onClick={clearAll}
                onKeyDown={event => {
                  if (event.key === 'Enter') clearAll();
                }}
                aria-label='清空所有查询条件'
                title='清空所有查询条件 (Escape)'
                type='button'
              >
                清空
              </button>
            )}
          </div>
        </div>

        {!hasRules ?
          <div className='text-base-content/60 min-w-md py-8 text-center' aria-live='polite' role='status'>
            <div className='mb-2 flex justify-center' aria-hidden='true'>
              <svg
                className='size-12 opacity-40'
                fill='none'
                stroke='currentColor'
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                viewBox='0 0 24 24'
              >
                <circle cx='11' cy='11' r='8' />
                <path d='m21 21-4.3-4.3' />
              </svg>
            </div>
            <p className='mb-4'>还没有任何查询条件</p>
            <button className='btn btn-sm' onClick={addFirstRule} aria-label='添加第一个条件' type='button'>
              添加第一个条件
            </button>
          </div>
        : <QueryGroup
            allowCollapse={enableCollapse}
            depth={0}
            dragDropHandler={enableDrag ? dragDropHandler : undefined}
            errors={validation?.errors ?? []}
            fields={fieldsComputed}
            group={rootGroup!}
            maxDepth={maxDepth}
            onAddGroup={onAddGroup}
            onAddRule={onAddRule}
            onRemoveItem={onRemoveItem}
            onUpdateCombinator={onUpdateCombinator}
            onUpdateRule={onUpdateRule}
          />
        }
      </div>
    </div>
  );
}

// packages/rxdb-model-vue/src/query-builder/query-builder/QueryBuilder.vue
<script lang="ts" setup>
/**
 * Vue Query Builder 主组件（对齐 Angular 侧 `QueryBuilderComponent`）。
 *
 * 提供可视化的查询条件构建界面，支持：
 * - 传入 SchemaInfo 或 FieldMetadata[] 定义可用字段；
 * - 拖拽重排规则和分组；
 * - 嵌套分组（最大 5 层）；
 * - 实时验证；
 * - Escape 键在有规则时清空全部条件。
 */
import {
  createQueryBuilderService,
  type FieldMetadata,
  type RuleGroup,
  type SchemaInfo,
  type UIRule,
  type ValidationResult
} from '@aiao/rxdb-model';
import { computed, onScopeDispose, ref, shallowRef, watch } from 'vue';
import QueryGroup from '../query-group/QueryGroup.vue';
import { QueryDragDropHandler, type UIRuleGroup } from '../query-group/query-drag-drop';
import type { RxDBQueryOutput } from './query-builder-types';

const props = withDefaults(
  defineProps<{
    /** Schema 信息，包含字段定义 */
    // eslint-disable-next-line vue/require-default-prop -- 对象类型 props 的 undefined 默认与 withDefaults 类型推断不兼容（语义与 Angular 的 input<T | undefined>() 一致）
    schema?: SchemaInfo;
    /** 字段列表（直接传入，优先于 schema） */
    fields?: FieldMetadata[];
    /** 初始查询条件（可选） */
    // eslint-disable-next-line vue/require-default-prop -- 对象类型 props 的 undefined 默认与 withDefaults 类型推断不兼容（语义与 Angular 的 input<T | undefined>() 一致）
    initialQuery?: RxDBQueryOutput<Record<string, unknown>>;
    /** 最大嵌套层级 */
    maxDepth?: number;
    /** 内容区域最大高度（超出后滚动） */
    height?: string;
    /** 是否开启拖拽排序功能 */
    enableDrag?: boolean;
    /** 是否开启分组展开/收起功能 */
    enableCollapse?: boolean;
  }>(),
  { fields: () => [], maxDepth: 5, height: '80vh', enableDrag: true, enableCollapse: true }
);

const emit = defineEmits<{
  /** 查询条件变更 */
  queryChange: [query: RxDBQueryOutput<Record<string, unknown>>];
  /** 验证状态变更 */
  validationChange: [result: ValidationResult];
}>();

const service = createQueryBuilderService<Record<string, unknown>>({
  config: { maxNestingLevel: props.maxDepth }
});

const rootGroup = shallowRef<UIRuleGroup | undefined>(undefined);
const validation = shallowRef<ValidationResult | undefined>(undefined);
const rootSub = service.rootGroup$.subscribe(g => (rootGroup.value = g as UIRuleGroup));
const validationSub = service.validation$.subscribe(v => (validation.value = v));

const scrollContainer = ref<HTMLElement | null>(null);

const dragDropHandler = new QueryDragDropHandler((itemId, targetGroupId, targetIndex) =>
  service.moveItem(itemId, targetGroupId, targetIndex)
);

/** 上次应用的 initialQuery 引用，用于检测是否有新查询需要加载 */
let lastAppliedInitialQuery: unknown = undefined;

/** 计算后的字段列表（fields 优先，其次 schema.fields） */
const fieldsComputed = computed(() => {
  const directFields = props.fields;
  if (directFields && directFields.length > 0) {
    return directFields;
  }
  const schemaInfo = props.schema;
  return schemaInfo?.fields ?? [];
});

/** 验证错误列表 */
const validationErrors = computed(() => validation.value?.errors ?? []);

/** 是否有规则 */
const hasRules = computed(() => {
  const group = rootGroup.value;
  return !!group && group.rules.length > 0;
});

// 监听字段变化并同步到服务
watch(
  fieldsComputed,
  fields => {
    if (fields.length > 0) {
      service.setFields(fields);
    }
  },
  { immediate: true }
);

// 监听初始查询并加载（引用变化时重新加载，用户修改不影响此 prop 故不会覆盖）
watch(
  () => props.initialQuery,
  initial => {
    if (initial !== undefined && initial !== lastAppliedInitialQuery) {
      lastAppliedInitialQuery = initial;
      service.fromRxDBQuery(initial as unknown as RuleGroup<Record<string, unknown>>);
    }
  },
  { immediate: true }
);

// 监听查询变化并发出事件
watch(rootGroup, group => {
  if (group) {
    emit('queryChange', service.toRxDBQuery() as RxDBQueryOutput<Record<string, unknown>>);
  }
});

// 监听验证变化并发出事件
watch(validation, v => {
  if (v) {
    emit('validationChange', v);
  }
});

// 同步 maxDepth 到 service
watch(
  () => props.maxDepth,
  depth => {
    service.setMaxNestingLevel(depth);
  },
  { immediate: true }
);

onScopeDispose(() => {
  rootSub.unsubscribe();
  validationSub.unsubscribe();
  service.destroy();
});

/** 添加第一个规则（用首个字段建规则） */
const addFirstRule = (): void => {
  const firstField = fieldsComputed.value[0];
  if (firstField) {
    service.addRule(undefined, {
      field: firstField.name,
      operator:
        firstField.isRelation ? 'exists'
        : firstField.type === 'keyValue' ? 'null'
        : '=',
      value: firstField.type === 'boolean' ? false : ''
    });
  }
};

/** 清空所有规则 */
const clearAll = (): void => {
  service.clear();
};

/** 添加规则到指定组 */
const onAddRule = (event: { parentId: string; rule: Omit<UIRule, 'id'> }): void => {
  service.addRule(event.parentId, event.rule);
  scrollToBottom();
};

/** 添加子组到指定组 */
const onAddGroup = (parentId: string): void => {
  service.addGroup(parentId);
  scrollToBottom();
};

/** 删除规则或组 */
const onRemoveItem = (id: string): void => {
  service.remove(id);
};

/** 更新规则 */
const onUpdateRule = (event: { id: string; updates: Partial<UIRule> }): void => {
  service.updateRule(event.id, event.updates);
};

/** 更新组合器 */
const onUpdateCombinator = (event: { id: string; combinator: 'and' | 'or' }): void => {
  service.updateGroupCombinator(event.id, event.combinator);
};

/** 键盘快捷键处理 */
const onKeyDown = (event: KeyboardEvent): void => {
  if (event.key === 'Escape' && hasRules.value) {
    event.preventDefault();
    clearAll();
  }
};

const scrollToBottom = (): void => {
  setTimeout(() => {
    scrollContainer.value?.scrollTo({ top: scrollContainer.value.scrollHeight, behavior: 'smooth' });
  }, 0);
};

defineExpose({
  hasRules,
  rootGroup,
  validationErrors,
  fieldsComputed,
  dragDropHandler,
  addFirstRule,
  clearAll,
  onKeyDown,
  onAddRule,
  onAddGroup,
  onRemoveItem,
  onUpdateRule,
  onUpdateCombinator
});
</script>

<template>
  <div
    class="rxdb-query-builder bg-base-100"
    aria-label="查询条件构建器"
    role="search"
    tabindex="0"
    @keydown="onKeyDown"
  >
    <div
      ref="scrollContainer"
      class="overflow-y-auto"
      :style="{ 'max-height': height }"
    >
      <!-- 标题栏 -->
      <div class="mb-4 flex items-center justify-between">
        <h3
          id="query-builder-title"
          class="text-base"
        >
          查询条件
        </h3>
        <div
          class="flex gap-2"
          aria-label="查询操作"
          role="toolbar"
        >
          <button
            v-if="hasRules"
            class="btn btn-ghost btn-sm"
            aria-label="清空所有查询条件"
            title="清空所有查询条件 (Escape)"
            type="button"
            @click="clearAll"
            @keydown.enter="clearAll"
          >
            清空
          </button>
        </div>
      </div>

      <!-- 空状态提示 -->
      <div
        v-if="!hasRules"
        class="text-base-content/60 min-w-md py-8 text-center"
        aria-live="polite"
        role="status"
      >
        <div
          class="mb-2 flex justify-center"
          aria-hidden="true"
        >
          <svg
            class="size-12 opacity-40"
            fill="none"
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <circle
              cx="11"
              cy="11"
              r="8"
            />
            <path d="m21 21-4.3-4.3" />
          </svg>
        </div>
        <p class="mb-4">
          还没有任何查询条件
        </p>
        <button
          class="btn btn-sm"
          aria-label="添加第一个条件"
          type="button"
          @click="addFirstRule"
        >
          添加第一个条件
        </button>
      </div>

      <!-- 根规则组 -->
      <QueryGroup
        v-else
        :allow-collapse="enableCollapse"
        :depth="0"
        :drag-drop-handler="enableDrag ? dragDropHandler : undefined"
        :errors="validationErrors"
        :fields="fieldsComputed"
        :group="rootGroup!"
        :max-depth="maxDepth"
        role="region"
        @add-group="onAddGroup"
        @add-rule="onAddRule"
        @remove-item="onRemoveItem"
        @update-combinator="onUpdateCombinator"
        @update-rule="onUpdateRule"
      />
    </div>
  </div>
</template>
