// packages/rxdb-model-react/src/entity-form/entity-form.tsx
/**
 * @fileoverview 元数据驱动表单组件（Angular `EntityFormComponent` 的 React 移植）。
 *
 * 语义与 Angular 侧一致：按字段类型渲染对应输入控件，支持 create / edit / view 三模式；
 * 解析、格式化与校验全部委托 `@aiao/rxdb-model`
 * （`parseEntityFieldValueStrict` / `validateForm` / `formatEntityFieldValue`）。
 * `data` 输入变化时重置本地表单（Angular 侧 `linkedSignal` 同语义）。
 *
 * @module entity-form
 */
import {
  EntityFieldType,
  formatEntityFieldValue,
  parseEntityFieldValueStrict,
  validateForm,
  type EntityFormData,
  type FormFieldChangeEvent,
  type FormFieldConfig,
  type FormMode,
  type FormValidationResult,
  type RelatedEntityItem,
  type RelatedEntityProvider
} from '@aiao/rxdb-model';
import { useMemo, useState, type JSX } from 'react';

/** {@link EntityForm} 的 props。 */
export interface EntityFormProps {
  /** 表单字段配置。 */
  fields: FormFieldConfig[];
  /** 表单数据（字段名 → 值）。 */
  data: EntityFormData;
  /** 表单模式（view / edit / create），缺省 `view`。 */
  mode?: FormMode;
  /** 关联实体候选提供者（关系字段下拉数据源）。 */
  relatedEntityProvider?: RelatedEntityProvider;
  /** 是否渲染保存 / 取消按钮，缺省 `true`。 */
  showActions?: boolean;
  /** 字段值变更。 */
  onFieldChanged?: (event: FormFieldChangeEvent) => void;
  /** 校验通过后的提交。 */
  onFormSubmitted?: (data: EntityFormData) => void;
  /** 取消（本地数据重置为最近一次输入）。 */
  onFormCancelled?: () => void;
  /** 校验失败（解析失败或提交校验失败）。 */
  onValidationErrors?: (result: FormValidationResult) => void;
}

/**
 * 把日期类值格式化为原生日期/时间输入框的回显值（本地时区，等价 Angular DatePipe 默认时区）。
 */
function dateToInputValue(value: unknown, pattern: 'yyyy-MM-dd' | 'HH:mm' | 'yyyy-MM-ddTHH:mm'): string {
  if (!value) return '';
  const date = value instanceof Date ? value : new Date(value as string);
  if (Number.isNaN(date.getTime())) return '';
  const pad = (n: number): string => String(n).padStart(2, '0');
  const ymd = `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
  const hm = `${pad(date.getHours())}:${pad(date.getMinutes())}`;
  if (pattern === 'yyyy-MM-dd') return ymd;
  if (pattern === 'HH:mm') return hm;
  return `${ymd}T${hm}`;
}

/** dateTime format 的显示模式映射到原生输入类型（Angular 侧 `dateInputType`）。 */
function dateInputType(field: FormFieldConfig): 'date' | 'datetime-local' | 'time' {
  const format = field.format;
  if (format?.kind === 'dateTime') {
    if (format.display === 'date') return 'date';
    if (format.display === 'time') return 'time';
  }
  return 'datetime-local';
}

/** dateTime format 的显示模式映射到回显格式（Angular 侧 `datePipeFormat`）。 */
function datePipeFormat(field: FormFieldConfig): 'yyyy-MM-dd' | 'HH:mm' | 'yyyy-MM-ddTHH:mm' {
  const format = field.format;
  if (format?.kind === 'dateTime') {
    if (format.display === 'date') return 'yyyy-MM-dd';
    if (format.display === 'time') return 'HH:mm';
  }
  return 'yyyy-MM-ddTHH:mm';
}

/** 数字类 format 的值域约束（min / max / step）。 */
function numericBounds(field: FormFieldConfig): { min?: number; max?: number; step?: number } {
  const format = field.format;
  if (
    format &&
    (format.kind === 'number' ||
      format.kind === 'currency' ||
      format.kind === 'percentage' ||
      format.kind === 'duration' ||
      format.kind === 'rating')
  ) {
    return {
      ...(format.min === undefined ? {} : { min: format.min }),
      ...(format.max === undefined ? {} : { max: format.max }),
      ...(format.step === undefined ? {} : { step: format.step })
    };
  }
  return {};
}

/** 数字类 format 的单位标注（currency 代码 / 百分号 / 时长单位）。 */
function numericUnitLabel(field: FormFieldConfig): string {
  switch (field.format?.kind) {
    case 'currency':
      return field.format.currency;
    case 'percentage':
      return '%';
    case 'duration':
      return field.format.unit;
    default:
      return '';
  }
}

/** 字符串 format 映射到原生输入类型。 */
function textInputType(field: FormFieldConfig): string {
  switch (field.format?.kind) {
    case 'url':
      return 'url';
    case 'email':
      return 'email';
    case 'phone':
      return 'tel';
    default:
      return 'text';
  }
}

/** 多行文本类 format：渲染 textarea。 */
function isTextareaFormat(field: FormFieldConfig): boolean {
  const kind = field.format?.kind;
  return kind === 'multilineText' || kind === 'richText' || kind === 'code';
}

/** 取色器回显值：非法或空值退回黑色。 */
function colorValue(value: unknown): string {
  return (
    typeof value === 'string' && /^#?[0-9a-fA-F]{6}$/.test(value) ?
      value.startsWith('#') ?
        value
      : `#${value}`
    : '#000000'
  );
}

/** 字节序列回显为 hex 字符串。 */
function binaryToHex(value: unknown): string {
  return value instanceof Uint8Array ? Array.from(value, byte => byte.toString(16).padStart(2, '0')).join('') : '';
}

/**
 * 元数据驱动表单组件：按字段类型渲染对应输入控件，支持 create / edit / view 三模式。
 */
export function EntityForm({
  fields,
  data,
  mode = 'view',
  relatedEntityProvider,
  showActions = true,
  onFieldChanged,
  onFormSubmitted,
  onFormCancelled,
  onValidationErrors
}: EntityFormProps): JSX.Element {
  const [initialData, setInitialData] = useState<EntityFormData>(() => ({ ...data }));
  const [formData, setFormData] = useState<EntityFormData>(() => ({ ...data }));

  // data 输入变化 → 重置本地表单（Angular 侧 linkedSignal 同语义；渲染期调整状态）
  const [prevData, setPrevData] = useState(data);
  if (prevData !== data) {
    setPrevData(data);
    setInitialData({ ...data });
    setFormData({ ...data });
  }

  const editableFields = useMemo(() => fields.filter(field => !field.hidden), [fields]);
  const isReadonly = mode === 'view';

  const relatedItemsMap = useMemo(() => {
    const map = new Map<string, RelatedEntityItem[]>();
    if (!relatedEntityProvider) return map;
    for (const field of editableFields) {
      if (field.relatedEntityName) {
        map.set(field.field, relatedEntityProvider(field.relatedEntityName, field.relatedNamespace));
      }
    }
    return map;
  }, [relatedEntityProvider, editableFields]);

  const displayValueMap = useMemo(() => {
    const map = new Map<string, string>();
    for (const field of editableFields) {
      if (!isReadonly && field.readonly !== true) continue;
      const value = formData[field.field];
      if ((field.type === 'oneToOne' || field.type === 'manyToOne') && field.relatedEntityName) {
        const items = relatedItemsMap.get(field.field) ?? [];
        const item = items.find(i => i.id === value);
        map.set(field.field, item?.displayName ?? formatEntityFieldValue(field.type, value, field.format));
      } else if (field.type === 'enum' && field.options) {
        const label = field.options[String(value)]?.label;
        map.set(field.field, label ?? formatEntityFieldValue(field.type, value, field.format));
      } else if (field.type === 'stringArray' && field.options) {
        const items =
          Array.isArray(value) ? value
          : typeof value === 'string' ? value.split(',')
          : [];
        map.set(field.field, items.map(v => field.options![String(v).trim()]?.label ?? String(v).trim()).join(', '));
      } else {
        map.set(field.field, formatEntityFieldValue(field.type, value, field.format));
      }
    }
    return map;
  }, [editableFields, formData, isReadonly, relatedItemsMap]);

  /** 字段变更：严格解析失败输出 validationErrors 且不更新本地数据（Angular 侧同语义）。 */
  const onFieldChange = (field: FormFieldConfig, rawValue: unknown): void => {
    const previousValue = formData[field.field];
    const result = parseEntityFieldValueStrict(field.type, rawValue);
    if (!result.ok) {
      onValidationErrors?.({
        valid: false,
        errors: [{ field: field.field, message: `${field.displayName} ${result.message}` }]
      });
      return;
    }
    const parsed = result.value;
    setFormData(current => ({ ...current, [field.field]: parsed }));
    onFieldChanged?.({ field: field.field, type: field.type as EntityFieldType, value: parsed, previousValue });
  };

  const onSubmit = (): void => {
    const result = validateForm(fields, formData);
    if (!result.valid) {
      onValidationErrors?.(result);
      return;
    }
    onFormSubmitted?.(formData);
  };

  const onCancel = (): void => {
    setFormData({ ...initialData });
    onFormCancelled?.();
  };

  /** 复选组的当前选中状态（支持数组与逗号字符串两种存储形态）。 */
  const multiSelected = (field: FormFieldConfig, value: string): boolean => {
    const current = formData[field.field];
    if (Array.isArray(current)) return current.includes(value);
    if (typeof current === 'string')
      return current
        .split(',')
        .map(s => s.trim())
        .includes(value);
    return false;
  };

  /** 复选组切换：合并出新数组后走统一解析链路。 */
  const onMultiSelectChange = (field: FormFieldConfig, value: string, checked: boolean): void => {
    const current = formData[field.field];
    const list =
      Array.isArray(current) ? [...(current as string[])]
      : typeof current === 'string' ?
        current
          .split(',')
          .map(s => s.trim())
          .filter(Boolean)
      : [];
    const next = checked ? [...list, value] : list.filter(v => v !== value);
    onFieldChange(field, next);
  };

  /** 渲染单个字段的编辑控件。 */
  const renderFieldInput = (field: FormFieldConfig): JSX.Element => {
    if (isReadonly || field.readonly === true) {
      return (
        <div className='input input-ghost flex min-h-10 items-center'>{displayValueMap.get(field.field) ?? ''}</div>
      );
    }
    switch (field.type) {
      case 'boolean':
        return (
          <input
            className='toggle'
            checked={!!formData[field.field]}
            onChange={event => onFieldChange(field, event.target.checked)}
            type='checkbox'
          />
        );
      case 'enum':
        return (
          <select
            className='select'
            value={(formData[field.field] as string) ?? ''}
            onChange={event => onFieldChange(field, event.target.value)}
          >
            {field.nullable && <option value=''>(空)</option>}
            {(field.enumValues ?? []).map(value => (
              <option key={value} value={value} disabled={field.options?.[value]?.disabled === true}>
                {field.options?.[value]?.label ?? value}
              </option>
            ))}
          </select>
        );
      case 'date':
        return (
          <input
            className='input'
            type={dateInputType(field)}
            value={formData[field.field] ? dateToInputValue(formData[field.field], datePipeFormat(field)) : ''}
            onChange={event => onFieldChange(field, event.target.value)}
          />
        );
      case 'number':
      case 'integer': {
        const bounds = numericBounds(field);
        return (
          <div className='flex items-center gap-2'>
            <input
              className='input flex-1'
              {...(bounds.max === undefined ? {} : { max: bounds.max })}
              {...(bounds.min === undefined ? {} : { min: bounds.min })}
              placeholder={field.placeholder ?? ''}
              step={bounds.step ?? (field.type === 'integer' ? '1' : 'any')}
              value={(formData[field.field] as string | number) ?? ''}
              onChange={event => onFieldChange(field, event.target.value)}
              type='number'
            />
            {numericUnitLabel(field) && <span className='label w-10 shrink-0'>{numericUnitLabel(field)}</span>}
          </div>
        );
      }
      case 'bigint':
        return (
          <input
            className='input'
            placeholder={field.placeholder ?? ''}
            value={String(formData[field.field] ?? '')}
            onChange={event => onFieldChange(field, event.target.value)}
            inputMode='numeric'
            type='text'
          />
        );
      case 'binary':
        return (
          <textarea
            className='textarea min-h-16 font-mono'
            placeholder={field.placeholder ?? '十六进制字节序列（如 0a0b）'}
            value={binaryToHex(formData[field.field])}
            onChange={event => onFieldChange(field, event.target.value)}
          />
        );
      case 'stringArray':
        if (field.enumValues && field.enumValues.length > 0) {
          return (
            <div className='flex flex-col gap-1'>
              {field.enumValues.map(value => (
                <label className='flex items-center gap-2' key={value}>
                  <input
                    className='checkbox'
                    checked={multiSelected(field, value)}
                    disabled={field.options?.[value]?.disabled === true}
                    onChange={event => onMultiSelectChange(field, value, event.target.checked)}
                    type='checkbox'
                  />
                  {field.options?.[value]?.color && (
                    <span
                      className='inline-block h-2 w-2 rounded-full'
                      style={{ background: field.options[value]!.color }}
                    />
                  )}
                  <span>{field.options?.[value]?.label ?? value}</span>
                </label>
              ))}
            </div>
          );
        }
        return (
          <input
            className='input'
            placeholder={field.placeholder ?? '逗号分隔'}
            value={((formData[field.field] as string[] | undefined) ?? []).join(', ')}
            onChange={event => onFieldChange(field, event.target.value)}
            type='text'
          />
        );
      case 'numberArray':
        return (
          <input
            className='input'
            placeholder={field.placeholder ?? '逗号分隔数字'}
            value={((formData[field.field] as number[] | undefined) ?? []).join(', ')}
            onChange={event => onFieldChange(field, event.target.value)}
            type='text'
          />
        );
      case 'json':
      case 'keyValue': {
        const raw = formData[field.field];
        return (
          <textarea
            className='textarea min-h-24'
            placeholder={field.placeholder ?? 'JSON'}
            value={raw !== null && raw !== undefined ? JSON.stringify(raw) : ''}
            onChange={event => onFieldChange(field, event.target.value)}
          />
        );
      }
      case 'oneToOne':
      case 'manyToOne':
        return (
          <select
            className='select'
            value={(formData[field.field] as string) ?? ''}
            onChange={event => onFieldChange(field, event.target.value)}
          >
            <option value=''>(空)</option>
            {(relatedItemsMap.get(field.field) ?? []).map(item => (
              <option key={item.id} value={item.id}>
                {item.displayName}
              </option>
            ))}
          </select>
        );
      default:
        if (field.format?.kind === 'color') {
          return (
            <div className='flex items-center gap-2'>
              <input
                className='h-9 w-12 cursor-pointer border-0 bg-transparent'
                value={colorValue(formData[field.field])}
                onChange={event => onFieldChange(field, event.target.value)}
                type='color'
              />
              <input
                className='input flex-1'
                placeholder={field.placeholder ?? '#rrggbb'}
                value={(formData[field.field] as string) ?? ''}
                onChange={event => onFieldChange(field, event.target.value)}
                type='text'
              />
            </div>
          );
        }
        if (isTextareaFormat(field)) {
          return (
            <textarea
              className='textarea min-h-16'
              placeholder={field.placeholder ?? ''}
              value={(formData[field.field] as string) ?? ''}
              onChange={event => onFieldChange(field, event.target.value)}
            />
          );
        }
        return (
          <input
            className='input'
            placeholder={field.placeholder ?? ''}
            type={textInputType(field)}
            value={(formData[field.field] as string | number) ?? ''}
            onChange={event => onFieldChange(field, event.target.value)}
          />
        );
    }
  };

  /** 占据两列栅格的字段：json / keyValue / binary / 多行文本类 format / 显式 span。 */
  const isWideField = (field: FormFieldConfig): boolean =>
    field.span === 2 ||
    field.type === 'json' ||
    field.type === 'keyValue' ||
    field.type === 'binary' ||
    isTextareaFormat(field);

  return (
    <form
      className='grid grid-cols-1 gap-4 md:grid-cols-2'
      onSubmit={event => {
        event.preventDefault();
        onSubmit();
      }}
    >
      {editableFields.map(field => (
        <fieldset
          className={`fieldset${isWideField(field) ? 'md:col-span-2' : ''}`}
          data-field={field.field}
          key={field.field}
        >
          <legend className='fieldset-legend'>{field.displayName}</legend>
          {renderFieldInput(field)}
          {field.helpText && <p className='label'>{field.helpText}</p>}
        </fieldset>
      ))}
      {!isReadonly && showActions && (
        <div className='flex justify-end gap-2 pt-2 md:col-span-2'>
          <button className='btn' onClick={onCancel} type='button'>
            取消
          </button>
          <button className='btn btn-primary' type='submit'>
            保存
          </button>
        </div>
      )}
    </form>
  );
}

// packages/rxdb-model-vue/src/entity-form/EntityForm.vue
<script lang="ts" setup>
/**
 * 元数据驱动表单组件：按字段类型渲染对应输入控件，支持 create / edit / view 三模式；
 * 解析、格式化与校验全部委托 `@aiao/rxdb-model`。
 *
 * 对齐 Angular 侧 `EntityFormComponent`：字段控件、只读展示、操作按钮与
 * 四条输出链路（fieldChanged / formSubmitted / formCancelled / validationErrors）
 * 逐项等价，模板文案逐字一致。
 */
import type {
  EntityFieldType,
  EntityFormData,
  FormFieldChangeEvent,
  FormFieldConfig,
  FormMode,
  FormValidationResult,
  RelatedEntityItem,
  RelatedEntityProvider
} from '@aiao/rxdb-model';
import { formatEntityFieldValue, parseEntityFieldValueStrict, validateForm } from '@aiao/rxdb-model';
import { computed, ref, watch } from 'vue';

const props = withDefaults(
  defineProps<{
    /** 字段配置 */
    fields: FormFieldConfig[];
    /** 表单数据 */
    data: EntityFormData;
    /** 表单模式 */
    mode?: FormMode;
    /** 关系实体候选提供者 */
    relatedEntityProvider?: RelatedEntityProvider;
    /** 是否渲染保存/取消操作按钮 */
    showActions?: boolean;
  }>(),
  { mode: 'view', showActions: true, relatedEntityProvider: undefined }
);

const emit = defineEmits<{
  /** 字段值变更 */
  fieldChanged: [event: FormFieldChangeEvent];
  /** 表单提交 */
  formSubmitted: [data: EntityFormData];
  /** 表单取消 */
  formCancelled: [];
  /** 校验错误 */
  validationErrors: [result: FormValidationResult];
}>();

/** 初始数据（data 属性变化时重置） */
const initialData = ref<EntityFormData>({ ...props.data });
/** 当前编辑数据（取消时回到 initialData） */
const formData = ref<EntityFormData>({ ...initialData.value });

watch(
  () => props.data,
  data => {
    initialData.value = { ...data };
    formData.value = { ...data };
  }
);

/** 可编辑字段（隐藏字段不渲染） */
const editableFields = computed(() => props.fields.filter(f => !f.hidden));

/** view 模式整体只读 */
const isReadonly = computed(() => props.mode === 'view');

/** 关系字段候选（field → 关联实体条目列表） */
const relatedItemsMap = computed(() => {
  const provider = props.relatedEntityProvider;
  const map = new Map<string, RelatedEntityItem[]>();
  if (!provider) return map;
  for (const field of editableFields.value) {
    if (field.relatedEntityName) {
      map.set(field.field, provider(field.relatedEntityName, field.relatedNamespace));
    }
  }
  return map;
});

/** 只读字段的展示值（field → 格式化字符串） */
const displayValueMap = computed(() => {
  const data = formData.value;
  const fields = editableFields.value;
  const itemsMap = relatedItemsMap.value;
  const map = new Map<string, string>();
  for (const field of fields) {
    if (!isReadonly.value && field.readonly !== true) continue;
    const value = data[field.field];
    if ((field.type === 'oneToOne' || field.type === 'manyToOne') && field.relatedEntityName) {
      const items = itemsMap.get(field.field) ?? [];
      const item = items.find(i => i.id === value);
      map.set(field.field, item?.displayName ?? formatEntityFieldValue(field.type, value, field.format));
    } else if (field.type === 'enum' && field.options) {
      const label = field.options[String(value)]?.label;
      map.set(field.field, label ?? formatEntityFieldValue(field.type, value, field.format));
    } else if (field.type === 'stringArray' && field.options) {
      const items =
        Array.isArray(value) ? value
        : typeof value === 'string' ? value.split(',')
        : [];
      map.set(field.field, items.map(v => field.options![String(v).trim()]?.label ?? String(v).trim()).join(', '));
    } else {
      map.set(field.field, formatEntityFieldValue(field.type, value, field.format));
    }
  }
  return map;
});

/** 字段变更：统一解析链路（解析失败 emit validationErrors 且不更新数据） */
const onFieldChange = (field: FormFieldConfig, rawValue: unknown): void => {
  const current = formData.value;
  const previousValue = current[field.field];
  const result = parseEntityFieldValueStrict(field.type, rawValue);
  if (!result.ok) {
    emit('validationErrors', {
      valid: false,
      errors: [{ field: field.field, message: `${field.displayName} ${result.message}` }]
    });
    return;
  }
  const parsed = result.value;
  formData.value = { ...current, [field.field]: parsed };
  emit('fieldChanged', { field: field.field, type: field.type as EntityFieldType, value: parsed, previousValue });
};

/** 表单提交：校验通过才 emit formSubmitted */
const onSubmit = (): void => {
  const result = validateForm(props.fields, formData.value);
  if (!result.valid) {
    emit('validationErrors', result);
    return;
  }
  emit('formSubmitted', formData.value);
};

/** 取消：重置为初始数据并 emit formCancelled */
const onCancel = (): void => {
  formData.value = { ...initialData.value };
  emit('formCancelled');
};

/** 字段是否只读展示 */
const isFieldReadonly = (field: FormFieldConfig): boolean => isReadonly.value || field.readonly === true;

/** 占据两列栅格的字段：json / keyValue / binary / 多行文本类 format / 显式 span */
const isWideField = (field: FormFieldConfig): boolean =>
  field.span === 2 ||
  field.type === 'json' ||
  field.type === 'keyValue' ||
  field.type === 'binary' ||
  isTextareaFormat(field);

/** 多行文本类 format：渲染 textarea */
const isTextareaFormat = (field: FormFieldConfig): boolean => {
  const kind = field.format?.kind;
  return kind === 'multilineText' || kind === 'richText' || kind === 'code';
};

/** dateTime format 的显示模式映射到原生输入类型 */
const dateInputType = (field: FormFieldConfig): 'date' | 'datetime-local' | 'time' => {
  const format = field.format;
  if (format?.kind === 'dateTime') {
    if (format.display === 'date') return 'date';
    if (format.display === 'time') return 'time';
  }
  return 'datetime-local';
};

/** dateTime format 的显示模式映射到日期格式（对齐 Angular DatePipe 格式） */
const datePipeFormat = (field: FormFieldConfig): string => {
  const format = field.format;
  if (format?.kind === 'dateTime') {
    if (format.display === 'date') return 'yyyy-MM-dd';
    if (format.display === 'time') return 'HH:mm';
  }
  return 'yyyy-MM-ddTHH:mm';
};

/** 数字类 format 的值域约束（min / max / step） */
const numericBounds = (field: FormFieldConfig): { min?: number; max?: number; step?: number } => {
  const format = field.format;
  if (
    format &&
    (format.kind === 'number' ||
      format.kind === 'currency' ||
      format.kind === 'percentage' ||
      format.kind === 'duration' ||
      format.kind === 'rating')
  ) {
    return {
      ...(format.min === undefined ? {} : { min: format.min }),
      ...(format.max === undefined ? {} : { max: format.max }),
      ...(format.step === undefined ? {} : { step: format.step })
    };
  }
  return {};
};

/** 数字类 format 的单位标注（currency 代码 / 百分号 / 时长单位） */
const numericUnitLabel = (field: FormFieldConfig): string => {
  switch (field.format?.kind) {
    case 'currency':
      return field.format.currency;
    case 'percentage':
      return '%';
    case 'duration':
      return field.format.unit;
    default:
      return '';
  }
};

/** enum / 多选值的展示 label（无 options 时退回原值） */
const enumOptionLabel = (field: FormFieldConfig, value: string): string => field.options?.[value]?.label ?? value;

/** options 中声明 disabled 的值不可选 */
const enumOptionDisabled = (field: FormFieldConfig, value: string): boolean =>
  field.options?.[value]?.disabled === true;

/** 字符串 format 映射到原生输入类型 */
const textInputType = (field: FormFieldConfig): string => {
  switch (field.format?.kind) {
    case 'url':
      return 'url';
    case 'email':
      return 'email';
    case 'phone':
      return 'tel';
    default:
      return 'text';
  }
};

/** 取色器回显值：非法或空值退回黑色 */
const colorValue = (field: FormFieldConfig): string => {
  const value = formData.value[field.field];
  return (
    typeof value === 'string' && /^#?[0-9a-fA-F]{6}$/.test(value) ?
      value.startsWith('#') ?
        value
      : `#${value}`
    : '#000000'
  );
};

/** 字节序列回显为 hex 字符串 */
const binaryToHex = (value: unknown): string =>
  value instanceof Uint8Array ? Array.from(value, byte => byte.toString(16).padStart(2, '0')).join('') : '';

/** 复选组的当前选中状态（支持数组与逗号字符串两种存储形态） */
const multiSelected = (field: FormFieldConfig, value: string): boolean => {
  const current = formData.value[field.field];
  if (Array.isArray(current)) return current.includes(value);
  if (typeof current === 'string')
    return current
      .split(',')
      .map(s => s.trim())
      .includes(value);
  return false;
};

/** 复选组切换：合并出新数组后走统一解析链路 */
const onMultiSelectChange = (field: FormFieldConfig, value: string, checked: boolean): void => {
  const current = formData.value[field.field];
  const list =
    Array.isArray(current) ? [...(current as string[])]
    : typeof current === 'string' ?
      current
        .split(',')
        .map(s => s.trim())
        .filter(Boolean)
    : [];
  const next = checked ? [...list, value] : list.filter(v => v !== value);
  onFieldChange(field, next);
};

/** 数组类字段的输入回显（数组 → 逗号分隔字符串） */
const arrayJoin = (value: unknown): string => (Array.isArray(value) ? value : []).join(', ');

/** JSON 类字段的输入回显（null → 空串） */
const jsonOrEmpty = (value: unknown): string => (value !== null ? JSON.stringify(value) : '');

const pad2 = (n: number): string => String(n).padStart(2, '0');
/** 输入控件的回显值（string / number 原样；null / undefined 回退空串；其余 String 化） */
const displayInputValue = (field: FormFieldConfig): string | number => {
  const v = formData.value[field.field];
  if (v === null || v === undefined) return '';
  return typeof v === 'string' || typeof v === 'number' ? v : String(v);
};

/** 日期类字段的输入回显（对齐 Angular DatePipe 的 yyyy-MM-dd / HH:mm / yyyy-MM-ddTHH:mm） */
const dateInputValue = (field: FormFieldConfig): string => {
  const value = formData.value[field.field];
  if (!value) return '';
  const date = value instanceof Date ? value : new Date(String(value));
  if (Number.isNaN(date.getTime())) return '';
  const format = datePipeFormat(field);
  const datePart = `${date.getFullYear()}-${pad2(date.getMonth() + 1)}-${pad2(date.getDate())}`;
  const timePart = `${pad2(date.getHours())}:${pad2(date.getMinutes())}`;
  if (format === 'yyyy-MM-dd') return datePart;
  if (format === 'HH:mm') return timePart;
  return `${datePart}T${timePart}`;
};

defineExpose({
  initialData,
  formData,
  editableFields,
  isReadonly,
  relatedItemsMap,
  displayValueMap,
  onFieldChange,
  onSubmit,
  onCancel,
  isFieldReadonly,
  isWideField,
  isTextareaFormat,
  dateInputType,
  datePipeFormat,
  numericBounds,
  numericUnitLabel,
  enumOptionLabel,
  enumOptionDisabled,
  textInputType,
  colorValue,
  binaryToHex,
  multiSelected,
  onMultiSelectChange,
  displayInputValue
});
</script>

<template>
  <form
    class="grid grid-cols-1 gap-4 md:grid-cols-2"
    @submit.prevent="onSubmit"
  >
    <fieldset
      v-for="field in editableFields"
      :key="field.field"
      class="fieldset"
      :class="{ 'md:col-span-2': isWideField(field) }"
    >
      <legend class="fieldset-legend">
        {{ field.displayName }}
      </legend>
      <div
        v-if="isFieldReadonly(field)"
        class="input input-ghost flex min-h-10 items-center"
      >
        {{ displayValueMap.get(field.field) ?? '' }}
      </div>
      <template v-else>
        <template v-if="field.type === 'boolean'">
          <input
            class="toggle"
            :checked="!!formData[field.field]"
            type="checkbox"
            @change="onFieldChange(field, ($event.target as HTMLInputElement).checked)"
          >
        </template>
        <select
          v-else-if="field.type === 'enum'"
          class="select"
          :value="displayInputValue(field)"
          @change="onFieldChange(field, ($event.target as HTMLSelectElement).value)"
        >
          <option
            v-if="field.nullable"
            value=""
          >
            (空)
          </option>
          <option
            v-for="val in field.enumValues ?? []"
            :key="val"
            :disabled="enumOptionDisabled(field, val)"
            :value="val"
          >
            {{ enumOptionLabel(field, val) }}
          </option>
        </select>
        <input
          v-else-if="field.type === 'date'"
          class="input"
          :type="dateInputType(field)"
          :value="dateInputValue(field)"
          @change="onFieldChange(field, ($event.target as HTMLInputElement).value)"
        >
        <div
          v-else-if="field.type === 'number'"
          class="flex items-center gap-2"
        >
          <input
            class="input flex-1"
            :max="numericBounds(field).max"
            :min="numericBounds(field).min"
            :placeholder="field.placeholder ?? ''"
            :step="numericBounds(field).step ?? 'any'"
            :value="displayInputValue(field)"
            type="number"
            @change="onFieldChange(field, ($event.target as HTMLInputElement).value)"
          >
          <span
            v-if="numericUnitLabel(field)"
            class="label w-10 shrink-0"
          >{{ numericUnitLabel(field) }}</span>
        </div>
        <div
          v-else-if="field.type === 'integer'"
          class="flex items-center gap-2"
        >
          <input
            class="input flex-1"
            :max="numericBounds(field).max"
            :min="numericBounds(field).min"
            :placeholder="field.placeholder ?? ''"
            :step="numericBounds(field).step ?? '1'"
            :value="displayInputValue(field)"
            type="number"
            @change="onFieldChange(field, ($event.target as HTMLInputElement).value)"
          >
          <span
            v-if="numericUnitLabel(field)"
            class="label w-10 shrink-0"
          >{{ numericUnitLabel(field) }}</span>
        </div>
        <input
          v-else-if="field.type === 'bigint'"
          class="input"
          :placeholder="field.placeholder ?? ''"
          :value="displayInputValue(field)"
          inputmode="numeric"
          type="text"
          @change="onFieldChange(field, ($event.target as HTMLInputElement).value)"
        >
        <textarea
          v-else-if="field.type === 'binary'"
          class="textarea min-h-16 font-mono"
          :placeholder="field.placeholder ?? '十六进制字节序列（如 0a0b）'"
          :value="binaryToHex(formData[field.field])"
          @change="onFieldChange(field, ($event.target as HTMLTextAreaElement).value)"
        />
        <div
          v-else-if="field.type === 'stringArray' && field.enumValues && field.enumValues.length > 0"
          class="flex flex-col gap-1"
        >
          <label
            v-for="val in field.enumValues"
            :key="val"
            class="flex items-center gap-2"
          >
            <input
              class="checkbox"
              :checked="multiSelected(field, val)"
              :disabled="enumOptionDisabled(field, val)"
              type="checkbox"
              @change="onMultiSelectChange(field, val, ($event.target as HTMLInputElement).checked)"
            >
            <span
              v-if="field.options?.[val]?.color"
              class="inline-block h-2 w-2 rounded-full"
              :style="{ background: field.options?.[val]?.color }"
            />
            <span>{{ enumOptionLabel(field, val) }}</span>
          </label>
        </div>
        <input
          v-else-if="field.type === 'stringArray'"
          class="input"
          :placeholder="field.placeholder ?? '逗号分隔'"
          :value="arrayJoin(formData[field.field] ?? [])"
          type="text"
          @change="onFieldChange(field, ($event.target as HTMLInputElement).value)"
        >
        <input
          v-else-if="field.type === 'numberArray'"
          class="input"
          :placeholder="field.placeholder ?? '逗号分隔数字'"
          :value="arrayJoin(formData[field.field] ?? [])"
          type="text"
          @change="onFieldChange(field, ($event.target as HTMLInputElement).value)"
        >
        <textarea
          v-else-if="field.type === 'json'"
          class="textarea min-h-24"
          :placeholder="field.placeholder ?? 'JSON'"
          :value="jsonOrEmpty(formData[field.field])"
          @change="onFieldChange(field, ($event.target as HTMLTextAreaElement).value)"
        />
        <textarea
          v-else-if="field.type === 'keyValue'"
          class="textarea min-h-24"
          :placeholder="field.placeholder ?? 'JSON'"
          :value="jsonOrEmpty(formData[field.field])"
          @change="onFieldChange(field, ($event.target as HTMLTextAreaElement).value)"
        />
        <select
          v-else-if="field.type === 'oneToOne'"
          class="select"
          :value="displayInputValue(field)"
          @change="onFieldChange(field, ($event.target as HTMLSelectElement).value)"
        >
          <option value="">
            (空)
          </option>
          <option
            v-for="item in relatedItemsMap.get(field.field) ?? []"
            :key="item.id"
            :value="item.id"
          >
            {{ item.displayName }}
          </option>
        </select>
        <select
          v-else-if="field.type === 'manyToOne'"
          class="select"
          :value="displayInputValue(field)"
          @change="onFieldChange(field, ($event.target as HTMLSelectElement).value)"
        >
          <option value="">
            (空)
          </option>
          <option
            v-for="item in relatedItemsMap.get(field.field) ?? []"
            :key="item.id"
            :value="item.id"
          >
            {{ item.displayName }}
          </option>
        </select>
        <div
          v-else-if="field.format?.kind === 'color'"
          class="flex items-center gap-2"
        >
          <input
            class="h-9 w-12 cursor-pointer border-0 bg-transparent"
            :value="colorValue(field)"
            type="color"
            @change="onFieldChange(field, ($event.target as HTMLInputElement).value)"
          >
          <input
            class="input flex-1"
            :placeholder="field.placeholder ?? '#rrggbb'"
            :value="displayInputValue(field)"
            type="text"
            @change="onFieldChange(field, ($event.target as HTMLInputElement).value)"
          >
        </div>
        <textarea
          v-else-if="isTextareaFormat(field)"
          class="textarea min-h-16"
          :placeholder="field.placeholder ?? ''"
          :value="displayInputValue(field)"
          @change="onFieldChange(field, ($event.target as HTMLTextAreaElement).value)"
        />
        <input
          v-else
          class="input"
          :placeholder="field.placeholder ?? ''"
          :type="textInputType(field)"
          :value="displayInputValue(field)"
          @change="onFieldChange(field, ($event.target as HTMLInputElement).value)"
        >
      </template>
      <p
        v-if="field.helpText"
        class="label"
      >
        {{ field.helpText }}
      </p>
    </fieldset>
    <div
      v-if="!isReadonly && showActions"
      class="flex justify-end gap-2 pt-2 md:col-span-2"
    >
      <button
        class="btn"
        type="button"
        @click="onCancel"
      >
        取消
      </button>
      <button
        class="btn btn-primary"
        type="submit"
      >
        保存
      </button>
    </div>
  </form>
</template>
