// apps/dev-rxdb-vue/src/app/components/AppThemeBtn.vue
<script lang="ts" setup>
import { MoonStar, Palette, Sun } from '@lucide/vue';
import { useTheme } from '../composables/useTheme';

const { currentTheme, setTheme } = useTheme();

const toggleTheme = () => {
  const next =
    currentTheme.value === 'auto' ? 'dark'
    : currentTheme.value === 'dark' ? 'light'
    : 'auto';
  setTheme(next);
};
</script>

<template>
  <button
    class="btn btn-ghost btn-sm px-2"
    @click="toggleTheme"
    aria-label="theme"
  >
    <Sun
      v-if="currentTheme === 'light'"
      :size="16"
    />
    <MoonStar
      v-else-if="currentTheme === 'dark'"
      :size="16"
    />
    <Palette
      v-else
      :size="16"
    />
  </button>
</template>

// apps/dev-rxdb-react/src/app/components/AppThemeBtn.tsx
import { MoonStar, Palette, Sun } from 'lucide-react';
import { useTheme } from '../hooks/useTheme';

export function AppThemeBtn() {
  const { currentTheme, setTheme } = useTheme();

  const handleToggleTheme = () => {
    let nextTheme: 'auto' | 'dark' | 'light' = 'auto';
    switch (currentTheme) {
      case 'auto':
        nextTheme = 'dark';
        break;
      case 'dark':
        nextTheme = 'light';
        break;
      case 'light':
        nextTheme = 'auto';
        break;
    }
    setTheme(nextTheme);
  };

  const getIcon = () => {
    switch (currentTheme) {
      case 'light':
        return <Sun size={16} />;
      case 'dark':
        return <MoonStar size={16} />;
      default:
        return <Palette size={16} />;
    }
  };

  return (
    <button className='btn btn-ghost btn-sm px-2' onClick={handleToggleTheme} aria-label='theme'>
      {getIcon()}
    </button>
  );
}
