// packages/rxdb-model-vue/src/entity-table/EntityTable.vue
<script lang="ts" setup>
/**
 * 通用实体数据表格组件（对齐 Angular 侧 `EntityTableComponent`）。
 *
 * 基于 VTable 提供高性能表格渲染，全部表格基础设施（列构建、编辑器、剪贴板、
 * 键盘、主题）来自 `@aiao/rxdb-model`；本组件负责表格实例生命周期、事件桥接、
 * 暗色主题探测与销毁释放。
 */
import type {
  BatchChangeItem,
  CellChangeEvent,
  EntityTableRecord,
  HeaderPositionChange,
  PendingWrite,
  RowMoveEvent
} from '@aiao/rxdb-model';
import {
  CellTooltipManager,
  ROW_SERIES_COL_OFFSET,
  TableClipboardManager,
  collectDeleteWrites,
  collectReorderedIds,
  completeTableEdit,
  createListTable,
  createTheme,
  getCSSVariables,
  handleTableKeydown,
  isDocumentDarkMode,
  patchDragIconForReadonlyRows,
  readRowMove,
  restoreTableRecords,
  setCellSwitchState,
  setRowDragEnabled,
  syncHeaderSortIcon,
  updateTableRecords,
  changeCellValue as vtChangeCellValue
} from '@aiao/rxdb-model';
import type { ListTable, ListTableConstructorOptions } from '@visactor/vtable';
import * as VTable from '@visactor/vtable';
import { inject, onBeforeUnmount, onMounted, ref, shallowRef, watch } from 'vue';
import { ENTITY_TABLE_CONFIG } from './config';

const props = withDefaults(
  defineProps<{
    /** 表格行数据 */
    records: EntityTableRecord[];
    /** 列定义 */
    columns: ListTableConstructorOptions['columns'];
    /** 是否暗色主题（缺省时自动探测） */
    isDarkMode?: boolean;
    /** 主键字段名 */
    idField?: string;
    /** 不可清空的字段集合 */
    nonClearableFields?: ReadonlySet<string>;
    /** VTable 构造选项（覆盖默认配置） */
    // eslint-disable-next-line vue/require-default-prop -- 对象类型 props 的 undefined 默认与 withDefaults 类型推断不兼容（语义与 Angular 的 input<T | undefined>() 一致）
    tableOptions?: Partial<ListTableConstructorOptions>;
    /** 单元格错误检测器（悬停时显示 tooltip） */
    cellErrorDetector?: (record: EntityTableRecord, field: string) => string | null;
    /** 是否加载中（渲染 spinner） */
    loading?: boolean;
    /** 业务层回调判断单元格是否可清空（返回 false 跳过） */
    cellClearable?: (record: Record<string, unknown>, field: string) => boolean;
    /** 触底时加载更多数据的回调 */
    loadMore?: () => void;
    /** 加载更多中状态（底部小 spinner，不拦截滚动） */
    loadingMore?: boolean;
    /** 是否显示行拖动手柄，缺省 `true`；运行时切换即时生效（建表需开启 `rowSeriesNumber.dragOrder`） */
    rowDragEnabled?: boolean;
  }>(),
  {
    isDarkMode: undefined,
    idField: 'id',
    nonClearableFields: () => new Set<string>(),
    cellErrorDetector: undefined,
    loading: false,
    cellClearable: undefined,
    loadMore: undefined,
    loadingMore: false,
    rowDragEnabled: true
  }
);

const emit = defineEmits<{
  /** 单元格变更 */
  cellChanged: [event: CellChangeEvent];
  /** 行删除（delete-action 图标） */
  rowDeleted: [record: EntityTableRecord];
  /** 图标点击（delete-action 之外的名字） */
  iconClicked: [event: { name: string; record: EntityTableRecord }];
  /** 批量变更（剪贴板粘贴 / Delete 清空） */
  batchUpdated: [items: BatchChangeItem[]];
  /** 行拖拽重排后的 id 顺序 */
  rowReordered: [ids: string[]];
  /** 单行拖放：被拖行与落点前后邻居（US-028） */
  rowMoved: [move: RowMoveEvent];
  /** 触底且未提供 loadMore */
  scrollNearBottom: [];
  /** 列头排序点击（业务层接管查询排序） */
  sortClicked: [event: { field: unknown; order: unknown }];
}>();

const config = inject(ENTITY_TABLE_CONFIG, undefined);

/** 当前表格实例（初始化后为真实 VTable ListTable） */
const tableInstance = shallowRef<ListTable | null>(null);
const tableContainer = ref<HTMLElement | null>(null);
const tableReady = ref(false);
const cellTooltip = ref<{ x: number; y: number; content: string } | null>(null);
const headerHeight = ref(40);

let prevColumns: ListTableConstructorOptions['columns'] | null = null;
let prevRecords: EntityTableRecord[] | null = null;
/** 最近一次交给表格的行顺序副本：VTable 拖放会原地改写传入数组 */
let committedRecords: EntityTableRecord[] = [];
let selectedCell: { col: number; row: number } | null = null;
let containerKeydownHandler: ((e: KeyboardEvent) => void) | null = null;
let resizeObserver: ResizeObserver | null = null;
let containerEl: HTMLElement | null = null;
let themeObserver: MutationObserver | null = null;
let prefersDarkQuery: MediaQueryList | null = null;
let prefersDarkListener: (() => void) | null = null;

const detectedDarkMode = ref(false);
const clipboard = new TableClipboardManager();
const tooltip = new CellTooltipManager();

const resolvedDarkMode = (): boolean => props.isDarkMode ?? detectedDarkMode.value;

const syncDetectedDarkMode = (): void => {
  detectedDarkMode.value = isDocumentDarkMode();
};

const observeThemeChanges = (): void => {
  if (typeof MutationObserver !== 'undefined') {
    themeObserver = new MutationObserver(() => syncDetectedDarkMode());
    themeObserver.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['data-theme']
    });
  }

  if (typeof window === 'undefined' || typeof window.matchMedia !== 'function') {
    return;
  }

  prefersDarkQuery = window.matchMedia('(prefers-color-scheme: dark)');
  prefersDarkListener = (): void => {
    if (!document.documentElement.hasAttribute('data-theme')) {
      syncDetectedDarkMode();
    }
  };
  prefersDarkQuery.addEventListener('change', prefersDarkListener);
};

const initTable = (container: HTMLElement): void => {
  const table = createListTable(container, props.records, props.columns, resolvedDarkMode(), props.tableOptions);
  tableInstance.value = table;
  prevRecords = props.records;
  committedRecords = [...props.records];
  containerEl = container;
  const h = table.getRowHeight(0);
  if (h > 0) headerHeight.value = h;

  resizeObserver = new ResizeObserver(() => table.resize());
  resizeObserver.observe(container);
  table.updateTheme(createTheme(resolvedDarkMode(), getCSSVariables()));
  patchDragIconForReadonlyRows(table);
  setRowDragEnabled(table, props.rowDragEnabled);
  bindTableEvents(table, container);
};

/** 从业务层回滚单元格值（校验失败时恢复原值） */
const changeCellValue = (col: number, row: number, value: unknown): void => {
  if (tableInstance.value) vtChangeCellValue(tableInstance.value, col, row, value);
};

/** 把行恢复成最近一次交给表格的顺序（拖放被拒或落库失败时调用） */
const restoreRecords = (): void => {
  if (tableInstance.value && prevRecords) restoreTableRecords(tableInstance.value, prevRecords, committedRecords);
};

/** 重绘主题（isDarkMode / 自动探测变化时） */
const redrawTheme = (): void => {
  if (tableInstance.value) {
    tableInstance.value.updateTheme(createTheme(resolvedDarkMode(), getCSSVariables()));
  }
};

const bindTableEvents = (table: VTable.ListTable, container: HTMLElement): void => {
  table.on('change_cell_value', (args: { col: number; row: number; changedValue: string | number }) => {
    handleCellChange(args.col, args.row, args.changedValue);
  });
  table.on('switch_state_change', (args: { col: number; row: number; checked: boolean }) => {
    handleCellChange(args.col, args.row, args.checked);
  });
  table.on('checkbox_state_change', (args: { col: number; row: number; checked: boolean }) => {
    handleCellChange(args.col, args.row, args.checked);
  });
  table.on('icon_click', (args: { name: string; col: number; row: number }) => {
    completeTableEdit(table);
    const record = table.getRecordByCell(args.col, args.row) as EntityTableRecord | undefined;
    if (!record) return;
    if (args.name === 'delete-action') emit('rowDeleted', record);
    else emit('iconClicked', { name: args.name, record });
  });
  table.on('mouseenter_cell', (args: { col: number; row: number }) => showCellError(args.col, args.row));
  table.on('mouseleave_cell', () => tooltip.hide(v => (cellTooltip.value = v)));
  table.on('selected_cell', (args: { col: number; row: number }) => {
    selectedCell = { col: args.col, row: args.row };
  });
  table.on('change_header_position', (args: HeaderPositionChange) => {
    const ids = collectReorderedIds(table, props.idField);
    if (ids.length > 0) emit('rowReordered', ids);
    const move = readRowMove(table, props.idField, args);
    if (move) emit('rowMoved', move);
  });
  // 返回 false 阻止 VTable executeSort，由业务层 cursor orderBy 重查；排序图标另行同步
  table.on('sort_click', (args: { field: unknown; order: unknown }) => {
    emit('sortClicked', { field: args.field, order: args.order });
    syncHeaderSortIcon(table, args);
    return false;
  });
  table.on('scroll', (args: { scrollDirection: string; scrollRatioY?: number; dy?: number }) => {
    if (
      args.scrollDirection === 'vertical' &&
      (args.dy ?? 0) > 0 &&
      (args.scrollRatioY ?? 0) > 0.9 &&
      !props.loadingMore
    ) {
      const fn = props.loadMore;
      if (fn) {
        fn();
      } else {
        emit('scrollNearBottom');
      }
    }
  });

  containerKeydownHandler = (e: KeyboardEvent) =>
    handleTableKeydown(
      {
        getTable: () => tableInstance.value,
        getSelectedCell: () => selectedCell,
        getColDef: col => getColDef(col),
        onCopy: () => void clipboard.copy(table, props.columns as Record<string, unknown>[]),
        onPaste: () => void pasteFromClipboard(),
        onDelete: () => deleteSelectedCells(),
        onCellChange: (col, row, val) => handleCellChange(col, row, val)
      },
      e
    );
  container.addEventListener('keydown', containerKeydownHandler);
};

const getColDef = (col: number): { cellType?: string; field?: string } | undefined =>
  (props.columns as Record<string, unknown>[])?.[col - ROW_SERIES_COL_OFFSET] as
    { cellType?: string; field?: string } | undefined;

const handleCellChange = (col: number, row: number, changedValue: unknown): void => {
  const record = tableInstance.value?.getRecordByCell(col, row) as EntityTableRecord | undefined;
  const fieldName = (getColDef(col) as { field?: string } | undefined)?.field;
  if (!record || !fieldName) return;
  emit('cellChanged', { col, row, field: fieldName, value: changedValue, record });
};

const showCellError = (col: number, row: number): void => {
  const table = tableInstance.value;
  if (!table) return;
  const detector = props.cellErrorDetector;
  if (!detector) return;
  const record = table.getRecordByCell(col, row) as EntityTableRecord | undefined;
  if (!record) return;
  const field = (getColDef(col) as { field?: string } | undefined)?.field;
  if (!field) return;
  const content = detector(record, field);
  if (!content) return;
  tooltip.showError(table, col, row, content, v => (cellTooltip.value = v), config?.tooltipDelay);
};

/** 将 PendingWrite[] 按 idField 归并为 BatchChangeItem[] */
const groupWrites = (writes: PendingWrite[]): BatchChangeItem[] => {
  const map = new Map<string, Record<string, unknown>>();
  for (const w of writes) {
    const id = String((w.record as Record<string, unknown>)[props.idField]);
    if (!map.has(id)) map.set(id, {});
    map.get(id)![w.field] = w.value;
  }
  return [...map.entries()].map(([recordId, changes]) => ({ recordId, changes }));
};

const pasteFromClipboard = async (): Promise<void> => {
  if (!tableInstance.value) return;
  const writes = await clipboard.paste(tableInstance.value, props.columns as Record<string, unknown>[]);
  if (writes.length > 0) {
    for (const w of writes) {
      if (typeof w.value === 'boolean') {
        setCellSwitchState(tableInstance.value, w.col, w.row, w.value);
      }
    }
    emit('batchUpdated', groupWrites(writes));
  }
};

const deleteSelectedCells = (): void => {
  const table = tableInstance.value;
  if (!table) return;
  const columns = props.columns as { field?: string; cellType?: string | ((...a: unknown[]) => string) }[];
  const { writes, boolCells } = collectDeleteWrites(table, columns, props.nonClearableFields, props.cellClearable);
  for (const bc of boolCells) setCellSwitchState(table, bc.col, bc.row, false);
  if (writes.length > 0) emit('batchUpdated', groupWrites(writes));
};

onMounted(() => {
  syncDetectedDarkMode();
  observeThemeChanges();

  const el = tableContainer.value;
  if (el && !tableInstance.value && props.columns?.length) {
    initTable(el);
    prevColumns = props.columns;
    tableReady.value = true;
  }
});

watch(
  () => [props.records, props.columns] as const,
  ([records, columns]) => {
    if (!tableInstance.value) {
      if (!tableReady.value && columns?.length) {
        const el = tableContainer.value;
        if (el) {
          initTable(el);
          prevColumns = columns;
          tableReady.value = true;
        }
      }
      return;
    }
    const columnsChanged = columns !== prevColumns;
    if (columnsChanged) {
      updateTableRecords(tableInstance.value, records, prevColumns ?? columns, columns);
      prevColumns = columns;
      prevRecords = records;
      committedRecords = [...records];
    } else if (records !== prevRecords) {
      tableInstance.value.setRecords(records);
      prevRecords = records;
      committedRecords = [...records];
    }
  }
);

// 行拖动手柄开关（VTable 只在建表时读 dragOrder，运行时经补丁过的 getIcons 收起）
watch(
  () => props.rowDragEnabled,
  enabled => {
    if (tableInstance.value) setRowDragEnabled(tableInstance.value, enabled);
  }
);

watch([() => props.isDarkMode, detectedDarkMode], () => {
  redrawTheme();
});

onBeforeUnmount(() => {
  tooltip.cleanup();
  themeObserver?.disconnect();
  themeObserver = null;
  if (prefersDarkQuery && prefersDarkListener) {
    prefersDarkQuery.removeEventListener('change', prefersDarkListener);
  }
  prefersDarkQuery = null;
  prefersDarkListener = null;
  if (containerKeydownHandler) {
    containerEl?.removeEventListener('keydown', containerKeydownHandler);
    containerKeydownHandler = null;
  }
  resizeObserver?.disconnect();
  resizeObserver = null;
  if (tableInstance.value) {
    completeTableEdit(tableInstance.value);
    tableInstance.value.release();
  }
  tableInstance.value = null;
  containerEl = null;
  tableReady.value = false;
});

defineExpose({
  tableInstance,
  tableContainer,
  headerHeight,
  cellTooltip,
  changeCellValue,
  redrawTheme,
  restoreRecords
});
</script>

<template>
  <div class="rxdb-entity-table relative h-full w-full overflow-hidden">
    <div
      ref="tableContainer"
      class="absolute inset-0"
    />
    <div
      v-if="records.length === 0 && !loading"
      class="text-base-content/40 absolute inset-x-0 bottom-0 flex items-center justify-center text-sm"
      :style="{ top: headerHeight + 'px' }"
      aria-label="暂无数据"
      role="status"
    >
      <div class="empty-slot">
        <slot name="emptyState" />
      </div>
      <div class="empty-default flex flex-col items-center gap-3">
        <svg
          aria-hidden="true"
          fill="none"
          height="40"
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="1.2"
          viewBox="0 0 24 24"
          width="40"
          xmlns="http://www.w3.org/2000/svg"
        >
          <rect
            height="18"
            rx="2"
            width="18"
            x="3"
            y="3"
          />
          <path d="M3 9h18" />
          <path d="M9 9v12" />
          <path d="M3 15h18" />
        </svg>
        <span>暂无数据</span>
      </div>
    </div>
    <div
      v-if="loading"
      class="bg-base-100/60 absolute inset-0 z-10 flex items-center justify-center"
    >
      <span class="loading loading-spinner loading-md text-primary" />
    </div>
    <div
      v-if="loadingMore"
      class="pointer-events-none absolute right-0 bottom-0 left-0 z-10 flex justify-center py-1.5"
    >
      <span class="loading loading-dots loading-sm text-primary" />
    </div>
    <div
      v-if="cellTooltip"
      class="bg-base-300 text-base-content border-base-300 pointer-events-none fixed z-[100] max-w-xs rounded border px-2 py-1.5 text-xs shadow-lg"
      :style="{ left: cellTooltip.x + 'px', top: cellTooltip.y + 'px' }"
      aria-atomic="true"
      aria-live="assertive"
      role="tooltip"
    >
      {{ cellTooltip.content }}
    </div>
  </div>
</template>

<style scoped>
.rxdb-entity-table {
  display: block;
  width: 100%;
  height: 100%;
  min-height: 200px;
}

.empty-slot:has(> *) ~ .empty-default {
  display: none;
}
</style>

// packages/rxdb-model-react/src/entity-table/entity-table.tsx
/**
 * @fileoverview VTable 表格宿主组件（Angular `EntityTableComponent` 的 React 移植）。
 *
 * 语义与 Angular 侧一致：负责表格实例生命周期、事件桥接（VTable 事件 →
 * onCellChanged / onBatchUpdated / onRowDeleted / onIconClicked / onRowReordered / onRowMoved /
 * onScrollNearBottom / onSortClicked）、暗色主题探测与销毁释放；
 * 全部表格基础设施（列构建、编辑器、剪贴板、键盘、主题）来自 `@aiao/rxdb-model`。
 *
 * 命令式能力（`tableInstance` / `changeCellValue` / `redrawTheme` / `restoreRecords`）经 ref handle 暴露
 * （对应 Angular 组件上的公开 getter 与方法）。
 *
 * @module entity-table/entity-table
 */
import type {
  BatchChangeItem,
  CellChangeEvent,
  EntityTableHandle,
  EntityTableRecord,
  HeaderPositionChange,
  PendingWrite,
  RowMoveEvent
} from '@aiao/rxdb-model';
import {
  CellTooltipManager,
  ROW_SERIES_COL_OFFSET,
  TableClipboardManager,
  collectDeleteWrites,
  collectReorderedIds,
  completeTableEdit,
  createListTable,
  createTheme,
  getCSSVariables,
  handleTableKeydown,
  isDocumentDarkMode,
  patchDragIconForReadonlyRows,
  readRowMove,
  restoreTableRecords,
  setCellSwitchState,
  setRowDragEnabled,
  syncHeaderSortIcon,
  updateTableRecords,
  changeCellValue as vtChangeCellValue
} from '@aiao/rxdb-model';
import type { ListTable, ListTableConstructorOptions } from '@visactor/vtable';
import { forwardRef, useContext, useEffect, useImperativeHandle, useRef, useState, type ReactNode } from 'react';
import { ENTITY_TABLE_CONFIG } from './config';
import './entity-table.css';

/** 单元格错误 tooltip 快照。 */
interface CellTooltipState {
  x: number;
  y: number;
  content: string;
}

/** {@link EntityTable} 的 props。 */
export interface EntityTableProps {
  /** 表格记录。 */
  records: EntityTableRecord[];
  /** 列定义。 */
  columns: NonNullable<ListTableConstructorOptions['columns']>;
  /** 暗色模式；缺省时自动探测（data-theme / prefers-color-scheme）。 */
  isDarkMode?: boolean;
  /** 主键字段名，缺省 `'id'`。 */
  idField?: string;
  /** 不可清空的字段集合（Delete 清空时跳过）。 */
  nonClearableFields?: ReadonlySet<string>;
  /** 透传给 VTable 的额外表格选项。 */
  tableOptions?: Partial<ListTableConstructorOptions>;
  /** 单元格错误检测器（悬停时显示 tooltip）。 */
  cellErrorDetector?: (record: EntityTableRecord, field: string) => string | null;
  /** 是否显示加载态。 */
  loading?: boolean;
  /** 业务层回调判断单元格是否可清空（返回 false 跳过）。 */
  cellClearable?: (record: Record<string, unknown>, field: string) => boolean;
  /** 触底时加载更多数据的回调。 */
  loadMore?: () => void;
  /** 加载更多中状态（已有数据，底部小 spinner，不拦截滚动）。 */
  loadingMore?: boolean;
  /** 空态插槽（有内容时替代默认空态）。 */
  emptyState?: ReactNode;
  /** 单元格变更。 */
  onCellChanged?: (event: CellChangeEvent) => void;
  /** 行删除（delete-action 图标）。 */
  onRowDeleted?: (record: EntityTableRecord) => void;
  /** 非删除类图标点击。 */
  onIconClicked?: (event: { name: string; record: EntityTableRecord }) => void;
  /** 批量变更（剪贴板粘贴 / Delete 清空）。 */
  onBatchUpdated?: (mutations: BatchChangeItem[]) => void;
  /** 行重排（列头拖拽）。 */
  onRowReordered?: (orderedIds: string[]) => void;
  /** 是否显示行拖动手柄，缺省 `true`；运行时切换即时生效（建表需开启 `rowSeriesNumber.dragOrder`）。 */
  rowDragEnabled?: boolean;
  /** 单行拖放：被拖行与落点前后邻居（US-028）。 */
  onRowMoved?: (move: RowMoveEvent) => void;
  /** 触底且未提供 loadMore 时输出。 */
  onScrollNearBottom?: () => void;
  /** 列头排序点击；业务层接管查询排序，表格不执行客户端排序。 */
  onSortClicked?: (event: { field: unknown; order: unknown }) => void;
}

/**
 * VTable 表格宿主组件。
 */
export const EntityTable = forwardRef<EntityTableHandle, EntityTableProps>(function EntityTable(
  {
    records,
    columns,
    isDarkMode,
    idField = 'id',
    nonClearableFields = new Set<string>(),
    tableOptions,
    cellErrorDetector,
    loading = false,
    cellClearable,
    loadMore,
    loadingMore = false,
    emptyState,
    onCellChanged,
    onRowDeleted,
    onIconClicked,
    onBatchUpdated,
    onRowReordered,
    rowDragEnabled = true,
    onRowMoved,
    onScrollNearBottom,
    onSortClicked
  },
  ref
) {
  const config = useContext(ENTITY_TABLE_CONFIG);

  const containerRef = useRef<HTMLDivElement>(null);
  const tableRef = useRef<ListTable | null>(null);
  const prevColumnsRef = useRef<ListTableConstructorOptions['columns'] | null>(null);
  const prevRecordsRef = useRef<EntityTableRecord[] | null>(null);
  /** 最近一次交给表格的行顺序副本：VTable 拖放会原地改写传入数组 */
  const committedRecordsRef = useRef<EntityTableRecord[]>([]);
  const selectedCellRef = useRef<{ col: number; row: number } | null>(null);
  const clipboardRef = useRef<TableClipboardManager | null>(null);
  const tooltipRef = useRef<CellTooltipManager | null>(null);
  const resizeObserverRef = useRef<ResizeObserver | null>(null);
  const themeObserverRef = useRef<MutationObserver | null>(null);
  const containerKeydownHandlerRef = useRef<((e: KeyboardEvent) => void) | null>(null);
  const prefersDarkQueryRef = useRef<MediaQueryList | null>(null);
  const prefersDarkListenerRef = useRef<(() => void) | null>(null);
  const configRef = useRef(config);

  const [tableReady, setTableReady] = useState(false);
  const [cellTooltip, setCellTooltip] = useState<CellTooltipState | null>(null);
  const [headerHeight, setHeaderHeight] = useState(40);
  const [detectedDarkMode, setDetectedDarkMode] = useState(false);

  // 事件回调与可选项始终读最新值（VTable 事件在渲染周期外触发）
  const propsRef = useRef({
    records,
    columns,
    isDarkMode,
    idField,
    nonClearableFields,
    tableOptions,
    cellErrorDetector,
    loading,
    cellClearable,
    loadMore,
    loadingMore,
    onCellChanged,
    onRowDeleted,
    onIconClicked,
    onBatchUpdated,
    onRowReordered,
    rowDragEnabled,
    onRowMoved,
    onScrollNearBottom,
    onSortClicked
  });
  useEffect(() => {
    propsRef.current = {
      records,
      columns,
      isDarkMode,
      idField,
      nonClearableFields,
      tableOptions,
      cellErrorDetector,
      loading,
      cellClearable,
      loadMore,
      loadingMore,
      onCellChanged,
      onRowDeleted,
      onIconClicked,
      onBatchUpdated,
      onRowReordered,
      rowDragEnabled,
      onRowMoved,
      onScrollNearBottom,
      onSortClicked
    };
  });

  useEffect(() => {
    configRef.current = config;
  }, [config]);

  const resolvedDarkMode = isDarkMode ?? detectedDarkMode;
  const resolvedDarkModeRef = useRef(resolvedDarkMode);
  resolvedDarkModeRef.current = resolvedDarkMode;

  // ── 暗色模式探测（data-theme 属性 + prefers-color-scheme）──────────────
  useEffect(() => {
    setDetectedDarkMode(isDocumentDarkMode());
    if (typeof MutationObserver !== 'undefined') {
      const observer = new MutationObserver(() => setDetectedDarkMode(isDocumentDarkMode()));
      observer.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });
      themeObserverRef.current = observer;
    }
    if (typeof window === 'undefined' || typeof window.matchMedia !== 'function') {
      return () => {
        themeObserverRef.current?.disconnect();
        themeObserverRef.current = null;
      };
    }
    const query = window.matchMedia('(prefers-color-scheme: dark)');
    const listener = (): void => {
      if (!document.documentElement.hasAttribute('data-theme')) {
        setDetectedDarkMode(isDocumentDarkMode());
      }
    };
    query.addEventListener('change', listener);
    prefersDarkQueryRef.current = query;
    prefersDarkListenerRef.current = listener;
    return () => {
      themeObserverRef.current?.disconnect();
      themeObserverRef.current = null;
      if (prefersDarkQueryRef.current && prefersDarkListenerRef.current) {
        prefersDarkQueryRef.current.removeEventListener('change', prefersDarkListenerRef.current);
      }
      prefersDarkQueryRef.current = null;
      prefersDarkListenerRef.current = null;
    };
  }, []);

  // ── 主题重绘 ────────────────────────────────────────────────────────────
  useEffect(() => {
    const table = tableRef.current;
    if (table) table.updateTheme(createTheme(resolvedDarkMode, getCSSVariables()));
  }, [resolvedDarkMode, tableReady]);

  // ── 初始化 / records / columns 同步（对应 Angular 的 afterNextRender + effect）──
  useEffect(() => {
    const el = containerRef.current;
    if (!tableRef.current && !tableReady && columns.length > 0 && el) {
      initTable(el);
      prevColumnsRef.current = columns;
      prevRecordsRef.current = records;
      setTableReady(true);
    }
    const table = tableRef.current;
    if (!table) return;
    const columnsChanged = columns !== prevColumnsRef.current;
    if (columnsChanged) {
      updateTableRecords(table, records, prevColumnsRef.current ?? columns, columns);
      prevColumnsRef.current = columns;
      prevRecordsRef.current = records;
      committedRecordsRef.current = [...records];
    } else if (records !== prevRecordsRef.current) {
      table.setRecords(records);
      prevRecordsRef.current = records;
      committedRecordsRef.current = [...records];
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [records, columns, tableReady]);

  // ── 行拖动手柄开关（VTable 只在建表时读 dragOrder，运行时经补丁过的 getIcons 收起）──
  useEffect(() => {
    const table = tableRef.current;
    if (table) setRowDragEnabled(table, rowDragEnabled);
  }, [rowDragEnabled, tableReady]);

  /** 创建表格实例、注册基础事件与容器键盘监听（对应 Angular `#initTable`）。 */
  function initTable(container: HTMLElement): void {
    const current = propsRef.current;
    const columnDefs = current.columns ?? [];
    const table = createListTable(
      container,
      current.records,
      columnDefs,
      resolvedDarkModeRef.current,
      current.tableOptions
    );
    tableRef.current = table;
    prevRecordsRef.current = current.records;
    committedRecordsRef.current = [...current.records];
    const h = table.getRowHeight(0);
    if (h > 0) setHeaderHeight(h);

    const resizeObserver = new ResizeObserver(() => table.resize());
    resizeObserver.observe(container);
    resizeObserverRef.current = resizeObserver;

    table.updateTheme(createTheme(resolvedDarkModeRef.current, getCSSVariables()));
    patchDragIconForReadonlyRows(table);
    setRowDragEnabled(table, current.rowDragEnabled);

    table.on('change_cell_value', (args: { col: number; row: number; changedValue: string | number }) => {
      handleCellChange(args.col, args.row, args.changedValue);
    });
    table.on('switch_state_change', (args: { col: number; row: number; checked: boolean }) => {
      handleCellChange(args.col, args.row, args.checked);
    });
    table.on('checkbox_state_change', (args: { col: number; row: number; checked: boolean }) => {
      handleCellChange(args.col, args.row, args.checked);
    });
    table.on('icon_click', (args: { name: string; col: number; row: number }) => {
      completeTableEdit(table);
      const record = table.getRecordByCell(args.col, args.row) as EntityTableRecord | undefined;
      if (!record) return;
      if (args.name === 'delete-action') propsRef.current.onRowDeleted?.(record);
      else propsRef.current.onIconClicked?.({ name: args.name, record });
    });
    table.on('mouseenter_cell', (args: { col: number; row: number }) => showCellError(args.col, args.row));
    table.on('mouseleave_cell', () => {
      const tooltip = tooltipRef.current ?? (tooltipRef.current = new CellTooltipManager());
      tooltip.hide(() => setCellTooltip(null));
    });
    table.on('selected_cell', (args: { col: number; row: number }) => {
      selectedCellRef.current = { col: args.col, row: args.row };
    });
    table.on('change_header_position', (args: HeaderPositionChange) => {
      const ids = collectReorderedIds(table, propsRef.current.idField);
      if (ids.length > 0) propsRef.current.onRowReordered?.(ids);
      const move = readRowMove(table, propsRef.current.idField, args);
      if (move) propsRef.current.onRowMoved?.(move);
    });
    // 返回 false 阻止 VTable executeSort，由业务层 cursor orderBy 重查；排序图标另行同步
    table.on('sort_click', (args: { field: unknown; order: unknown }) => {
      propsRef.current.onSortClicked?.({ field: args.field, order: args.order });
      syncHeaderSortIcon(table, args);
      return false;
    });
    table.on('scroll', (args: { scrollDirection: string; scrollRatioY?: number; dy?: number }) => {
      if (
        args.scrollDirection === 'vertical' &&
        (args.dy ?? 0) > 0 &&
        (args.scrollRatioY ?? 0) > 0.9 &&
        !propsRef.current.loadingMore
      ) {
        const fn = propsRef.current.loadMore;
        if (fn) fn();
        else propsRef.current.onScrollNearBottom?.();
      }
    });

    const keydownHandler = (e: KeyboardEvent): void =>
      handleTableKeydown(
        {
          getTable: () => tableRef.current,
          getSelectedCell: () => selectedCellRef.current,
          getColDef: col => getColDef(col),
          onCopy: () => void getClipboard().copy(table, propsRef.current.columns as Record<string, unknown>[]),
          onPaste: () => void pasteFromClipboard(),
          onDelete: () => deleteSelectedCells(),
          onCellChange: (col, row, val) => handleCellChange(col, row, val)
        },
        e
      );
    containerKeydownHandlerRef.current = keydownHandler;
    container.addEventListener('keydown', keydownHandler);
  }

  function getClipboard(): TableClipboardManager {
    return clipboardRef.current ?? (clipboardRef.current = new TableClipboardManager());
  }

  /** 按列索引取列定义（跳过行号列）。 */
  function getColDef(col: number): { cellType?: string; field?: string } | undefined {
    return (propsRef.current.columns as Record<string, unknown>[])?.[col - ROW_SERIES_COL_OFFSET] as
      { cellType?: string; field?: string } | undefined;
  }

  /** VTable 单元格变更 → onCellChanged（携带列字段名与行记录）。 */
  function handleCellChange(col: number, row: number, changedValue: unknown): void {
    const table = tableRef.current;
    const record = table?.getRecordByCell(col, row) as EntityTableRecord | undefined;
    const fieldName = getColDef(col)?.field;
    if (!record || !fieldName) return;
    propsRef.current.onCellChanged?.({ col, row, field: fieldName, value: changedValue, record });
  }

  /** 悬停单元格：cellErrorDetector 命中时经 CellTooltipManager 延迟显示错误 tooltip。 */
  function showCellError(col: number, row: number): void {
    const table = tableRef.current;
    if (!table) return;
    const detector = propsRef.current.cellErrorDetector;
    if (!detector) return;
    const record = table.getRecordByCell(col, row) as EntityTableRecord | undefined;
    if (!record) return;
    const field = getColDef(col)?.field;
    if (!field) return;
    const content = detector(record, field);
    if (!content) return;
    const tooltip = tooltipRef.current ?? (tooltipRef.current = new CellTooltipManager());
    tooltip.showError(table, col, row, content, value => setCellTooltip(value), configRef.current?.tooltipDelay);
  }

  /** 将 PendingWrite[] 按 idField 归并为 BatchChangeItem[]。 */
  function groupWrites(writes: PendingWrite[]): BatchChangeItem[] {
    const map = new Map<string, Record<string, unknown>>();
    for (const w of writes) {
      const id = String((w.record as Record<string, unknown>)[propsRef.current.idField]);
      if (!map.has(id)) map.set(id, {});
      map.get(id)![w.field] = w.value;
    }
    return [...map.entries()].map(([recordId, changes]) => ({ recordId, changes }));
  }

  /** Ctrl+V 粘贴：系统剪贴板 TSV → 批量写入 → onBatchUpdated。 */
  async function pasteFromClipboard(): Promise<void> {
    const table = tableRef.current;
    if (!table) return;
    const writes = await getClipboard().paste(table, propsRef.current.columns as Record<string, unknown>[]);
    if (writes.length > 0) {
      for (const w of writes) {
        if (typeof w.value === 'boolean') {
          setCellSwitchState(table, w.col, w.row, w.value);
        }
      }
      propsRef.current.onBatchUpdated?.(groupWrites(writes));
    }
  }

  /** Delete 清空选中单元格 → onBatchUpdated。 */
  function deleteSelectedCells(): void {
    const table = tableRef.current;
    if (!table) return;
    const current = propsRef.current;
    const writes = collectDeleteWrites(
      table,
      current.columns as { field?: string; cellType?: string | ((...a: unknown[]) => string) }[],
      current.nonClearableFields,
      current.cellClearable
    );
    for (const bc of writes.boolCells) setCellSwitchState(table, bc.col, bc.row, false);
    if (writes.writes.length > 0) current.onBatchUpdated?.(groupWrites(writes.writes));
  }

  useImperativeHandle(
    ref,
    () => ({
      get tableInstance(): ListTable | null {
        return tableRef.current;
      },
      changeCellValue(col: number, row: number, value: unknown): void {
        const table = tableRef.current;
        if (table) vtChangeCellValue(table, col, row, value);
      },
      redrawTheme(): void {
        const table = tableRef.current;
        if (table) table.updateTheme(createTheme(resolvedDarkModeRef.current, getCSSVariables()));
      },
      restoreRecords(): void {
        const table = tableRef.current;
        const records = prevRecordsRef.current;
        if (table && records) restoreTableRecords(table, records, committedRecordsRef.current);
      }
    }),
    []
  );

  // ── 销毁释放（对应 Angular ngOnDestroy）───────────────────────────────
  useEffect(() => {
    const container = containerRef.current;
    return () => {
      tooltipRef.current?.cleanup();
      themeObserverRef.current?.disconnect();
      if (prefersDarkQueryRef.current && prefersDarkListenerRef.current) {
        prefersDarkQueryRef.current.removeEventListener('change', prefersDarkListenerRef.current);
      }
      if (containerKeydownHandlerRef.current) {
        container?.removeEventListener('keydown', containerKeydownHandlerRef.current);
      }
      resizeObserverRef.current?.disconnect();
      if (tableRef.current) {
        completeTableEdit(tableRef.current);
        tableRef.current.release();
      }
      tableRef.current = null;
    };
  }, []);

  return (
    <div className='rxdb-entity-table relative h-full w-full overflow-hidden'>
      <div className='absolute inset-0' ref={containerRef} />
      {records.length === 0 && !loading && (
        <div
          className='text-base-content/40 absolute inset-x-0 bottom-0 flex items-center justify-center text-sm'
          style={{ top: headerHeight }}
          aria-label='暂无数据'
          role='status'
        >
          <div className='empty-slot'>{emptyState}</div>
          <div className='empty-default flex flex-col items-center gap-3'>
            <svg
              aria-hidden='true'
              fill='none'
              height='40'
              stroke='currentColor'
              strokeLinecap='round'
              strokeLinejoin='round'
              strokeWidth='1.2'
              viewBox='0 0 24 24'
              width='40'
            >
              <rect height='18' rx='2' width='18' x='3' y='3' />
              <path d='M3 9h18' />
              <path d='M9 9v12' />
              <path d='M3 15h18' />
            </svg>
            <span>暂无数据</span>
          </div>
        </div>
      )}
      {loading && (
        <div className='bg-base-100/60 absolute inset-0 z-10 flex items-center justify-center'>
          <span className='loading loading-spinner loading-md text-primary' />
        </div>
      )}
      {loadingMore && (
        <div className='pointer-events-none absolute right-0 bottom-0 left-0 z-10 flex justify-center py-1.5'>
          <span className='loading loading-dots loading-sm text-primary' />
        </div>
      )}
      {cellTooltip && (
        <div
          className='bg-base-300 text-base-content border-base-300 pointer-events-none fixed z-[100] max-w-xs rounded border px-2 py-1.5 text-xs shadow-lg'
          style={{ left: cellTooltip.x, top: cellTooltip.y }}
          aria-atomic='true'
          aria-live='assertive'
          role='tooltip'
        >
          {cellTooltip.content}
        </div>
      )}
    </div>
  );
});
