// apps/dev-rxdb-react/src/app/pages/storage/components/StorageFileList.tsx
import { formatFileSize, STORAGE_TESTID } from '@aiao/utils';
import { Download, Eye, FolderOpen, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useRef } from 'react';
import { canPreviewFile, getFileIcon, getFileIconColor, StorageBrowserItem } from '../utils/storage-utils';

interface Props {
  entries: StorageBrowserItem[];
  currentPath: string;
  selectedPaths: Set<string>;
  onNavigate: (entry: StorageBrowserItem) => void;
  onDownload: (entry: StorageBrowserItem) => void;
  onDelete: (entry: StorageBrowserItem) => void;
  onPreview: (entry: StorageBrowserItem) => void;
  onContextMenu: (event: React.MouseEvent, entry: StorageBrowserItem) => void;
  onEntryClick: (entry: StorageBrowserItem, event: React.MouseEvent) => void;
}

function formatDate(timestamp?: number): string {
  if (!timestamp) return '-';

  return new Date(timestamp).toLocaleString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  });
}

export function StorageFileList({
  entries,
  selectedPaths,
  onNavigate,
  onDownload,
  onDelete,
  onPreview,
  onContextMenu,
  onEntryClick
}: Props) {
  const clickTimeoutRef = useRef<number | null>(null);
  const T = STORAGE_TESTID;

  useEffect(() => {
    return () => {
      if (clickTimeoutRef.current) {
        clearTimeout(clickTimeoutRef.current);
      }
    };
  }, []);

  const handleEntryClick = useCallback(
    (entry: StorageBrowserItem, event: React.MouseEvent) => {
      if (clickTimeoutRef.current) clearTimeout(clickTimeoutRef.current);
      clickTimeoutRef.current = window.setTimeout(() => {
        onEntryClick(entry, event);
        clickTimeoutRef.current = null;
      }, 250);
    },
    [onEntryClick]
  );

  const handleDoubleClick = useCallback(
    (entry: StorageBrowserItem) => {
      if (clickTimeoutRef.current) {
        clearTimeout(clickTimeoutRef.current);
        clickTimeoutRef.current = null;
      }

      if (entry.kind === 'directory') {
        onNavigate(entry);
        return;
      }

      onPreview(entry);
    },
    [onNavigate, onPreview]
  );

  return (
    <table className='table-zebra table select-none' data-testid={T.FILE_LIST}>
      <thead>
        <tr>
          <th>Name</th>
          <th className='w-32'>Size</th>
          <th className='w-40'>Modified</th>
          <th className='w-24'>Actions</th>
        </tr>
      </thead>
      <tbody>
        {entries.map(entry => {
          const Icon = getFileIcon(entry);
          const iconColor = getFileIconColor(entry);
          const isSelected = selectedPaths.has(entry.path);

          return (
            <tr
              key={entry.path}
              className={`cursor-pointer ${isSelected ? 'bg-primary/10' : 'hover:bg-base-200'}`}
              data-entry-path={entry.path}
              data-testid={entry.kind === 'file' ? T.FILE_ROW : undefined}
              onClick={event => handleEntryClick(entry, event)}
              onContextMenu={event => {
                event.preventDefault();
                onContextMenu(event, entry);
              }}
              onDoubleClick={() => handleDoubleClick(entry)}
            >
              <td className='font-medium' data-testid={entry.kind === 'file' ? T.FILE_NAME : undefined}>
                {entry.kind === 'directory' ?
                  <button
                    className='flex items-center gap-1.5 hover:underline'
                    onClick={event => {
                      event.stopPropagation();
                      onNavigate(entry);
                    }}
                  >
                    <Icon className={iconColor} size={16} />
                    {entry.name}
                  </button>
                : <div className='flex items-center gap-1.5'>
                    <Icon className={iconColor} size={16} />
                    <span>{entry.name}</span>
                  </div>
                }
              </td>
              <td
                className='text-base-content/60 text-sm'
                data-testid={entry.kind === 'file' ? T.FILE_SIZE : undefined}
              >
                {entry.kind === 'file' ? formatFileSize(entry.size || 0) : '-'}
              </td>
              <td className='text-base-content/60 text-sm'>{formatDate(entry.lastModified)}</td>
              <td>
                <div className='flex items-center gap-1'>
                  {entry.kind === 'directory' ?
                    <>
                      <button
                        className='btn btn-ghost btn-xs'
                        onClick={event => {
                          event.stopPropagation();
                          onNavigate(entry);
                        }}
                        title='Open'
                      >
                        <FolderOpen size={14} />
                      </button>
                      <button
                        className='btn btn-ghost btn-xs'
                        onClick={event => {
                          event.stopPropagation();
                          onDownload(entry);
                        }}
                        title='Download ZIP'
                      >
                        <Download size={14} />
                      </button>
                    </>
                  : <>
                      {canPreviewFile(entry) && (
                        <button
                          className='btn btn-ghost btn-xs'
                          data-testid={T.PREVIEW_BTN}
                          onClick={event => {
                            event.stopPropagation();
                            onPreview(entry);
                          }}
                          title='Preview'
                        >
                          <Eye size={14} />
                        </button>
                      )}
                      <button
                        className='btn btn-ghost btn-xs'
                        data-testid={T.DOWNLOAD_BTN}
                        onClick={event => {
                          event.stopPropagation();
                          onDownload(entry);
                        }}
                        title='Download'
                      >
                        <Download size={14} />
                      </button>
                    </>
                  }
                  <button
                    className='btn btn-ghost btn-xs text-error'
                    data-testid={entry.kind === 'file' ? T.DELETE_BTN : undefined}
                    onClick={event => {
                      event.stopPropagation();
                      onDelete(entry);
                    }}
                    title='Delete'
                  >
                    <Trash2 size={14} />
                  </button>
                </div>
              </td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
}

// apps/dev-rxdb-vue/src/pages/storage/components/StorageFileList.vue
<script lang="ts" setup>
import { formatFileSize, STORAGE_TESTID } from '@aiao/utils';
import { Download, Eye, FolderOpen, Trash2 } from '@lucide/vue';
import { ref } from 'vue';
import {
  canPreviewFile,
  formatDate,
  getFileIcon,
  getFileIconColor,
  type StorageBrowserItem
} from '../utils/storage-utils';

defineProps<{
  entries: StorageBrowserItem[];
  currentPath: string;
  selectedPaths: Set<string>;
}>();

const emit = defineEmits<{
  navigate: [entry: StorageBrowserItem];
  download: [entry: StorageBrowserItem];
  delete: [entry: StorageBrowserItem];
  preview: [entry: StorageBrowserItem];
  contextMenu: [payload: { event: MouseEvent; entry: StorageBrowserItem }];
  entryClick: [payload: { entry: StorageBrowserItem; event: MouseEvent }];
}>();

const clickTimeout = ref<number | null>(null);
const T = STORAGE_TESTID;

function handleEntryClick(entry: StorageBrowserItem, event: MouseEvent) {
  if (clickTimeout.value) clearTimeout(clickTimeout.value);
  clickTimeout.value = window.setTimeout(() => {
    emit('entryClick', { entry, event });
    clickTimeout.value = null;
  }, 250);
}

function handleDoubleClick(entry: StorageBrowserItem) {
  if (clickTimeout.value) {
    clearTimeout(clickTimeout.value);
    clickTimeout.value = null;
  }

  if (entry.kind === 'directory') {
    emit('navigate', entry);
    return;
  }

  emit('preview', entry);
}

function handleContextMenu(event: MouseEvent, entry: StorageBrowserItem) {
  event.preventDefault();
  emit('contextMenu', { event, entry });
}
</script>

<template>
  <table
    class="table-zebra table select-none"
    :data-testid="T.FILE_LIST"
  >
    <thead>
      <tr>
        <th>Name</th>
        <th class="w-32">Size</th>
        <th class="w-40">Modified</th>
        <th class="w-24">Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr
        class="cursor-pointer"
        v-for="entry in entries"
        :class="selectedPaths.has(entry.path) ? 'bg-primary/10' : 'hover:bg-base-200'"
        :data-entry-path="entry.path"
        :data-testid="T.FILE_ROW"
        :key="entry.path"
        @click="handleEntryClick(entry, $event)"
        @contextmenu="handleContextMenu($event, entry)"
        @dblclick="handleDoubleClick(entry)"
      >
        <td
          class="font-medium"
          :data-testid="T.FILE_NAME"
        >
          <button
            class="flex items-center gap-1.5 hover:underline"
            v-if="entry.kind === 'directory'"
            @click.stop="emit('navigate', entry)"
          >
            <component
              :class="getFileIconColor(entry)"
              :is="getFileIcon(entry)"
              :size="16"
            />
            {{ entry.name }}
          </button>
          <div
            class="flex items-center gap-1.5"
            v-else
          >
            <component
              :class="getFileIconColor(entry)"
              :is="getFileIcon(entry)"
              :size="16"
            />
            <span>{{ entry.name }}</span>
          </div>
        </td>
        <td
          class="text-base-content/60 text-sm"
          :data-testid="entry.kind === 'file' ? T.FILE_SIZE : undefined"
        >
          {{ entry.kind === 'file' ? formatFileSize(entry.size || 0) : '-' }}
        </td>
        <td class="text-base-content/60 text-sm">
          {{ formatDate(entry.lastModified) }}
        </td>
        <td>
          <div class="flex items-center gap-1">
            <template v-if="entry.kind === 'directory'">
              <button
                class="btn btn-ghost btn-xs"
                @click.stop="emit('navigate', entry)"
                title="Open"
              >
                <FolderOpen :size="14" />
              </button>
              <button
                class="btn btn-ghost btn-xs"
                @click.stop="emit('download', entry)"
                title="Download ZIP"
              >
                <Download :size="14" />
              </button>
            </template>
            <template v-else>
              <button
                class="btn btn-ghost btn-xs"
                v-if="canPreviewFile(entry)"
                :data-testid="T.PREVIEW_BTN"
                @click.stop="emit('preview', entry)"
                title="Preview"
              >
                <Eye :size="14" />
              </button>
              <button
                class="btn btn-ghost btn-xs"
                :data-testid="T.DOWNLOAD_BTN"
                @click.stop="emit('download', entry)"
                title="Download"
              >
                <Download :size="14" />
              </button>
            </template>
            <button
              class="btn btn-ghost btn-xs text-error"
              :data-testid="entry.kind === 'file' ? T.DELETE_BTN : undefined"
              @click.stop="emit('delete', entry)"
              title="Delete"
            >
              <Trash2 :size="14" />
            </button>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</template>
