// apps/dev-rxdb-react/src/app/pages/storage/components/StorageNewFolderDialog.tsx
import { STORAGE_TESTID } from '@aiao/utils';

interface StorageNewFolderDialogProps {
  name: string;
  show: boolean;
  onCancel: () => void;
  onConfirm: () => void;
  onNameChange: (name: string) => void;
}

export function StorageNewFolderDialog({
  name,
  show,
  onCancel,
  onConfirm,
  onNameChange
}: StorageNewFolderDialogProps): React.JSX.Element | null {
  const T = STORAGE_TESTID;

  if (!show) {
    return null;
  }

  return (
    <div className='modal modal-open' data-testid={T.NEW_FOLDER_DIALOG} onClick={onCancel}>
      <div className='modal-box' onClick={event => event.stopPropagation()}>
        <h3 className='mb-4 text-base font-bold'>New Folder</h3>
        <input
          className='input input-bordered w-full'
          data-testid={T.NEW_FOLDER_INPUT}
          onChange={event => onNameChange(event.target.value)}
          onKeyDown={event => event.key === 'Enter' && onConfirm()}
          placeholder='Folder name'
          type='text'
          value={name}
        />
        <div className='modal-action'>
          <button className='btn btn-sm' onClick={onCancel}>
            Cancel
          </button>
          <button className='btn btn-sm btn-primary' data-testid={T.NEW_FOLDER_CONFIRM} onClick={onConfirm}>
            Create
          </button>
        </div>
      </div>
    </div>
  );
}

// apps/dev-rxdb-vue/src/pages/storage/components/StorageNewFolderDialog.vue
<script lang="ts" setup>
import { STORAGE_TESTID } from '@aiao/utils';
import { ref, watch } from 'vue';

const props = defineProps<{ show: boolean }>();
const emit = defineEmits<{
  (e: 'confirm', name: string): void;
  (e: 'cancel'): void;
}>();

const T = STORAGE_TESTID;
const name = ref('');

watch(
  () => props.show,
  visible => {
    if (!visible) name.value = '';
  }
);

function submit(): void {
  if (!name.value.trim()) return;
  emit('confirm', name.value.trim());
}
</script>

<template>
  <div
    class="modal modal-open"
    v-if="show"
    :data-testid="T.NEW_FOLDER_DIALOG"
    @click="emit('cancel')"
  >
    <div
      class="modal-box"
      @click.stop
    >
      <h3 class="mb-4 text-base font-bold">New Folder</h3>
      <input
        class="input input-bordered w-full"
        v-model="name"
        :data-testid="T.NEW_FOLDER_INPUT"
        @keydown.enter="submit"
        placeholder="Folder name"
        type="text"
      />
      <div class="modal-action">
        <button
          class="btn btn-sm"
          @click="emit('cancel')"
        >
          Cancel
        </button>
        <button
          class="btn btn-sm btn-primary"
          :data-testid="T.NEW_FOLDER_CONFIRM"
          @click="submit"
        >
          Create
        </button>
      </div>
    </div>
  </div>
</template>
