// apps/dev-rxdb-react/src/app/pages/storage/components/StorageFileGrid.tsx
import { useRxDB } from '@aiao/rxdb-react';
import { formatFileSize, STORAGE_TESTID } from '@aiao/utils';
import { Download, Eye, FolderOpen, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useMemo, useRef } from 'react';
import { useObjectUrlMap } from '../../../hooks/loadObjectUrlMap';
import { canPreviewFile, getFileIcon, getFileIconColor, isImageFile, StorageBrowserItem } from '../utils/storage-utils';

interface Props {
  entries: StorageBrowserItem[];
  currentPath: string;
  selectedPaths: Set<string>;
  onNavigate: (entry: StorageBrowserItem) => void;
  onDownload: (entry: StorageBrowserItem) => void;
  onDelete: (entry: StorageBrowserItem) => void;
  onPreview: (entry: StorageBrowserItem) => void;
  onContextMenu: (event: React.MouseEvent, entry: StorageBrowserItem) => void;
  onEntryClick: (entry: StorageBrowserItem, event: React.MouseEvent) => void;
}

const getEntryPath = (entry: StorageBrowserItem) => entry.path;

export function StorageFileGrid({
  entries,
  selectedPaths,
  onNavigate,
  onDownload,
  onDelete,
  onPreview,
  onContextMenu,
  onEntryClick
}: Props) {
  const rxdb = useRxDB();
  const clickTimeoutRef = useRef<number | null>(null);
  const imageEntries = useMemo(
    () => entries.filter(entry => entry.kind === 'file' && entry.meta && isImageFile(entry)),
    [entries]
  );
  const loadThumbnail = useCallback(
    async (entry: StorageBrowserItem): Promise<string | null> => {
      if (!entry.meta) return null;
      return rxdb.storage.createObjectUrl(entry.meta.id);
    },
    [rxdb]
  );
  const revokeThumbnail = useCallback((url: string) => rxdb.storage.revokeObjectUrl(url), [rxdb]);
  const thumbnailUrls = useObjectUrlMap({
    items: imageEntries,
    getKey: getEntryPath,
    loadUrl: loadThumbnail,
    revokeUrl: revokeThumbnail
  });
  const T = STORAGE_TESTID;

  useEffect(() => {
    return () => {
      if (clickTimeoutRef.current) window.clearTimeout(clickTimeoutRef.current);
    };
  }, []);

  const handleEntryClick = useCallback(
    (entry: StorageBrowserItem, event: React.MouseEvent) => {
      if (clickTimeoutRef.current) clearTimeout(clickTimeoutRef.current);
      clickTimeoutRef.current = window.setTimeout(() => {
        onEntryClick(entry, event);
        clickTimeoutRef.current = null;
      }, 250);
    },
    [onEntryClick]
  );

  const handleDoubleClick = useCallback(
    (entry: StorageBrowserItem) => {
      if (clickTimeoutRef.current) {
        clearTimeout(clickTimeoutRef.current);
        clickTimeoutRef.current = null;
      }

      if (entry.kind === 'directory') {
        onNavigate(entry);
        return;
      }

      onPreview(entry);
    },
    [onNavigate, onPreview]
  );

  return (
    <div className='grid grid-cols-3 gap-3 p-3 select-none sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-8 xl:grid-cols-10 2xl:grid-cols-12'>
      {entries.map(entry => {
        const Icon = getFileIcon(entry);
        const iconColor = getFileIconColor(entry);
        const isSelected = selectedPaths.has(entry.path);

        return (
          <div
            key={entry.path}
            className={`group hover:bg-base-300 relative flex cursor-pointer flex-col items-center gap-1.5 rounded-lg p-1.5 transition-all ${isSelected ? 'bg-primary/20 ring-primary ring-2' : ''}`}
            data-entry-path={entry.path}
            onClick={event => handleEntryClick(entry, event)}
            onContextMenu={event => {
              event.preventDefault();
              onContextMenu(event, entry);
            }}
            onDoubleClick={() => handleDoubleClick(entry)}
            role='button'
            tabIndex={0}
          >
            <div className='flex h-16 w-full items-center justify-center'>
              {entry.kind === 'file' && isImageFile(entry) && thumbnailUrls.get(entry.path) ?
                <img
                  alt={entry.name}
                  className='h-full w-full rounded object-cover'
                  src={thumbnailUrls.get(entry.path)}
                />
              : <Icon className={iconColor} size={24} />}
            </div>

            <div className='w-full text-center'>
              <h2
                className='line-clamp-2 text-xs font-medium'
                data-testid={entry.kind === 'file' ? T.FILE_NAME : undefined}
                title={entry.name}
              >
                {entry.name}
              </h2>
              {entry.kind === 'file' && (
                <p className='text-base-content/60 text-[10px]' data-testid={T.FILE_SIZE}>
                  {formatFileSize(entry.size || 0)}
                </p>
              )}
            </div>

            <div className='absolute top-1 right-1 flex gap-0.5 opacity-0 transition-opacity group-hover:opacity-100'>
              {entry.kind === 'directory' ?
                <>
                  <button
                    className='btn btn-circle btn-ghost btn-xs bg-base-100/80 backdrop-blur'
                    onClick={event => {
                      event.stopPropagation();
                      onNavigate(entry);
                    }}
                    title='Open'
                  >
                    <FolderOpen size={12} />
                  </button>
                  <button
                    className='btn btn-circle btn-ghost btn-xs bg-base-100/80 backdrop-blur'
                    onClick={event => {
                      event.stopPropagation();
                      onDownload(entry);
                    }}
                    title='Download ZIP'
                  >
                    <Download size={12} />
                  </button>
                </>
              : <>
                  {canPreviewFile(entry) && (
                    <button
                      className='btn btn-circle btn-ghost btn-xs bg-base-100/80 backdrop-blur'
                      data-testid={T.PREVIEW_BTN}
                      onClick={event => {
                        event.stopPropagation();
                        onPreview(entry);
                      }}
                      title='Preview'
                    >
                      <Eye size={12} />
                    </button>
                  )}
                  <button
                    className='btn btn-circle btn-ghost btn-xs bg-base-100/80 backdrop-blur'
                    data-testid={T.DOWNLOAD_BTN}
                    onClick={event => {
                      event.stopPropagation();
                      onDownload(entry);
                    }}
                    title='Download'
                  >
                    <Download size={12} />
                  </button>
                </>
              }
              <button
                className='btn btn-circle btn-ghost btn-xs bg-base-100/80 text-error backdrop-blur'
                data-testid={entry.kind === 'file' ? T.DELETE_BTN : undefined}
                onClick={event => {
                  event.stopPropagation();
                  onDelete(entry);
                }}
                title='Delete'
              >
                <Trash2 size={12} />
              </button>
            </div>
          </div>
        );
      })}
    </div>
  );
}

// apps/dev-rxdb-vue/src/pages/storage/components/StorageFileGrid.vue
<script lang="ts" setup>
import { injectRxDB } from '@aiao/rxdb-vue';
import { formatFileSize, STORAGE_TESTID } from '@aiao/utils';
import { Download, Eye, FolderOpen, Trash2 } from '@lucide/vue';
import { onUnmounted, ref, watch } from 'vue';
import {
  canPreviewFile,
  getFileIcon,
  getFileIconColor,
  isImageFile,
  type StorageBrowserItem
} from '../utils/storage-utils';

const props = defineProps<{
  entries: StorageBrowserItem[];
  currentPath: string;
  selectedPaths: Set<string>;
}>();

const emit = defineEmits<{
  navigate: [entry: StorageBrowserItem];
  download: [entry: StorageBrowserItem];
  delete: [entry: StorageBrowserItem];
  preview: [entry: StorageBrowserItem];
  contextMenu: [payload: { event: MouseEvent; entry: StorageBrowserItem }];
  entryClick: [payload: { entry: StorageBrowserItem; event: MouseEvent }];
}>();

const rxdb = injectRxDB()!;
const thumbnailUrls = ref<Map<string, string>>(new Map());
const clickTimeout = ref<number | null>(null);
const T = STORAGE_TESTID;
let loadingThumbnails = false;
let lastHash = '';

watch(
  () => props.entries.map(entry => entry.path).join('|'),
  hash => {
    if (!hash) {
      thumbnailUrls.value.forEach(url => rxdb.storage.revokeObjectUrl(url));
      thumbnailUrls.value = new Map();
      lastHash = '';
      return;
    }

    if (hash === lastHash) {
      return;
    }

    lastHash = hash;

    if (!loadingThumbnails) {
      setTimeout(() => {
        void loadThumbnails();
      }, 0);
    }
  },
  { immediate: true }
);

onUnmounted(() => {
  if (clickTimeout.value) clearTimeout(clickTimeout.value);
  thumbnailUrls.value.forEach(url => rxdb.storage.revokeObjectUrl(url));
});

async function loadThumbnails() {
  if (loadingThumbnails) return;
  loadingThumbnails = true;

  try {
    const imageEntries = props.entries.filter(entry => entry.kind === 'file' && entry.meta && isImageFile(entry));
    const urls = new Map<string, string>();
    const concurrentLimit = 5;

    for (let index = 0; index < imageEntries.length; index += concurrentLimit) {
      const batch = imageEntries.slice(index, index + concurrentLimit);
      await Promise.all(
        batch.map(async entry => {
          if (!entry.meta) return;

          try {
            const url = await rxdb.storage.createObjectUrl(entry.meta.id);
            urls.set(entry.path, url);
          } catch {
            return;
          }
        })
      );
    }

    thumbnailUrls.value.forEach(url => rxdb.storage.revokeObjectUrl(url));
    thumbnailUrls.value = urls;
  } finally {
    loadingThumbnails = false;
  }
}

function handleEntryClick(entry: StorageBrowserItem, event: MouseEvent) {
  if (clickTimeout.value) clearTimeout(clickTimeout.value);
  clickTimeout.value = window.setTimeout(() => {
    emit('entryClick', { entry, event });
    clickTimeout.value = null;
  }, 250);
}

function handleDoubleClick(entry: StorageBrowserItem) {
  if (clickTimeout.value) {
    clearTimeout(clickTimeout.value);
    clickTimeout.value = null;
  }

  if (entry.kind === 'directory') {
    emit('navigate', entry);
    return;
  }

  emit('preview', entry);
}

function handleContextMenu(event: MouseEvent, entry: StorageBrowserItem) {
  event.preventDefault();
  emit('contextMenu', { event, entry });
}
</script>

<template>
  <div
    class="grid grid-cols-3 gap-3 p-3 select-none sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-8 xl:grid-cols-10 2xl:grid-cols-12"
  >
    <div
      class="group hover:bg-base-300 relative flex cursor-pointer flex-col items-center gap-1.5 rounded-lg p-1.5 transition-all"
      v-for="entry in entries"
      :class="selectedPaths.has(entry.path) ? 'bg-primary/20 ring-primary ring-2' : ''"
      :data-entry-path="entry.path"
      :data-testid="T.FILE_ROW"
      :key="entry.path"
      @click="handleEntryClick(entry, $event)"
      @contextmenu="handleContextMenu($event, entry)"
      @dblclick="handleDoubleClick(entry)"
      role="button"
      tabindex="0"
    >
      <div class="flex h-16 w-full items-center justify-center">
        <img
          class="h-full w-full rounded object-cover"
          v-if="entry.kind === 'file' && isImageFile(entry) && thumbnailUrls.get(entry.path)"
          :alt="entry.name"
          :src="thumbnailUrls.get(entry.path)"
        />
        <component
          v-else
          :class="getFileIconColor(entry)"
          :is="getFileIcon(entry)"
          :size="24"
        />
      </div>

      <div class="w-full text-center">
        <h2
          class="line-clamp-2 text-xs font-medium"
          :data-testid="T.FILE_NAME"
          :title="entry.name"
        >
          {{ entry.name }}
        </h2>
        <p
          class="text-base-content/60 text-[10px]"
          v-if="entry.kind === 'file'"
          :data-testid="T.FILE_SIZE"
        >
          {{ formatFileSize(entry.size || 0) }}
        </p>
      </div>

      <div class="absolute top-1 right-1 flex gap-0.5 opacity-0 transition-opacity group-hover:opacity-100">
        <template v-if="entry.kind === 'directory'">
          <button
            class="btn btn-circle btn-ghost btn-xs bg-base-100/80 backdrop-blur"
            @click.stop="emit('navigate', entry)"
            title="Open"
          >
            <FolderOpen :size="12" />
          </button>
          <button
            class="btn btn-circle btn-ghost btn-xs bg-base-100/80 backdrop-blur"
            @click.stop="emit('download', entry)"
            title="Download ZIP"
          >
            <Download :size="12" />
          </button>
        </template>
        <template v-else>
          <button
            class="btn btn-circle btn-ghost btn-xs bg-base-100/80 backdrop-blur"
            v-if="canPreviewFile(entry)"
            :data-testid="T.PREVIEW_BTN"
            @click.stop="emit('preview', entry)"
            title="Preview"
          >
            <Eye :size="12" />
          </button>
          <button
            class="btn btn-circle btn-ghost btn-xs bg-base-100/80 backdrop-blur"
            :data-testid="T.DOWNLOAD_BTN"
            @click.stop="emit('download', entry)"
            title="Download"
          >
            <Download :size="12" />
          </button>
        </template>
        <button
          class="btn btn-circle btn-ghost btn-xs bg-base-100/80 text-error backdrop-blur"
          :data-testid="entry.kind === 'file' ? T.DELETE_BTN : undefined"
          @click.stop="emit('delete', entry)"
          title="Delete"
        >
          <Trash2 :size="12" />
        </button>
      </div>
    </div>
  </div>
</template>
