// apps/dev-rxdb-react/src/app/pages/storage/components/StorageRenameDialog.tsx
import { STORAGE_TESTID } from '@aiao/utils';
import type { StorageBrowserItem } from '../utils/storage-utils';

interface StorageRenameDialogProps {
  entry: StorageBrowserItem | null;
  newName: string;
  show: boolean;
  onCancel: () => void;
  onConfirm: () => void;
  onNameChange: (name: string) => void;
}

export function StorageRenameDialog({
  entry,
  newName,
  show,
  onCancel,
  onConfirm,
  onNameChange
}: StorageRenameDialogProps): React.JSX.Element | null {
  const T = STORAGE_TESTID;

  if (!show || !entry) {
    return null;
  }

  return (
    <div className='modal modal-open' data-testid={T.RENAME_DIALOG} onClick={onCancel}>
      <div className='modal-box' onClick={event => event.stopPropagation()}>
        <h3 className='mb-4 text-base font-bold'>Rename {entry.kind === 'file' ? 'File' : 'Folder'}</h3>
        <input
          className='input input-bordered w-full'
          data-testid={T.RENAME_INPUT}
          onChange={event => onNameChange(event.target.value)}
          onKeyDown={event => event.key === 'Enter' && onConfirm()}
          placeholder={entry.kind === 'file' ? 'File name' : 'Folder name'}
          type='text'
          value={newName}
        />
        <div className='modal-action'>
          <button className='btn btn-sm' onClick={onCancel}>
            Cancel
          </button>
          <button className='btn btn-sm btn-primary' data-testid={T.RENAME_CONFIRM} onClick={onConfirm}>
            Confirm
          </button>
        </div>
      </div>
    </div>
  );
}

// apps/dev-rxdb-vue/src/pages/storage/components/StorageRenameDialog.vue
<script lang="ts" setup>
import { STORAGE_TESTID } from '@aiao/utils';
import { ref, watch } from 'vue';
import type { StorageBrowserItem } from '../utils/storage-utils';

const props = defineProps<{ show: boolean; entry: StorageBrowserItem | null }>();
const emit = defineEmits<{
  (e: 'confirm', name: string): void;
  (e: 'cancel'): void;
}>();

const T = STORAGE_TESTID;
const newName = ref('');

watch(
  () => props.entry,
  entry => {
    newName.value = entry?.name ?? '';
  },
  { immediate: true }
);

function submit(): void {
  if (!newName.value.trim()) return;
  emit('confirm', newName.value.trim());
}
</script>

<template>
  <div
    class="modal modal-open"
    v-if="show && entry"
    :data-testid="T.RENAME_DIALOG"
    @click="emit('cancel')"
  >
    <div
      class="modal-box"
      @click.stop
    >
      <h3 class="mb-4 text-base font-bold">Rename {{ entry.kind === 'file' ? 'File' : 'Folder' }}</h3>
      <input
        class="input input-bordered w-full"
        v-model="newName"
        :data-testid="T.RENAME_INPUT"
        :placeholder="entry.kind === 'file' ? 'File name' : 'Folder name'"
        @keydown.enter="submit"
        type="text"
      />
      <div class="modal-action">
        <button
          class="btn btn-sm"
          @click="emit('cancel')"
        >
          Cancel
        </button>
        <button
          class="btn btn-sm btn-primary"
          :data-testid="T.RENAME_CONFIRM"
          @click="submit"
        >
          Confirm
        </button>
      </div>
    </div>
  </div>
</template>
