// apps/dev-rxdb-react/src/app/pages/storage/components/StorageContextMenu.tsx
import { STORAGE_TESTID } from '@aiao/utils';
import { Download, Edit3, Eye, FolderOpen, Trash2 } from 'lucide-react';
import type { StorageBrowserItem } from '../utils/storage-utils';

export type StorageContextMenuAction = 'view' | 'download' | 'rename' | 'delete';

interface StorageContextMenuProps {
  entry: StorageBrowserItem | null;
  show: boolean;
  x: number;
  y: number;
  onAction: (action: StorageContextMenuAction) => void;
}

export function StorageContextMenu({ entry, show, x, y, onAction }: StorageContextMenuProps): React.JSX.Element | null {
  const T = STORAGE_TESTID;

  if (!show || !entry) {
    return null;
  }

  return (
    // P1-4：容器必须是 <ul>。菜单项是 <li>，而 <li> 的内容模型要求父级为 ul / ol / menu，
    // 挂在 <div> 下浏览器不给 list 语义，辅助技术读不到"这是一个 4 项菜单"。
    // （daisyUI 的 `menu` 类本身也是给 <ul> 用的。）
    <ul
      className='menu border-base-content/10 bg-base-300/95 fixed z-50 w-40 rounded-lg border p-1.5 text-sm shadow-2xl'
      data-testid={T.CONTEXT_MENU}
      onClick={event => event.stopPropagation()}
      style={{
        left: x,
        top: y,
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)'
      }}
    >
      <li>
        <button
          className='w-full gap-2 px-2 py-1.5 text-left'
          data-testid={T.CONTEXT_VIEW}
          onClick={() => onAction('view')}
          type='button'
        >
          {entry.kind === 'file' ?
            <>
              <Eye size={14} />
              <span>View</span>
            </>
          : <>
              <FolderOpen size={14} />
              <span>Open</span>
            </>
          }
        </button>
      </li>
      <li>
        <button
          className='w-full gap-2 px-2 py-1.5 text-left'
          data-testid={T.CONTEXT_DOWNLOAD}
          onClick={() => onAction('download')}
          type='button'
        >
          <Download size={14} />
          <span>{entry.kind === 'file' ? 'Download' : 'Download ZIP'}</span>
        </button>
      </li>
      <li>
        <button
          className='w-full gap-2 px-2 py-1.5 text-left'
          data-testid={T.CONTEXT_RENAME}
          onClick={() => onAction('rename')}
          type='button'
        >
          <Edit3 size={14} />
          <span>Rename</span>
        </button>
      </li>
      <li>
        <button
          className='text-error w-full gap-2 px-2 py-1.5 text-left'
          data-testid={T.CONTEXT_DELETE}
          onClick={() => onAction('delete')}
          type='button'
        >
          <Trash2 size={14} />
          <span>Delete</span>
        </button>
      </li>
    </ul>
  );
}

// apps/dev-rxdb-vue/src/pages/storage/components/StorageContextMenu.vue
<script lang="ts" setup>
import { STORAGE_TESTID } from '@aiao/utils';
import { Download, Edit3, Eye, FolderOpen, Trash2 } from '@lucide/vue';
import type { StorageBrowserItem } from '../utils/storage-utils';

defineProps<{
  show: boolean;
  x: number;
  y: number;
  entry: StorageBrowserItem | null;
}>();

const emit = defineEmits<{
  (e: 'action', action: 'view' | 'download' | 'rename' | 'delete'): void;
}>();

const T = STORAGE_TESTID;
</script>

<template>
  <div
    class="menu border-base-content/10 bg-base-300/95 fixed z-50 w-40 rounded-lg border p-1.5 text-sm shadow-2xl"
    v-if="show && entry"
    :data-testid="T.CONTEXT_MENU"
    :style="{
      left: x + 'px',
      top: y + 'px',
      backdropFilter: 'blur(12px)',
      WebkitBackdropFilter: 'blur(12px)'
    }"
    @click.stop
  >
    <li>
      <button
        class="w-full gap-2 px-2 py-1.5 text-left"
        :data-testid="T.CONTEXT_VIEW"
        @click="emit('action', 'view')"
        type="button"
      >
        <Eye
          v-if="entry.kind === 'file'"
          :size="14"
        />
        <FolderOpen
          v-else
          :size="14"
        />
        <span>{{ entry.kind === 'file' ? 'View' : 'Open' }}</span>
      </button>
    </li>
    <li>
      <button
        class="w-full gap-2 px-2 py-1.5 text-left"
        :data-testid="T.CONTEXT_DOWNLOAD"
        @click="emit('action', 'download')"
        type="button"
      >
        <Download :size="14" />
        <span>{{ entry.kind === 'file' ? 'Download' : 'Download ZIP' }}</span>
      </button>
    </li>
    <li>
      <button
        class="w-full gap-2 px-2 py-1.5 text-left"
        :data-testid="T.CONTEXT_RENAME"
        @click="emit('action', 'rename')"
        type="button"
      >
        <Edit3 :size="14" />
        <span>Rename</span>
      </button>
    </li>
    <li>
      <button
        class="text-error w-full gap-2 px-2 py-1.5 text-left"
        :data-testid="T.CONTEXT_DELETE"
        @click="emit('action', 'delete')"
        type="button"
      >
        <Trash2 :size="14" />
        <span>Delete</span>
      </button>
    </li>
  </div>
</template>
