// apps/dev-rxdb-angular/src/app/app.ts
import { requestIdleCallbackPolyfill } from '@aiao/utils';
import { isPlatformBrowser } from '@angular/common';
import { ChangeDetectionStrategy, Component, DOCUMENT, inject, OnInit, PLATFORM_ID } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { SwUpdatesService } from '@modules/angular';
import { NgxLoadingBar } from '@ngx-loading-bar/core';
import { AppService } from './app.service';
import { AppHeader } from './components/app-header';
import { AppSidebar } from './components/app-sidebar';

@Component({
  imports: [RouterOutlet, AppSidebar, AppHeader, NgxLoadingBar],
  selector: 'app-root',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ngx-loading-bar></ngx-loading-bar>
    <div class="flex size-full" id="layout-main">
      @if (app.$sidebarPinned()) {
        <div
          class="sidebar-overlay md:hidden"
          (click)="app.toggleSidebar()"
          aria-hidden="true"
          aria-label="Close sidebar"
        ></div>
      }
      <app-sidebar></app-sidebar>
      <div class="flex h-full min-w-0 grow flex-col overflow-auto" id="layout-container">
        <app-header></app-header>
        <div id="layout-content">
          <router-outlet></router-outlet>
        </div>
      </div>
    </div>
  `,
  styles: [],
  host: {
    '[class.left-menu-pinned]': 'app.$sidebarPinned()',
    '[class.header-floating]': 'app.$headerFloating()'
  }
})
export class App implements OnInit {
  #document = inject(DOCUMENT);

  #swUpdatesService = inject(SwUpdatesService);
  app = inject(AppService);
  isBrowser = isPlatformBrowser(inject(PLATFORM_ID));

  ngOnInit(): void {
    const local = Intl.DateTimeFormat().resolvedOptions().locale;
    this.#document.documentElement.lang = local;

    if (this.isBrowser) {
      // safari 不支持 requestIdleCallback
      requestIdleCallbackPolyfill();
      this.#swUpdatesService.enable();
    }
  }
}

// apps/dev-rxdb-vue/src/app/App.vue
<script lang="ts" setup>
import { provideRxDB } from '@aiao/rxdb-vue';
import { onMounted, ref } from 'vue';
import { RouterView, useRouter } from 'vue-router';
import AppHeader from './components/AppHeader.vue';
import AppSidebar from './components/AppSidebar.vue';
import AppToast from './components/AppToast.vue';
import LoadingBar from './components/LoadingBar.vue';
import { useAppService } from './composables/useAppService';
import { useTheme } from './composables/useTheme';
import setup_rxdb from './rxdb/setup_rxdb_sqlite-wasm';

const db = setup_rxdb();
provideRxDB(db);

useTheme();
const { sidebarPinned, headerFloating, toggleSidebar } = useAppService();

// Loading bar
const loadingBarRef = ref<InstanceType<typeof LoadingBar>>();
const router = useRouter();

onMounted(() => {
  const locale = Intl.DateTimeFormat().resolvedOptions().locale;
  document.documentElement.lang = locale;
});

router.beforeEach(() => {
  loadingBarRef.value?.continuousStart();
});

router.afterEach(() => {
  loadingBarRef.value?.complete();
});

router.onError(() => {
  loadingBarRef.value?.complete();
});
</script>

<template>
  <div
    id="layout-main"
    :class="['flex size-full', { 'left-menu-pinned': sidebarPinned, 'header-floating': headerFloating }]"
  >
    <LoadingBar
      :shadow="true"
      color="#f11946"
      ref="loadingBarRef"
    />
    <AppToast />
    <div
      class="sidebar-overlay md:hidden"
      v-if="sidebarPinned"
      @click="toggleSidebar"
      aria-label="Close sidebar"
    />
    <AppSidebar />
    <div
      class="flex h-full min-w-0 grow flex-col overflow-hidden"
      id="layout-container"
    >
      <AppHeader />
      <div
        class="flex min-h-0 flex-1 flex-col overflow-auto"
        id="layout-content"
      >
        <RouterView />
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped></style>
