// packages/rxdb-model-vue/src/query-builder/popover-select/PopoverSelect.vue
<script lang="ts" setup>
/**
 * 基于 Popover API 的下拉选择组件（对齐 Angular 侧 `PopoverSelectComponent`）。
 *
 * 使用浏览器原生 Popover API 渲染选项列表（top layer，`overflow` 容器内不被裁剪）；
 * 支持关键字过滤、键盘导航（↑↓ 循环移动、Enter 选中、Escape 关闭）、
 * 打开自动高亮第一项，搜索后也自动高亮第一条结果。
 */
import { applyPopoverPosition, findOptionLabel } from '@aiao/rxdb-model';
import { computed, ref, watch } from 'vue';

let moduleUid = 0;

const props = withDefaults(
  defineProps<{
    /** 选项列表 */
    options: ReadonlyArray<{ value: string; label: string }>;
    /** 当前选中值 */
    selected?: string;
    /** 未选中时的占位文案 */
    placeholder?: string;
    /** 最小宽度 */
    minWidth?: string;
  }>(),
  { selected: '', placeholder: '请选择', minWidth: '8rem' }
);

const emit = defineEmits<{
  /** 选中某个选项 */
  selectChange: [value: string];
}>();

const uid = `rxdb-ps-${++moduleUid}`;
const listId = `${uid}-list`;
const filterText = ref('');
const activeIndex = ref(0);

const trigger = ref<HTMLButtonElement | null>(null);
const popoverEl = ref<HTMLElement | null>(null);
const filterInput = ref<HTMLInputElement | null>(null);

const currentLabel = computed(() => findOptionLabel(props.options, props.selected, props.placeholder));

const filteredOptions = computed(() => {
  const filter = filterText.value.toLowerCase().trim();
  if (!filter) return props.options;
  return props.options.filter(opt => opt.label.toLowerCase().includes(filter));
});

const activeItemId = computed(() => {
  const idx = activeIndex.value;
  const opts = filteredOptions.value;
  return idx >= 0 && idx < opts.length ? `${uid}-opt-${opts[idx].value}` : null;
});

// 过滤结果变化时高亮自动回到第一项
watch(filteredOptions, () => {
  activeIndex.value = 0;
});

const onBeforeToggle = (event: Event): void => {
  const te = event as ToggleEvent;
  if (te.newState === 'open') {
    if (popoverEl.value && trigger.value) {
      applyPopoverPosition(popoverEl.value, trigger.value.getBoundingClientRect());
    }
    filterText.value = '';
  }
};

const onToggle = (event: Event): void => {
  if ((event as ToggleEvent).newState === 'open') {
    filterInput.value?.focus();
    activeIndex.value = 0;
  }
};

const onKeydown = (event: KeyboardEvent): void => {
  const opts = filteredOptions.value;
  const len = opts.length;

  switch (event.key) {
    case 'ArrowDown': {
      event.preventDefault();
      if (len > 0) {
        activeIndex.value = (activeIndex.value + 1) % len;
        scrollActiveIntoView();
      }
      break;
    }
    case 'ArrowUp': {
      event.preventDefault();
      if (len > 0) {
        activeIndex.value = (activeIndex.value - 1 + len) % len;
        scrollActiveIntoView();
      }
      break;
    }
    case 'Enter': {
      event.preventDefault();
      const opt = opts[activeIndex.value];
      if (opt) onSelect(opt.value);
      break;
    }
    case 'Escape': {
      event.preventDefault();
      popoverEl.value?.hidePopover();
      trigger.value?.focus();
      break;
    }
    case 'Tab': {
      popoverEl.value?.hidePopover();
      break;
    }
  }
};

const onSelect = (value: string): void => {
  emit('selectChange', value);
  popoverEl.value?.hidePopover();
  trigger.value?.focus();
};

const scrollActiveIntoView = (): void => {
  const opts = filteredOptions.value;
  const opt = opts[activeIndex.value];
  if (!opt) return;
  document.getElementById(`${uid}-opt-${opt.value}`)?.scrollIntoView({ block: 'nearest' });
};

defineExpose({
  uid,
  listId,
  currentLabel,
  filteredOptions,
  activeItemId,
  filterText,
  activeIndex,
  onBeforeToggle,
  onToggle,
  onKeydown,
  onSelect
});
</script>

<template>
  <button
    ref="trigger"
    class="select select-sm text-left"
    :popovertarget="uid"
    :style="{ 'min-width': minWidth }"
    type="button"
  >
    {{ currentLabel }}
  </button>
  <div
    :id="uid"
    ref="popoverEl"
    class="bg-base-100 rounded-box border-base-300 border shadow-xl"
    :style="{ 'min-width': minWidth }"
    popover
    tabindex="-1"
    @beforetoggle="onBeforeToggle"
    @keydown="onKeydown"
    @toggle="onToggle"
  >
    <div class="mb-1 p-2">
      <input
        ref="filterInput"
        v-model="filterText"
        class="input input-sm w-full"
        :aria-activedescendant="activeItemId ?? undefined"
        :aria-controls="listId"
        aria-autocomplete="list"
        aria-expanded="true"
        placeholder="搜索..."
        role="combobox"
        type="text"
      />
    </div>
    <ul
      :id="listId"
      class="menu menu-sm max-h-60 w-full flex-nowrap overflow-y-auto px-2"
      role="listbox"
    >
      <li
        v-for="(option, i) in filteredOptions"
        :key="option.value"
        role="none"
      >
        <button
          :id="`${uid}-opt-${option.value}`"
          class="flex w-full items-center text-left text-sm"
          :aria-selected="option.value === selected"
          :class="{
            'bg-primary/15': option.value === selected,
            'font-semibold': option.value === selected,
            'menu-focus': activeIndex === i
          }"
          role="option"
          type="button"
          @click="onSelect(option.value)"
        >
          <span class="grow">{{ option.label }}</span>
          <svg
            v-if="option.value === selected"
            class="text-primary h-3 w-3 shrink-0"
            fill="none"
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2.5"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <polyline points="20 6 9 17 4 12" />
          </svg>
        </button>
      </li>
      <li
        v-if="filteredOptions.length === 0"
        class="px-3 py-1.5 text-sm opacity-50"
      >
        无匹配项
      </li>
    </ul>
  </div>
</template>

// packages/rxdb-model-angular/src/query-builder/popover-select/popover-select.component.ts
import { applyPopoverPosition, findOptionLabel } from '@aiao/rxdb-model';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  ElementRef,
  input,
  output,
  signal,
  untracked,
  viewChild
} from '@angular/core';
import { FormsModule } from '@angular/forms';

let _uid = 0;

/**
 * 基于 Popover API 的下拉选择组件
 *
 * @description
 * 使用浏览器原生 Popover API 渲染选项列表，在 top layer 渲染，
 * 确保在 `overflow: auto/hidden` 容器内也不会被裁剪。
 * 支持关键字过滤、键盘导航（↑↓ 移动、Enter 选中、Escape 关闭）。
 * 打开弹框自动高亮第一项，搜索后也自动高亮第一条结果。
 */
@Component({
  selector: 'rxdb-popover-select',
  standalone: true,
  imports: [FormsModule],
  template: `
    <button
      class="select select-sm text-left"
      #trigger
      [attr.popovertarget]="uid"
      [style.min-width]="minWidth()"
      type="button"
    >
      {{ currentLabel() }}
    </button>
    <div
      class="bg-base-100 rounded-box border-base-300 border shadow-xl"
      #popoverEl
      [id]="uid"
      [style.min-width]="minWidth()"
      (beforetoggle)="onBeforeToggle($event)"
      (keydown)="onKeydown($event)"
      (toggle)="onToggle($event)"
      popover
      tabindex="-1"
    >
      <div class="mb-1 p-2">
        <input
          class="input input-sm w-full"
          #filterInput
          [attr.aria-activedescendant]="activeItemId()"
          [attr.aria-controls]="listId"
          [attr.aria-expanded]="true"
          [ngModel]="filterText()"
          (ngModelChange)="filterText.set($event)"
          aria-autocomplete="list"
          placeholder="搜索..."
          role="combobox"
          type="text"
        />
      </div>
      <ul class="menu menu-sm max-h-60 w-full flex-nowrap overflow-y-auto px-2" [id]="listId" role="listbox">
        @for (option of filteredOptions(); track option.value; let i = $index) {
          <li role="none">
            <button
              class="flex w-full items-center text-left text-sm"
              [attr.aria-selected]="option.value === selected()"
              [class.bg-primary/15]="option.value === selected()"
              [class.font-semibold]="option.value === selected()"
              [class.menu-focus]="activeIndex() === i"
              [id]="uid + '-opt-' + option.value"
              (click)="onSelect(option.value)"
              role="option"
              type="button"
            >
              <span class="grow">{{ option.label }}</span>
              @if (option.value === selected()) {
                <svg
                  class="text-primary h-3 w-3 shrink-0"
                  fill="none"
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2.5"
                  viewBox="0 0 24 24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <polyline points="20 6 9 17 4 12" />
                </svg>
              }
            </button>
          </li>
        } @empty {
          <li class="px-3 py-1.5 text-sm opacity-50">无匹配项</li>
        }
      </ul>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class PopoverSelectComponent {
  private readonly trigger = viewChild.required<ElementRef<HTMLButtonElement>>('trigger');
  private readonly popoverEl = viewChild.required<ElementRef<HTMLElement>>('popoverEl');
  private readonly filterInput = viewChild<ElementRef<HTMLInputElement>>('filterInput');

  protected readonly uid = `rxdb-ps-${++_uid}`;
  protected readonly listId = `${this.uid}-list`;
  protected readonly filterText = signal('');
  protected readonly activeIndex = signal(0);

  readonly options = input.required<ReadonlyArray<{ value: string; label: string }>>();
  readonly selected = input<string>('');
  readonly placeholder = input<string>('请选择');
  readonly minWidth = input<string>('8rem');

  readonly selectChange = output<string>();

  readonly currentLabel = computed(() => findOptionLabel(this.options(), this.selected(), this.placeholder()));

  readonly filteredOptions = computed(() => {
    const filter = this.filterText().toLowerCase().trim();
    if (!filter) return this.options();
    return this.options().filter(opt => opt.label.toLowerCase().includes(filter));
  });

  readonly activeItemId = computed(() => {
    const idx = this.activeIndex();
    const opts = this.filteredOptions();
    return idx >= 0 && idx < opts.length ? `${this.uid}-opt-${opts[idx].value}` : null;
  });

  constructor() {
    effect(() => {
      this.filteredOptions();
      untracked(() => this.activeIndex.set(0));
    });
  }

  onBeforeToggle(event: Event): void {
    const te = event as ToggleEvent;
    if (te.newState === 'open') {
      applyPopoverPosition(this.popoverEl().nativeElement, this.trigger().nativeElement.getBoundingClientRect());
      this.filterText.set('');
    }
  }

  onToggle(event: Event): void {
    if ((event as ToggleEvent).newState === 'open') {
      this.filterInput()?.nativeElement.focus();
      this.activeIndex.set(0);
    }
  }

  onKeydown(event: KeyboardEvent): void {
    const opts = this.filteredOptions();
    const len = opts.length;

    switch (event.key) {
      case 'ArrowDown': {
        event.preventDefault();
        if (len > 0) {
          this.activeIndex.update(i => (i + 1) % len);
          this.scrollActiveIntoView();
        }
        break;
      }
      case 'ArrowUp': {
        event.preventDefault();
        if (len > 0) {
          this.activeIndex.update(i => (i - 1 + len) % len);
          this.scrollActiveIntoView();
        }
        break;
      }
      case 'Enter': {
        event.preventDefault();
        const opt = opts[this.activeIndex()];
        if (opt) this.onSelect(opt.value);
        break;
      }
      case 'Escape': {
        event.preventDefault();
        this.popoverEl().nativeElement.hidePopover();
        this.trigger().nativeElement.focus();
        break;
      }
      case 'Tab': {
        this.popoverEl().nativeElement.hidePopover();
        break;
      }
    }
  }

  onSelect(value: string): void {
    this.selectChange.emit(value);
    this.popoverEl().nativeElement.hidePopover();
    this.trigger().nativeElement.focus();
  }

  private scrollActiveIntoView(): void {
    const opts = this.filteredOptions();
    const opt = opts[this.activeIndex()];
    if (!opt) return;
    document.getElementById(`${this.uid}-opt-${opt.value}`)?.scrollIntoView({ block: 'nearest' });
  }
}
